In [228]:
import pandas as pd
import os
import re


def extract_stat_name(filename):
    # Extract the stat name from the filename
    match = filename.split("_")[2:][0].split(".")[0]

    return match


# print(extract_stat_name("df_season9_player-successful-raids.csv"))


def merge_csvs(directory):
    # Get all CSV files in the directory
    csv_files = [f for f in os.listdir(directory) if f.endswith(".csv")]

    # Initialize an empty list to store dataframes
    dfs = []

    for file in csv_files:
        # Read each CSV file
        df = pd.read_csv(os.path.join(directory, file))

        # Ensure 'player_id' is in the dataframe
        if "player_id" not in df.columns:
            print(f"Warning: 'player_id' not found in {file}. Skipping this file.")
            continue

        # Extract the stat name from the filename
        stat_name = extract_stat_name(file)

        # Rename columns to avoid conflicts
        for col in df.columns:
            if col != "player_id":
                df.rename(columns={col: f"{stat_name}_{col}"}, inplace=True)

        dfs.append(df)

    # Merge all dataframes
    merged_df = dfs[0]
    for df in dfs[1:]:
        merged_df = pd.merge(merged_df, df, on="player_id", how="outer")

    return merged_df


# Get directory from user
directory = "./season10"

# Merge CSVs
result = merge_csvs(directory)


# result.head()

In [229]:
len(list(result.columns))

122

In [230]:
player_name = []
match_played = []
value = []
team_id = []
team = []
team_name = []
rank = []
position_id = []
position_name = []
team_full_name = []
points_per_match = []


for col in result.columns:

    # 'player-total-points_player_name',
    # 'player-total-points_match_played',
    # 'player-total-points_value',
    # 'player-total-points_team_id',
    # 'player-total-points_team',
    # 'player-total-points_team_name',
    # 'player-total-points_rank',
    # 'player-total-points_position_id',
    # 'player-total-points_position_name',
    # 'player-total-points_team_full_name',
    # 'player-total-points_points_per_match',

    if col.endswith("_player_name"):
        player_name.append(col)

    if col.endswith("_match_played"):
        match_played.append(col)

    if col.endswith("_value"):
        value.append(col)

    if col.endswith("_team_id"):
        team_id.append(col)

    if col.endswith("_team"):
        team.append(col)

    if col.endswith("_team_name"):
        team_name.append(col)

    if col.endswith("_rank"):
        rank.append(col)

    if col.endswith("_position_id"):
        position_id.append(col)

    if col.endswith("_position_name"):
        position_name.append(col)

    if col.endswith("_team_full_name"):
        team_full_name.append(col)
        
    if col.endswith("_per_match"):
        points_per_match.append(col)

In [231]:
cols = [
    player_name, #
match_played,#####
value, ###
team_id,
team,####
team_name,#####
rank,#####
position_id,
position_name, ####
team_full_name, ####
points_per_match, ####
]
sum_of_cols = 0

for col in cols:
    print(len(col))
    sum_of_cols += len(col)

print(sum_of_cols)
# other_cols

11
11
11
11
11
11
11
11
11
11
11
121

In [232]:
l = [
    player_name
    + match_played
    + position_name
    + team
    + team_name
    + team_full_name
    + rank
    + value
    + points_per_match
    + team_id
    + position_id
]

In [233]:
# print(l)

In [234]:
# Display info about the merged dataframe
# print(result.info())

result = result[l[0]]

# Save the merged dataframe
output_file = directory + "/" + "merged_player_stats_all.csv"
result.to_csv(output_file, index=False)
print(f"Merged dataframe has been saved to '{output_file}'")

Merged dataframe has been saved to './season10/merged_player_stats_all.csv'

In [ ]:
bbb

## ignore the code below

In [1]:
import os

In [7]:
for i in os.listdir("."):
    if i.endswith(".csv") and "season1" in i:
        print(i)

1_df_season1_player-total-points.csv
11_df_season1_super-10s.csv
8_df_season1_player-dod-raid-points.csv
2_df_season1_player-successful-raids.csv
3_df_season1_player-raid-points.csv
9_df_season1_player-super-raids.csv
4_df_season1_player-successful-tackles.csv
5_df_season1_player-tackle-points.csv
7_df_season1_player-avg-tackle-points.csv
10_df_season1_player-super-tackles.csv
12_df_season1_high-5s.csv

In [14]:
import pandas as pd
import glob

# # Load all CSV files into a list of dataframes
# file_paths = [
#     "./1_df_season1_player-total-points.csv",
#     "./2_df_season1_player-successful-raids.csv",
#     "./3_df_season1_player-raid-points.csv",
#     "./4_df_season1_player-successful-tackles.csv",
#     "./5_df_season1_player-tackle-points.csv",
#     "./7_df_season1_player-avg-tackle-points.csv",
#     "./8_df_season1_player-dod-raid-points.csv",
#     "./9_df_season1_player-super-raids.csv",
#     "./10_df_season1_player-super-tackles.csv",
#     "./11_df_season1_super-10s.csv",
#     "./12_df_season1_high-5s.csv",
# ]

# # Reading all dataframes
# dfs = [pd.read_csv(file) for file in file_paths]

file_map = {
    "./1_df_season1_player-total-points.csv": "total_points",
    "./2_df_season1_player-successful-raids.csv": "successful_raids",
    "./3_df_season1_player-raid-points.csv": "raid_points",
    "./4_df_season1_player-successful-tackles.csv": "successful_tackles",
    "./5_df_season1_player-tackle-points.csv": "tackle_points",
    "./7_df_season1_player-avg-tackle-points.csv": "avg_tackle_points",
    "./8_df_season1_player-dod-raid-points.csv": "dod_raid_points",
    "./9_df_season1_player-super-raids.csv": "super_raids",
    "./10_df_season1_player-super-tackles.csv": "super_tackles",
    "./11_df_season1_super-10s.csv": "super_10s",
    "./12_df_season1_high-5s.csv": "super_5s",
}

# Load the CSVs again and rename columns based on their corresponding file
renamed_dfs = []

for path, stat_name in file_map.items():
    df = pd.read_csv(path)

    rename_dict = {
        col: (
            f"{stat_name}_{col}"
            if col
            not in ["player_id", "player_name", "team_name", "team_full_name", "value"]
            else col
        )
        for col in df.columns
    }
    renamed_dfs.append(df.rename(columns=rename_dict))

# Merge all dataframes on 'player_id'
merged_df = renamed_dfs[0]
for df in renamed_dfs[1:]:
    merged_df = pd.merge(
        merged_df,
        df,
        on=["player_id", "player_name", "team_name", "team_full_name"],
        how="outer",
    )


# # Merge all dataframes on 'player+id'
# merged_df = dfs[0]
# for df in dfs[1:]:
#     merged_df = pd.merge(
#         merged_df, df, on="player_id", how="outer", suffixes=("", "_duplicate")
#     )

# Removing duplicate columns
merged_df_no_dup = merged_df.loc[:, ~merged_df.columns.duplicated()]

# tools.display_dataframe_to_user(name="Merged Player Statistics", dataframe=merged_df)

In [15]:
merged_df.head()

,player_id,player_name,total_points_match_played,total_points_value,total_points_team_id,total_points_team,team_name,total_points_rank,total_points_position_id,total_points_position_name,...,super_10s_position_name,super_10s_points_per_match,super_5s_match_played,super_5s_value,super_5s_team_id,super_5s_team,super_5s_rank,super_5s_position_id,super_5s_position_name,super_5s_points_per_match
0,4,Ehsan Zamani Fard,8,6,2,NaN,DEL,70,9,Defender,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5,Farhad Kamal Gharibi,2,2,4,NaN,KOL,92,9,Defender,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,9,Takamitsu Kono,1,2,2,NaN,DEL,93,0,All Rounder,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10,Simon Kibura,4,8,7,NaN,PUN,67,8,Raider,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11,Dong Ju Hong,2,1,2,NaN,DEL,94,0,All Rounder,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
len(merged_df.columns)

92

In [17]:
merged_df.to_csv("merged_df_season1.csv")