In [116]:
import pandas as pd
import os
import re


def extract_stat_name(filename):
    # Extract the stat name from the filename
    match = filename.split("_")[4].split(".")[0]

    return match


# print(extract_stat_name("8_df_team_seasons-1_team-successful-raids"))


def merge_csvs(directory):
    # Get all CSV files in the directory
    csv_files = [f for f in os.listdir(directory) if f.endswith(".csv")]

    # Initialize an empty list to store dataframes
    dfs = []

    for file in csv_files:
        # Read each CSV file
        df = pd.read_csv(os.path.join(directory, file))

        # Ensure 'player_id' is in the dataframe
        if "team_id" not in df.columns:
            print(f"Warning: 'team_id' not found in {file}. Skipping this file.")
            continue

        # Extract the stat name from the filename
        stat_name = extract_stat_name(file)

        # Rename columns to avoid conflicts
        for col in df.columns:
            if col != "team_id":
                df.rename(columns={col: f"{stat_name}_{col}"}, inplace=True)

        dfs.append(df)

    # Merge all dataframes
    merged_df = dfs[0]
    for df in dfs[1:]:
        merged_df = pd.merge(merged_df, df, on="team_id", how="outer")

    return merged_df


# Get directory from user
directory = "./season_s-all"

# Merge CSVs
result = merge_csvs(directory)


result.head()
# result.to_csv("test.csv")

,team-total-points-conceded_match_played,team-total-points-conceded_value,team_id,team-total-points-conceded_team_name,team-total-points-conceded_rank,team-total-points-conceded_points_per_match,team-successful-raids_match_played,team-successful-raids_value,team-successful-raids_team_name,team-successful-raids_rank,...,team-total-points_match_played,team-total-points_value,team-total-points_team_name,team-total-points_rank,team-total-points_points_per_match,team-raid-points_match_played,team-raid-points_value,team-raid-points_team_name,team-raid-points_rank,team-raid-points_points_per_match
0,200,6647,1,Bengaluru Bulls,4,33.235000,200,3109,Bengaluru Bulls,2,...,200,6755,Bengaluru Bulls,2,33.775000,200,3916,Bengaluru Bulls,2,19.580000
1,196,6756,2,Dabang Delhi K.C.,3,34.469388,196,3099,Dabang Delhi K.C.,3,...,196,6508,Dabang Delhi K.C.,5,33.204082,196,3841,Dabang Delhi K.C.,3,19.596939
2,195,6156,3,Jaipur Pink Panthers,8,31.569231,195,2917,Jaipur Pink Panthers,5,...,195,6457,Jaipur Pink Panthers,6,33.112821,195,3626,Jaipur Pink Panthers,6,18.594872
3,195,6565,4,Bengal Warriors,5,33.666667,195,2986,Bengal Warriors,4,...,195,6354,Bengal Warriors,7,32.584615,195,3793,Bengal Warriors,4,19.451282
4,197,6270,5,U Mumba,7,31.827411,197,2907,U Mumba,6,...,197,6516,U Mumba,4,33.076142,197,3672,U Mumba,5,18.639594

In [117]:
len(list(result.columns))

71

In [118]:
list(result.columns)

['team-total-points-conceded_match_played',
 'team-total-points-conceded_value',
 'team_id',
 'team-total-points-conceded_team_name',
 'team-total-points-conceded_rank',
 'team-total-points-conceded_points_per_match',
 'team-successful-raids_match_played',
 'team-successful-raids_value',
 'team-successful-raids_team_name',
 'team-successful-raids_rank',
 'team-successful-raids_points_per_match',
 'team-super-raid_match_played',
 'team-super-raid_value',
 'team-super-raid_team_name',
 'team-super-raid_rank',
 'team-super-raid_points_per_match',
 'team-successful-tackles_match_played',
 'team-successful-tackles_value',
 'team-successful-tackles_team_name',
 'team-successful-tackles_rank',
 'team-successful-tackles_points_per_match',
 'team-avg-points-scored_match_played',
 'team-avg-points-scored_value',
 'team-avg-points-scored_team_name',
 'team-avg-points-scored_rank',
 'team-avg-points-scored_points_per_match',
 'team-average-tackle-points_match_played',
 'team-average-tackle-points_value',
 'team-average-tackle-points_team_name',
 'team-average-tackle-points_rank',
 'team-average-tackle-points_points_per_match',
 'team-tackle-points_match_played',
 'team-tackle-points_value',
 'team-tackle-points_team_name',
 'team-tackle-points_rank',
 'team-tackle-points_points_per_match',
 'team-dod-raid-points_match_played',
 'team-dod-raid-points_value',
 'team-dod-raid-points_team_name',
 'team-dod-raid-points_rank',
 'team-dod-raid-points_points_per_match',
 'team-all-outs-conceded_match_played',
 'team-all-outs-conceded_value',
 'team-all-outs-conceded_team_name',
 'team-all-outs-conceded_rank',
 'team-all-outs-conceded_points_per_match',
 'team-super-tackles_match_played',
 'team-super-tackles_value',
 'team-super-tackles_team_name',
 'team-super-tackles_rank',
 'team-super-tackles_points_per_match',
 'team-average-raid-points_match_played',
 'team-average-raid-points_value',
 'team-average-raid-points_team_name',
 'team-average-raid-points_rank',
 'team-average-raid-points_points_per_match',
 'team-all-outs-inflicted_match_played',
 'team-all-outs-inflicted_value',
 'team-all-outs-inflicted_team_name',
 'team-all-outs-inflicted_rank',
 'team-all-outs-inflicted_points_per_match',
 'team-total-points_match_played',
 'team-total-points_value',
 'team-total-points_team_name',
 'team-total-points_rank',
 'team-total-points_points_per_match',
 'team-raid-points_match_played',
 'team-raid-points_value',
 'team-raid-points_team_name',
 'team-raid-points_rank',
 'team-raid-points_points_per_match']

In [119]:
match_played = []
value = []
team_id = []
team_name = []
rank = []
points_per_match = []


for col in result.columns:

    # 'player-total-points_player_name',
    # 'player-total-points_match_played',
    # 'player-total-points_value',
    # 'player-total-points_team_id',
    # 'player-total-points_team',
    # 'player-total-points_team_name',
    # 'player-total-points_rank',
    # 'player-total-points_position_id',
    # 'player-total-points_position_name',
    # 'player-total-points_team_full_name',
    # 'player-total-points_points_per_match',

    # if col.endswith("_player_name"):
    #     player_name.append(col)

    if col.endswith("_match_played"):
        match_played.append(col)

    if col.endswith("_value"):
        value.append(col)

    if col.endswith("_team_id"):
        team_id.append(col)

    # if col.endswith("_team"):
    #     team.append(col)

    if col.endswith("_team_name"):
        team_name.append(col)

    if col.endswith("_rank"):
        rank.append(col)

    # if col.endswith("_position_id"):
    #     position_id.append(col)

    # if col.endswith("_position_name"):
    #     position_name.append(col)

    # if col.endswith("_team_full_name"):
    #     team_full_name.append(col)

    if col.endswith("_per_match"):
        points_per_match.append(col)

In [120]:
cols = [
    # player_name,  #
    match_played,  #####
    value,  ###
    team_id,
    # team,  ####
    team_name,  #####
    rank,  #####
    # position_id,
    # position_name,  ####
    # team_full_name,  ####
    points_per_match,  ####
]
sum_of_cols = 0

for col in cols:
    print(len(col))
    sum_of_cols += len(col)

print(sum_of_cols)
# other_cols

14
14
0
14
14
14
70

In [121]:
l = [
    # player_name
    team_id
    + team_name
    + match_played
    # + position_name
    # + team
    # + team_full_name
    + rank
    + value
    + points_per_match
    # + position_id
]

In [122]:
# print(l)

In [123]:
len(l[0])

70

In [124]:
l[0].append("team_id")

In [125]:
count = 0
for i in l[0]:
    for j in result.columns:
        if i==j:
            print(f"i==j, {i}")
            count+=1
        

print(count)

i==j, team-total-points-conceded_team_name
i==j, team-successful-raids_team_name
i==j, team-super-raid_team_name
i==j, team-successful-tackles_team_name
i==j, team-avg-points-scored_team_name
i==j, team-average-tackle-points_team_name
i==j, team-tackle-points_team_name
i==j, team-dod-raid-points_team_name
i==j, team-all-outs-conceded_team_name
i==j, team-super-tackles_team_name
i==j, team-average-raid-points_team_name
i==j, team-all-outs-inflicted_team_name
i==j, team-total-points_team_name
i==j, team-raid-points_team_name
i==j, team-total-points-conceded_match_played
i==j, team-successful-raids_match_played
i==j, team-super-raid_match_played
i==j, team-successful-tackles_match_played
i==j, team-avg-points-scored_match_played
i==j, team-average-tackle-points_match_played
i==j, team-tackle-points_match_played
i==j, team-dod-raid-points_match_played
i==j, team-all-outs-conceded_match_played
i==j, team-super-tackles_match_played
i==j, team-average-raid-points_match_played
i==j, team-all-outs-inflicted_match_played
i==j, team-total-points_match_played
i==j, team-raid-points_match_played
i==j, team-total-points-conceded_rank
i==j, team-successful-raids_rank
i==j, team-super-raid_rank
i==j, team-successful-tackles_rank
i==j, team-avg-points-scored_rank
i==j, team-average-tackle-points_rank
i==j, team-tackle-points_rank
i==j, team-dod-raid-points_rank
i==j, team-all-outs-conceded_rank
i==j, team-super-tackles_rank
i==j, team-average-raid-points_rank
i==j, team-all-outs-inflicted_rank
i==j, team-total-points_rank
i==j, team-raid-points_rank
i==j, team-total-points-conceded_value
i==j, team-successful-raids_value
i==j, team-super-raid_value
i==j, team-successful-tackles_value
i==j, team-avg-points-scored_value
i==j, team-average-tackle-points_value
i==j, team-tackle-points_value
i==j, team-dod-raid-points_value
i==j, team-all-outs-conceded_value
i==j, team-super-tackles_value
i==j, team-average-raid-points_value
i==j, team-all-outs-inflicted_value
i==j, team-total-points_value
i==j, team-raid-points_value
i==j, team-total-points-conceded_points_per_match
i==j, team-successful-raids_points_per_match
i==j, team-super-raid_points_per_match
i==j, team-successful-tackles_points_per_match
i==j, team-avg-points-scored_points_per_match
i==j, team-average-tackle-points_points_per_match
i==j, team-tackle-points_points_per_match
i==j, team-dod-raid-points_points_per_match
i==j, team-all-outs-conceded_points_per_match
i==j, team-super-tackles_points_per_match
i==j, team-average-raid-points_points_per_match
i==j, team-all-outs-inflicted_points_per_match
i==j, team-total-points_points_per_match
i==j, team-raid-points_points_per_match
i==j, team_id
71

In [126]:
# Display info about the merged dataframe
# print(result.info())


result = result[[l[0][-1]] + l[0][:-1]]

# Save the merged dataframe
output_file = directory + "/" + "merged_player_stats_all.csv"
result.to_csv(output_file, index=False)
print(f"Merged dataframe has been saved to '{output_file}'")

Merged dataframe has been saved to './season_s-all/merged_player_stats_all.csv'

In [115]:
bbb

NameError: name 'bbb' is not defined

## ignore the code below

In [1]:
import os

In [7]:
for i in os.listdir("."):
    if i.endswith(".csv") and "season1" in i:
        print(i)

1_df_season1_player-total-points.csv
11_df_season1_super-10s.csv
8_df_season1_player-dod-raid-points.csv
2_df_season1_player-successful-raids.csv
3_df_season1_player-raid-points.csv
9_df_season1_player-super-raids.csv
4_df_season1_player-successful-tackles.csv
5_df_season1_player-tackle-points.csv
7_df_season1_player-avg-tackle-points.csv
10_df_season1_player-super-tackles.csv
12_df_season1_high-5s.csv

In [14]:
import pandas as pd
import glob

# # Load all CSV files into a list of dataframes
# file_paths = [
#     "./1_df_season1_player-total-points.csv",
#     "./2_df_season1_player-successful-raids.csv",
#     "./3_df_season1_player-raid-points.csv",
#     "./4_df_season1_player-successful-tackles.csv",
#     "./5_df_season1_player-tackle-points.csv",
#     "./7_df_season1_player-avg-tackle-points.csv",
#     "./8_df_season1_player-dod-raid-points.csv",
#     "./9_df_season1_player-super-raids.csv",
#     "./10_df_season1_player-super-tackles.csv",
#     "./11_df_season1_super-10s.csv",
#     "./12_df_season1_high-5s.csv",
# ]

# # Reading all dataframes
# dfs = [pd.read_csv(file) for file in file_paths]

file_map = {
    "./1_df_season1_player-total-points.csv": "total_points",
    "./2_df_season1_player-successful-raids.csv": "successful_raids",
    "./3_df_season1_player-raid-points.csv": "raid_points",
    "./4_df_season1_player-successful-tackles.csv": "successful_tackles",
    "./5_df_season1_player-tackle-points.csv": "tackle_points",
    "./7_df_season1_player-avg-tackle-points.csv": "avg_tackle_points",
    "./8_df_season1_player-dod-raid-points.csv": "dod_raid_points",
    "./9_df_season1_player-super-raids.csv": "super_raids",
    "./10_df_season1_player-super-tackles.csv": "super_tackles",
    "./11_df_season1_super-10s.csv": "super_10s",
    "./12_df_season1_high-5s.csv": "super_5s",
}

# Load the CSVs again and rename columns based on their corresponding file
renamed_dfs = []

for path, stat_name in file_map.items():
    df = pd.read_csv(path)

    rename_dict = {
        col: (
            f"{stat_name}_{col}"
            if col
            not in ["player_id", "player_name", "team_name", "team_full_name", "value"]
            else col
        )
        for col in df.columns
    }
    renamed_dfs.append(df.rename(columns=rename_dict))

# Merge all dataframes on 'player_id'
merged_df = renamed_dfs[0]
for df in renamed_dfs[1:]:
    merged_df = pd.merge(
        merged_df,
        df,
        on=["player_id", "player_name", "team_name", "team_full_name"],
        how="outer",
    )


# # Merge all dataframes on 'player+id'
# merged_df = dfs[0]
# for df in dfs[1:]:
#     merged_df = pd.merge(
#         merged_df, df, on="player_id", how="outer", suffixes=("", "_duplicate")
#     )

# Removing duplicate columns
merged_df_no_dup = merged_df.loc[:, ~merged_df.columns.duplicated()]

# tools.display_dataframe_to_user(name="Merged Player Statistics", dataframe=merged_df)

In [15]:
merged_df.head()

,player_id,player_name,total_points_match_played,total_points_value,total_points_team_id,total_points_team,team_name,total_points_rank,total_points_position_id,total_points_position_name,...,super_10s_position_name,super_10s_points_per_match,super_5s_match_played,super_5s_value,super_5s_team_id,super_5s_team,super_5s_rank,super_5s_position_id,super_5s_position_name,super_5s_points_per_match
0,4,Ehsan Zamani Fard,8,6,2,NaN,DEL,70,9,Defender,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5,Farhad Kamal Gharibi,2,2,4,NaN,KOL,92,9,Defender,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,9,Takamitsu Kono,1,2,2,NaN,DEL,93,0,All Rounder,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,10,Simon Kibura,4,8,7,NaN,PUN,67,8,Raider,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11,Dong Ju Hong,2,1,2,NaN,DEL,94,0,All Rounder,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
len(merged_df.columns)

92

In [17]:
merged_df.to_csv("merged_df_season1.csv")