### Actual Code Starts:

In [20]:
options = webdriver.FirefoxOptions()
options.add_argument("--headless")
driver = webdriver.Firefox(options=options)


#driver.get('https://www.prokabaddi.com/stats/0-102-player-total-points-statistics') ALL-SEASONS
driver.get('https://www.prokabaddi.com/stats/44-102-player-total-points-statistics')

element = driver.find_element(By.CLASS_NAME, 'loadmore')
for i in range(21):
    #element[0].click()
    driver.execute_script("arguments[0].click();", element)
    
soup = BeautifulSoup(driver.page_source)


# for item in soup.find_all("div",class_="sipk-lb-playerName"):
#     print("hello")
#     [elem.extract() for elem in soup.find("div")]
#     f = open("parsed.txt", "a")
#     f.write(item.text)

#     f.close()
# playerDetails = pd.read_csv('parsed.txt',encoding='ISO-8859-1',sep='\t',names=['playerName'])
# print(playerDetails)


for info in soup.find_all("div", class_="info-name"):
    
    first_name_elem = info.find("p", class_="name first-name")
    last_name_elem = info.find("p", class_="name last-name")

    if first_name_elem and last_name_elem:
        first_name = first_name_elem.text.strip()
        last_name = last_name_elem.text.strip()
        full_name = f"{first_name} {last_name}"

        # Write the player's full name to parsed.txt
        with open("parsed.txt", "a") as f:
            f.write(full_name + "\n")


# Load the extracted names into a DataFrame
playerDetails = pd.read_csv('parsed.txt', encoding='ISO-8859-1', names=['playerName'])
if os.path.exists("parsed.txt"):
    os.remove("parsed.txt")

In [21]:
# print(playerDetails)

In [22]:
dfObj=pd.DataFrame(data=[])
dfObj['PlayerName'] = playerDetails[playerDetails.columns[0]]
dfObj

         PlayerName
0        Ashu Malik
1     Arjun Deshwal
2    Pawan Sehrawat
3    Maninder Singh
4         Narender
..              ...
213         Lavish
214  Narender Hooda
215  Ashish Sangwan
216        Navneet
217          Sunil

[218 rows x 1 columns]

In [25]:
soup = BeautifulSoup(driver.page_source)



for item in soup.find_all("div",class_="table-data matches-played"):
    [elem.extract() for elem in soup.find("div")]
    file = open('parsed.txt', "a")
    if item.text == "Matches Played":
        continue
    file.write(item.text)
    file.write("\n")
    #print(item.text)

    file.close()
playerDetails = pd.read_csv('parsed.txt',encoding='ISO-8859-1',sep='\t',names=['MatchesPlayed'])

playerDetails

     MatchesPlayed
0               23
1               23
2               21
3               21
4               21
..             ...
431              1
432              8
433              3
434              3
435              4

[436 rows x 1 columns]

In [6]:
playerDetails

      MatchesPlayed
0    Matches Played
1                23
2                23
3                21
4                21
..              ...
214               1
215               8
216               3
217               3
218               4

[219 rows x 1 columns]

In [27]:
dfObj['MatchesPlayed'] = playerDetails[playerDetails.columns[0]]
dfObj

         PlayerName  MatchesPlayed
0        Ashu Malik             23
1     Arjun Deshwal             23
2    Pawan Sehrawat             21
3    Maninder Singh             21
4         Narender              21
..              ...            ...
213         Lavish               1
214  Narender Hooda              8
215  Ashish Sangwan              3
216        Navneet               3
217          Sunil               4

[218 rows x 2 columns]

In [28]:
if os.path.exists("parsed.txt"):
    os.remove("parsed.txt")

In [31]:
soup = BeautifulSoup(driver.page_source)
for item in soup.find_all("div",class_="table-data rank"):
    [elem.extract() for elem in soup.find("div")]
    file = open('parsed.txt', "a")

    if item.text == "#":
        continue
    file.write(item.text)
    file.write("\n")


    file.close()
playerDetails = pd.read_csv('parsed.txt',encoding='ISO-8859-1',sep='\t',names=['Rank'])



if os.path.exists("parsed.txt"):
    os.remove("parsed.txt")

In [32]:
dfObj['Rank'] = playerDetails[playerDetails.columns[0]]
dfObj

         PlayerName  MatchesPlayed  Rank
0        Ashu Malik             23     1
1     Arjun Deshwal             23     2
2    Pawan Sehrawat             21     3
3    Maninder Singh             21     4
4         Narender              21     5
..              ...            ...   ...
213         Lavish               1   214
214  Narender Hooda              8   215
215  Ashish Sangwan              3   216
216        Navneet               3   217
217          Sunil               4   218

[218 rows x 3 columns]

In [35]:
soup = BeautifulSoup(driver.page_source)
for item in soup.find_all("div",class_="category"):
    [elem.extract() for elem in soup.find("div")]
    file = open('parsed.txt', "a")
    if item.text:
        file.write(item.text)

    else:
        file.write("NA")
    # file.write(item.text)
    file.write("\n")

    file.close()
playerDetails = pd.read_csv('parsed.txt',encoding='ISO-8859-1',sep='\t',names=['PlayerProfile'])

playerDetails

               PlayerProfile
0                     Raider
1                     Raider
2                     Raider
3                     Raider
4                     Raider
..                       ...
213     Defender-Right Cover
214              All Rounder
215              All-Rounder
216                   Raider
217  Defender - Right Corner

[218 rows x 1 columns]

In [36]:
import os
if os.path.exists("parsed.txt"):
    os.remove("parsed.txt")

In [37]:
dfObj['PlayerProfile'] = playerDetails[playerDetails.columns[0]]
dfObj

         PlayerName  MatchesPlayed  Rank            PlayerProfile
0        Ashu Malik             23     1                   Raider
1     Arjun Deshwal             23     2                   Raider
2    Pawan Sehrawat             21     3                   Raider
3    Maninder Singh             21     4                   Raider
4         Narender              21     5                   Raider
..              ...            ...   ...                      ...
213         Lavish               1   214     Defender-Right Cover
214  Narender Hooda              8   215              All Rounder
215  Ashish Sangwan              3   216              All-Rounder
216        Navneet               3   217                   Raider
217          Sunil               4   218  Defender - Right Corner

[218 rows x 4 columns]

In [40]:
soup = BeautifulSoup(driver.page_source)
for item in soup.find_all("div",class_="table-data total-points"):
    [elem.extract() for elem in soup.find("div")]
    file = open('parsed.txt', "a")
    if item.text == "Total Points":
        continue
    else:
        file.write(item.text)
    
    file.write("\n")

    file.close()
playerDetails = pd.read_csv('parsed.txt',encoding='ISO-8859-1',sep='\t',names=['TotalPoints'])
print(playerDetails)

import os
if os.path.exists("parsed.txt"):
    os.remove("parsed.txt")

     TotalPoints
0            280
1            278
2            217
3            198
4            195
..           ...
213            1
214            1
215            1
216            1
217            1

[218 rows x 1 columns]

In [41]:
dfObj['TotalPoints'] = playerDetails[playerDetails.columns[0]]
dfObj

         PlayerName  MatchesPlayed  Rank            PlayerProfile  TotalPoints
0        Ashu Malik             23     1                   Raider          280
1     Arjun Deshwal             23     2                   Raider          278
2    Pawan Sehrawat             21     3                   Raider          217
3    Maninder Singh             21     4                   Raider          198
4         Narender              21     5                   Raider          195
..              ...            ...   ...                      ...          ...
213         Lavish               1   214     Defender-Right Cover            1
214  Narender Hooda              8   215              All Rounder            1
215  Ashish Sangwan              3   216              All-Rounder            1
216        Navneet               3   217                   Raider            1
217          Sunil               4   218  Defender - Right Corner            1

[218 rows x 5 columns]

In [42]:
dfObj.describe()

       MatchesPlayed        Rank  TotalPoints
count     218.000000  218.000000   218.000000
mean       12.013761  109.500000    39.527523
std         7.250285   63.075352    49.344848
min         1.000000    1.000000     1.000000
25%         5.000000   55.250000     6.000000
50%        11.500000  109.500000    20.000000
75%        18.750000  163.750000    54.500000
max        24.000000  218.000000   280.000000

In [51]:
dfObj.to_csv("season10_total-points-statistics.csv")

In [2]:
import pandas as pd
import json
import re

def extract_json_from_script(script_content):
    # Find the JSON data within the script
    start = script_content.find('window.statsWidgetData = ')
    if start == -1:
        return None
    start += len('window.statsWidgetData = ')
    
    # Find the end of the JSON object
    bracket_count = 0
    end = start
    for i, char in enumerate(script_content[start:]):
        if char == '{':
            bracket_count += 1
        elif char == '}':
            bracket_count -= 1
            if bracket_count == 0:
                end = start + i + 1
                break
    
    if bracket_count != 0:
        return None
    
    json_str = script_content[start:end]
    
    # Parse the JSON data
    try:
        return json.loads(json_str)
    except json.JSONDecodeError:
        return None

# Read the content of the file
try:
    with open('../archive/js_script_json.txt', 'r', encoding='utf-8') as file:
        script_content = file.read()
except FileNotFoundError:
    print("Error: The file 'js_script_json.txt' was not found.")
    exit(1)
except IOError:
    print("Error: There was an issue reading the file.")
    exit(1)

# Extract JSON data from the script content
json_data = extract_json_from_script(script_content)

if json_data is None:
    print("Error: Could not extract JSON data from the file.")
    exit(1)




print(json_data)


# Extract the player data
player_data = json_data['stats']['data']

# Create a DataFrame
df = pd.DataFrame(player_data)

# Convert 'value' and 'match_played' to numeric type
df['value'] = pd.to_numeric(df['value'])
df['match_played'] = pd.to_numeric(df['match_played'])

# Calculate successful raids per match
df['raids_per_match'] = df['value'] / df['match_played']

# Display basic information about the DataFrame
print(df.info())

# Display the first few rows
print(df.head())

# Basic statistics
print(df.describe())

# Top 10 players by successful raids
top_10_players = df.sort_values('value', ascending=False).head(10)
print("\nTop 10 players by successful raids:")
print(top_10_players[['player_name', 'value', 'team_name']])

# Top 5 players by raids per match (minimum 10 matches played)
top_raiders = df[df['match_played'] >= 10].sort_values('raids_per_match', ascending=False).head(5)
print("\nTop 5 players by raids per match (minimum 10 matches):")
print(top_raiders[['player_name', 'raids_per_match', 'match_played', 'team_name']])

# Team performance
team_performance = df.groupby('team_name')['value'].sum().sort_values(ascending=False)
print("\nTeam performance (total successful raids):")
print(team_performance)

# Position-wise analysis
position_analysis = df.groupby('position_name')['value'].agg(['sum', 'mean', 'count'])
print("\nPosition-wise analysis:")
print(position_analysis)

# Correlation between matches played and successful raids
correlation = df['match_played'].corr(df['value'])
print(f"\nCorrelation between matches played and successful raids: {correlation:.2f}")


df.to_csv("season10_successful-raids-statistics.csv")

{'meta_info': {'seasons': [{'series_id': 44, 'is_default': True, 'is_linkable': True, 'display_name': 'Season 10', 'redirect_link': 'stats/44-{{STATID}}-{{STATNAME}}-statistics'}, {'series_id': 25, 'is_default': False, 'is_linkable': True, 'display_name': 'Season 9', 'redirect_link': 'stats/25-{{STATID}}-{{STATNAME}}-statistics'}, {'series_id': 20, 'is_default': False, 'is_linkable': True, 'display_name': 'Season 8', 'redirect_link': 'stats/20-{{STATID}}-{{STATNAME}}-statistics'}, {'series_id': 11, 'is_default': False, 'is_linkable': True, 'display_name': 'Season 7', 'redirect_link': 'stats/11-{{STATID}}-{{STATNAME}}-statistics'}, {'series_id': 10, 'is_default': False, 'is_linkable': True, 'display_name': 'Season 6', 'redirect_link': 'stats/10-{{STATID}}-{{STATNAME}}-statistics'}, {'series_id': 8, 'is_default': False, 'is_linkable': True, 'display_name': 'Season 5', 'redirect_link': 'stats/8-{{STATID}}-{{STATNAME}}-statistics'}, {'series_id': 4, 'is_default': False, 'is_linkable': True, 'display_name': 'Season 4', 'redirect_link': 'stats/4-{{STATID}}-{{STATNAME}}-statistics'}, {'series_id': 3, 'is_default': False, 'is_linkable': True, 'display_name': 'Season 3', 'redirect_link': 'stats/3-{{STATID}}-{{STATNAME}}-statistics'}, {'series_id': 2, 'is_default': False, 'is_linkable': True, 'display_name': 'Season 2', 'redirect_link': 'stats/2-{{STATID}}-{{STATNAME}}-statistics'}, {'series_id': 1, 'is_default': False, 'is_linkable': True, 'display_name': 'Season 1', 'redirect_link': 'stats/1-{{STATID}}-{{STATNAME}}-statistics'}, {'series_id': 0, 'is_default': False, 'is_linkable': True, 'display_name': 'All Seasons', 'redirect_link': 'stats/0-{{STATID}}-{{STATNAME}}-statistics'}], 'has_filter': False, 'max_filter_count': 2}, 'isWebView': False, 'stats': {'series_id': 44, 'series_name': 'Pro Kabaddi League Season 10, 2023', 'stat': 'Player Successful Raids', 'stat_id': '21', 'minimum_criteria': 'More than 0 Successful Raids', 'data': [{'player_id': 4947, 'player_name': 'Ashu Malik', 'match_played': 23, 'value': 228, 'team_id': 2, 'team': None, 'team_name': 'DEL', 'rank': '1', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Dabang Delhi K.C.'}, {'player_id': 2024, 'player_name': 'Arjun Deshwal', 'match_played': 23, 'value': 212, 'team_id': 3, 'team': None, 'team_name': 'JAI', 'rank': '2', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Jaipur Pink Panthers'}, {'player_id': 318, 'player_name': 'Pawan Sehrawat', 'match_played': 21, 'value': 156, 'team_id': 8, 'team': None, 'team_name': 'HYD', 'rank': '3', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Telugu Titans'}, {'player_id': 143, 'player_name': 'Maninder Singh', 'match_played': 21, 'value': 153, 'team_id': 4, 'team': None, 'team_name': 'KOL', 'rank': '4', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Bengal Warriors'}, {'player_id': 757, 'player_name': 'Sachin', 'match_played': 22, 'value': 142, 'team_id': 6, 'team': None, 'team_name': 'PAT', 'rank': '5', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Patna Pirates'}, {'player_id': 5093, 'player_name': 'Narender', 'match_played': 21, 'value': 137, 'team_id': 29, 'team': None, 'team_name': 'CHE', 'rank': '6', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Tamil Thalaivas'}, {'player_id': 3032, 'player_name': 'Guman Singh', 'match_played': 18, 'value': 129, 'team_id': 5, 'team': None, 'team_name': 'MUM', 'rank': '7', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'U Mumba'}, {'player_id': 3054, 'player_name': 'Vinay', 'match_played': 23, 'value': 127, 'team_id': 28, 'team': None, 'team_name': 'HAR', 'rank': '8', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Haryana Steelers'}, {'player_id': 5185, 'player_name': 'Nitin Kumar', 'match_played': 20, 'value': 125, 'team_id': 4, 'team': None, 'team_name': 'KOL', 'rank': '9', 'position_id': 0, 'position_name': 'Right Raider', 'team_full_name': 'Bengal Warriors'}, {'player_id': 4960, 'player_name': 'Aslam Mustafa Inamdar', 'match_played': 23, 'value': 119, 'team_id': 7, 'team': None, 'team_name': 'PUN', 'rank': '10', 'position_id': 0, 'position_name': 'All-rounder', 'team_full_name': 'Puneri Paltan'}, {'player_id': 3097, 'player_name': 'Ajinkya Pawar', 'match_played': 21, 'value': 110, 'team_id': 29, 'team': None, 'team_name': 'CHE', 'rank': '11', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Tamil Thalaivas'}, {'player_id': 5252, 'player_name': 'Amirmohammad Zafardanesh', 'match_played': 20, 'value': 106, 'team_id': 5, 'team': None, 'team_name': 'MUM', 'rank': '12', 'position_id': 0, 'position_name': 'All-Rounder', 'team_full_name': 'U Mumba'}, {'player_id': 4022, 'player_name': 'Mohit Goyat', 'match_played': 22, 'value': 103, 'team_id': 7, 'team': None, 'team_name': 'PUN', 'rank': '13', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Puneri Paltan'}, {'player_id': 197, 'player_name': 'Pardeep Narwal', 'match_played': 17, 'value': 99, 'team_id': 30, 'team': None, 'team_name': 'U.P.', 'rank': '14', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'U.P. Yoddhas'}, {'player_id': 5124, 'player_name': 'Parteek Dahiya', 'match_played': 20, 'value': 93, 'team_id': 31, 'team': None, 'team_name': 'GUJ', 'rank': '15', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Gujarat Giants'}, {'player_id': 4108, 'player_name': 'Shivam Patare', 'match_played': 23, 'value': 90, 'team_id': 28, 'team': None, 'team_name': 'HAR', 'rank': '16', 'position_id': 0, 'position_name': 'Left Raider', 'team_full_name': 'Haryana Steelers'}, {'player_id': 3966, 'player_name': 'Rakesh', 'match_played': 21, 'value': 88, 'team_id': 31, 'team': None, 'team_name': 'GUJ', 'rank': '17', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Gujarat Giants'}, {'player_id': 763, 'player_name': 'Manjeet', 'match_played': 22, 'value': 85, 'team_id': 6, 'team': None, 'team_name': 'PAT', 'rank': '18', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Patna Pirates'}, {'player_id': 4193, 'player_name': 'Sudhakar M ', 'match_played': 19, 'value': 82, 'team_id': 6, 'team': None, 'team_name': 'PAT', 'rank': '19', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Patna Pirates'}, {'player_id': 4944, 'player_name': 'Bharat', 'match_played': 18, 'value': 81, 'team_id': 1, 'team': None, 'team_name': 'BLR', 'rank': '20', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Bengaluru Bulls'}, {'player_id': 3233, 'player_name': 'Pankaj Mohite', 'match_played': 22, 'value': 74, 'team_id': 7, 'team': None, 'team_name': 'PUN', 'rank': '21', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Puneri Paltan'}, {'player_id': 5163, 'player_name': 'Gagana Gowda', 'match_played': 13, 'value': 70, 'team_id': 30, 'team': None, 'team_name': 'U.P.', 'rank': '22', 'position_id': 0, 'position_name': 'Right Raider', 'team_full_name': 'U.P. Yoddhas'}, {'player_id': 4179, 'player_name': 'Sushil', 'match_played': 16, 'value': 68, 'team_id': 1, 'team': None, 'team_name': 'BLR', 'rank': '23', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Bengaluru Bulls'}, {'player_id': 3241, 'player_name': 'Surender Gill', 'match_played': 10, 'value': 65, 'team_id': 30, 'team': None, 'team_name': 'U.P.', 'rank': '24', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'U.P. Yoddhas'}, {'player_id': 3053, 'player_name': 'V Ajith Kumar', 'match_played': 19, 'value': 64, 'team_id': 3, 'team': None, 'team_name': 'JAI', 'rank': '25', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Jaipur Pink Panthers'}, {'player_id': 3128, 'player_name': 'Sonu', 'match_played': 18, 'value': 63, 'team_id': 31, 'team': None, 'team_name': 'GUJ', 'rank': '26', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Gujarat Giants'}, {'player_id': 5282, 'player_name': 'Sandeep Kumar ', 'match_played': 20, 'value': 63, 'team_id': 6, 'team': None, 'team_name': 'PAT', 'rank': '27', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Patna Pirates'}, {'player_id': 2026, 'player_name': 'Siddharth Desai', 'match_played': 17, 'value': 59, 'team_id': 28, 'team': None, 'team_name': 'HAR', 'rank': '28', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Haryana Steelers'}, {'player_id': 2296, 'player_name': 'Naveen Kumar', 'match_played': 6, 'value': 55, 'team_id': 2, 'team': None, 'team_name': 'DEL', 'rank': '29', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Dabang Delhi K.C.'}, {'player_id': 106, 'player_name': 'Shrikant Jadhav', 'match_played': 15, 'value': 55, 'team_id': 4, 'team': None, 'team_name': 'KOL', 'rank': '30', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Bengal Warriors'}, {'player_id': 366, 'player_name': 'Vikash Kandola', 'match_played': 19, 'value': 55, 'team_id': 1, 'team': None, 'team_name': 'BLR', 'rank': '31', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Bengaluru Bulls'}, {'player_id': 660, 'player_name': 'Bhavani Rajput', 'match_played': 20, 'value': 49, 'team_id': 3, 'team': None, 'team_name': 'JAI', 'rank': '32', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Jaipur Pink Panthers'}, {'player_id': 4183, 'player_name': 'Meetu Sharma', 'match_played': 22, 'value': 44, 'team_id': 2, 'team': None, 'team_name': 'DEL', 'rank': '33', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Dabang Delhi K.C.'}, {'player_id': 3965, 'player_name': 'Manjeet', 'match_played': 20, 'value': 44, 'team_id': 2, 'team': None, 'team_name': 'DEL', 'rank': '34', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Dabang Delhi K.C.'}, {'player_id': 5138, 'player_name': 'Akshit ', 'match_played': 10, 'value': 44, 'team_id': 1, 'team': None, 'team_name': 'BLR', 'rank': '35', 'position_id': 0, 'position_name': 'Left Raider', 'team_full_name': 'Bengaluru Bulls'}, {'player_id': 4959, 'player_name': 'Akash Shinde', 'match_played': 13, 'value': 43, 'team_id': 7, 'team': None, 'team_name': 'PUN', 'rank': '36', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Puneri Paltan'}, {'player_id': 5197, 'player_name': 'Robin Chaudhary', 'match_played': 18, 'value': 40, 'team_id': 8, 'team': None, 'team_name': 'HYD', 'rank': '37', 'position_id': 0, 'position_name': 'Right Raider', 'team_full_name': 'Telugu Titans'}, {'player_id': 3023, 'player_name': 'Rohit Gulia', 'match_played': 16, 'value': 40, 'team_id': 31, 'team': None, 'team_name': 'GUJ', 'rank': '38', 'position_id': 0, 'position_name': 'All-Rounder', 'team_full_name': 'Gujarat Giants'}, {'player_id': 5157, 'player_name': 'Prafull Zaware', 'match_played': 19, 'value': 35, 'team_id': 8, 'team': None, 'team_name': 'HYD', 'rank': '39', 'position_id': 0, 'position_name': 'Left Raider', 'team_full_name': 'Telugu Titans'}, {'player_id': 3081, 'player_name': 'Vijay Malik', 'match_played': 14, 'value': 30, 'team_id': 30, 'team': None, 'team_name': 'U.P.', 'rank': '40', 'position_id': 0, 'position_name': 'All-Rounder', 'team_full_name': 'U.P. Yoddhas'}, {'player_id': 5046, 'player_name': 'Visvanth V', 'match_played': 18, 'value': 29, 'team_id': 5, 'team': None, 'team_name': 'MUM', 'rank': '41', 'position_id': 0, 'position_name': 'All- Rounder', 'team_full_name': 'U Mumba'}, {'player_id': 5153, 'player_name': 'Vishal Chahal ', 'match_played': 10, 'value': 28, 'team_id': 29, 'team': None, 'team_name': 'CHE', 'rank': '42', 'position_id': 0, 'position_name': 'Right Raider', 'team_full_name': 'Tamil Thalaivas'}, {'player_id': 4757, 'player_name': 'Vishwas S', 'match_played': 16, 'value': 28, 'team_id': 4, 'team': None, 'team_name': 'KOL', 'rank': '43', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Bengal Warriors'}, {'player_id': 4191, 'player_name': 'Sanjeevi S ', 'match_played': 17, 'value': 28, 'team_id': 8, 'team': None, 'team_name': 'HYD', 'rank': '44', 'position_id': 0, 'position_name': 'All- Rounder', 'team_full_name': 'Telugu Titans'}, {'player_id': 5002, 'player_name': 'Jai Bhagwan', 'match_played': 13, 'value': 27, 'team_id': 5, 'team': None, 'team_name': 'MUM', 'rank': '45', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'U Mumba'}, {'player_id': 5118, 'player_name': 'Mahipal', 'match_played': 7, 'value': 25, 'team_id': 30, 'team': None, 'team_name': 'U.P.', 'rank': '46', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'U.P. Yoddhas'}, {'player_id': 36, 'player_name': 'Chandran Ranjit', 'match_played': 4, 'value': 24, 'team_id': 28, 'team': None, 'team_name': 'HAR', 'rank': '47', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Haryana Steelers'}, {'player_id': 5121, 'player_name': 'Anil Kumar', 'match_played': 14, 'value': 23, 'team_id': 30, 'team': None, 'team_name': 'U.P.', 'rank': '48', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'U.P. Yoddhas'}, {'player_id': 4925, 'player_name': 'Mohammadreza Chiyaneh', 'match_played': 24, 'value': 21, 'team_id': 7, 'team': None, 'team_name': 'PUN', 'rank': '49', 'position_id': 0, 'position_name': 'All-Rounder', 'team_full_name': 'Puneri Paltan'}, {'player_id': 3970, 'player_name': 'Himanshu Narwal', 'match_played': 6, 'value': 19, 'team_id': 29, 'team': None, 'team_name': 'CHE', 'rank': '50', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Tamil Thalaivas'}, {'player_id': 2290, 'player_name': 'Rajnish', 'match_played': 7, 'value': 19, 'team_id': 8, 'team': None, 'team_name': 'HYD', 'rank': '51', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Telugu Titans'}, {'player_id': 3038, 'player_name': 'Neeraj Narwal', 'match_played': 12, 'value': 19, 'team_id': 1, 'team': None, 'team_name': 'BLR', 'rank': '52', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Bengaluru Bulls'}, {'player_id': 5117, 'player_name': 'Pranay Rane', 'match_played': 12, 'value': 19, 'team_id': 5, 'team': None, 'team_name': 'MUM', 'rank': '53', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'U Mumba'}, {'player_id': 5155, 'player_name': 'Nitin Singh', 'match_played': 9, 'value': 18, 'team_id': 29, 'team': None, 'team_name': 'CHE', 'rank': '54', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Tamil Thalaivas'}, {'player_id': 5146, 'player_name': 'Vishal Tate', 'match_played': 3, 'value': 17, 'team_id': 28, 'team': None, 'team_name': 'HAR', 'rank': '55', 'position_id': 0, 'position_name': 'Right Raider', 'team_full_name': 'Haryana Steelers'}, {'player_id': 3154, 'player_name': 'Sachin Narwal', 'match_played': 4, 'value': 17, 'team_id': 1, 'team': None, 'team_name': 'BLR', 'rank': '56', 'position_id': 0, 'position_name': 'All-Rounder', 'team_full_name': 'Bengaluru Bulls'}, {'player_id': 219, 'player_name': 'K. Prapanjan', 'match_played': 12, 'value': 16, 'team_id': 28, 'team': None, 'team_name': 'HAR', 'rank': '57', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Haryana Steelers'}, {'player_id': 3028, 'player_name': 'Ashish', 'match_played': 18, 'value': 14, 'team_id': 28, 'team': None, 'team_name': 'HAR', 'rank': '58', 'position_id': 0, 'position_name': 'All-Rounder', 'team_full_name': 'Haryana Steelers'}, {'player_id': 5116, 'player_name': 'Aditya Shinde', 'match_played': 12, 'value': 14, 'team_id': 7, 'team': None, 'team_name': 'PUN', 'rank': '59', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Puneri Paltan'}, {'player_id': 5251, 'player_name': 'Alireza Mirzaeian', 'match_played': 9, 'value': 14, 'team_id': 5, 'team': None, 'team_name': 'MUM', 'rank': '60', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'U Mumba'}, {'player_id': 5145, 'player_name': 'Nitin ', 'match_played': 9, 'value': 13, 'team_id': 31, 'team': None, 'team_name': 'GUJ', 'rank': '61', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Gujarat Giants'}, {'player_id': 5018, 'player_name': 'Heidarali Ekrami', 'match_played': 10, 'value': 13, 'team_id': 5, 'team': None, 'team_name': 'MUM', 'rank': '62', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'U Mumba'}, {'player_id': 4970, 'player_name': 'Shivam', 'match_played': 5, 'value': 13, 'team_id': 5, 'team': None, 'team_name': 'MUM', 'rank': '63', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'U Mumba'}, {'player_id': 4106, 'player_name': 'Tejas Patil', 'match_played': 5, 'value': 13, 'team_id': 28, 'team': None, 'team_name': 'HAR', 'rank': '64', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Haryana Steelers'}, {'player_id': 5094, 'player_name': 'Jatin', 'match_played': 6, 'value': 12, 'team_id': 29, 'team': None, 'team_name': 'CHE', 'rank': '65', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Tamil Thalaivas'}, {'player_id': 3161, 'player_name': 'Himanshu', 'match_played': 16, 'value': 11, 'team_id': 29, 'team': None, 'team_name': 'CHE', 'rank': '66', 'position_id': 0, 'position_name': 'Defender - Left Corner', 'team_full_name': 'Tamil Thalaivas'}, {'player_id': 5148, 'player_name': 'Abhijeet Malik', 'match_played': 5, 'value': 10, 'team_id': 3, 'team': None, 'team_name': 'JAI', 'rank': '67', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Jaipur Pink Panthers'}, {'player_id': 4961, 'player_name': 'Shubham Shelke', 'match_played': 5, 'value': 9, 'team_id': 3, 'team': None, 'team_name': 'JAI', 'rank': '68', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Jaipur Pink Panthers'}, {'player_id': 4963, 'player_name': 'Himanshu Singh', 'match_played': 7, 'value': 9, 'team_id': 29, 'team': None, 'team_name': 'CHE', 'rank': '69', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Tamil Thalaivas'}, {'player_id': 5225, 'player_name': 'Ghanshyam Magar', 'match_played': 5, 'value': 9, 'team_id': 28, 'team': None, 'team_name': 'HAR', 'rank': '70', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Haryana Steelers'}, {'player_id': 5158, 'player_name': 'Omkar Patil', 'match_played': 10, 'value': 9, 'team_id': 8, 'team': None, 'team_name': 'HYD', 'rank': '71', 'position_id': 0, 'position_name': 'Right Raider', 'team_full_name': 'Telugu Titans'}, {'player_id': 3176, 'player_name': 'Mohammad Nabibakhsh', 'match_played': 21, 'value': 8, 'team_id': 31, 'team': None, 'team_name': 'GUJ', 'rank': '72', 'position_id': 0, 'position_name': 'All-Rounder', 'team_full_name': 'Gujarat Giants'}, {'player_id': 3082, 'player_name': 'Monu', 'match_played': 13, 'value': 7, 'team_id': 1, 'team': None, 'team_name': 'BLR', 'rank': '73', 'position_id': 8, 'position_name': 'Raider', 'team_full_name': 'Bengaluru Bulls'}, {'player_id': 5180, 'player_name': 'Masanamuthu Lakshnanan', 'match_played': 4, 'value': 7, 'team_id': 29, 'team': None, 'team_name': 'CHE', 'rank': '74', 'position_id': 0, 'position_name': 'Right Raider', 'team_full_name': 'Tamil Thalaivas'}, {'player_id': 5200, 'player_name': 'Rohit Yadav', 'match_played': 5, 'value': 7, 'team_id': 5, 'team': None, 'team_name': 'MUM', 'rank': '75', 'position_id': 0, 'position_name': 'Left Raider', 'team_full_name': 'U Mumba'}, {'player_id': 5164, 'player_name': 'Shivam Chaudhary', 'match_played': 8, 'value': 6, 'team_id': 30, 'team': None, 'team_name': 'U.P.', 'rank': '76', 'position_id': 0, 'position_name': 'Left Raider', 'team_full_name': 'U.P. Yoddhas'}, {'player_id': 5039, 'player_name': 'Shankar Gadai', 'match_played': 15, 'value': 6, 'team_id': 8, 'team': None, 'team_name': 'HYD', 'rank': '77', 'position_id': 0, 'position_name': 'All-Rounder', 'team_full_name': 'Telugu Titans'}, {'player_id': 3090, 'player_name': 'Rakshith ', 'match_played': 4, 'value': 6, 'team_id': 1, 'team': None, 'team_name': 'BLR', 'rank': '78', 'position_id': 0, 'position_name': 'Defender-Right Cover', 'team_full_name': 'Bengaluru Bulls'}, {'player_id': 4723, 'player_name': 'Rohit', 'match_played': 5, 'value': 6, 'team_id': 6, 'team': None, 'team_name': 'PAT', 'rank': '79'

In [70]:
import pandas as pd
import json
import re
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.firefox.options import Options
from bs4 import BeautifulSoup
import time

def extract_json_from_script(script_content):
    # Find the JSON data within the script
    start = script_content.find('window.statsWidgetData = ')
    if start == -1:
        return None
    start += len('window.statsWidgetData = ')
    
    # Find the end of the JSON object
    bracket_count = 0
    end = start
    for i, char in enumerate(script_content[start:]):
        if char == '{':
            bracket_count += 1
        elif char == '}':
            bracket_count -= 1
            if bracket_count == 0:
                end = start + i + 1
                break
    
    if bracket_count != 0:
        return None
    
    json_str = script_content[start:end]
    
    # Parse the JSON data
    try:
        return json.loads(json_str)
    except json.JSONDecodeError:
        return None

def fetch_and_process_data(url):
    options = webdriver.FirefoxOptions()
    options.add_argument("--headless")
    driver = webdriver.Firefox(options=options)
    
    try:
        driver.get(url)

        
        
        # # Click the 'loadmore' button multiple times
        # for i in range(21):
        #     try:
        #         element = WebDriverWait(driver, 10).until(
        #             EC.presence_of_element_located((By.CLASS_NAME, 'loadmore'))
        #         )
        #         driver.execute_script("arguments[0].click();", element)
        #         time.sleep(1)  # Wait for content to load
        #     except:
        #         print(f"Stopped after {i} clicks")
        #         break
        
        # Extract the script content
        soup = BeautifulSoup(driver.page_source)
        # print(soup)
        script_tag = soup.find('script', string=lambda text: text and 'window.statsWidgetData' in text)

        # print(script_tag)

        # script_content = script_tag

        # json_data = extract_json_from_script(script_content)

        

        
        if script_tag:
            json_data = extract_json_from_script(script_tag.string)
            if json_data:
                player_data = json_data['stats']['data']
                df = pd.DataFrame(player_data)
                
                # Convert 'value' and 'match_played' to numeric type
                df['value'] = pd.to_numeric(df['value'])
                df['match_played'] = pd.to_numeric(df['match_played'])
                
                # Calculate points per match
                df['points_per_match'] = df['value'] / df['match_played']
                
                return df
    
    finally:
        driver.quit()
    
    return None

# URL of the webpage
url = "https://www.prokabaddi.com/stats/44-22-raid-points-statistics"

# Fetch and process data
df = fetch_and_process_data(url)

if df is not None:
    # Display basic information about the DataFrame
    print(df.info())

    # Display the first few rows
    print(df.head())

    # Basic statistics
    print(df.describe())

    # Top 10 players by total points
    top_10_players = df.sort_values('value', ascending=False).head(10)
    print("\nTop 10 players by total points:")
    print(top_10_players[['player_name', 'value', 'team_name']])

    # Top 5 players by points per match (minimum 10 matches played)
    top_players = df[df['match_played'] >= 10].sort_values('points_per_match', ascending=False).head(5)
    print("\nTop 5 players by points per match (minimum 10 matches):")
    print(top_players[['player_name', 'points_per_match', 'match_played', 'team_name']])

    # Team performance
    team_performance = df.groupby('team_name')['value'].sum().sort_values(ascending=False)
    print("\nTeam performance (total points):")
    print(team_performance)

    # Position-wise analysis
    position_analysis = df.groupby('position_name')['value'].agg(['sum', 'mean', 'count'])
    print("\nPosition-wise analysis:")
    print(position_analysis)

    # Correlation between matches played and total points
    correlation = df['match_played'].corr(df['value'])
    print(f"\nCorrelation between matches played and total points: {correlation:.2f}")
else:
    print("Failed to fetch or process data from the webpage.")

df.to_csv("season10_raid-points-statistics.csv")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 142 entries, 0 to 141
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         142 non-null    int64
 1   player_name       142 non-null    object
 2   match_played      142 non-null    int64
 3   value             142 non-null    int64
 4   team_id           142 non-null    int64
 5   team              0 non-null      object
 6   team_name         142 non-null    object
 7   rank              142 non-null    object
 8   position_id       142 non-null    int64
 9   position_name     142 non-null    object
 10  team_full_name    142 non-null    object
 11  points_per_match  142 non-null    float64
dtypes: float64(1), int64(5), object(6)
memory usage: 13.4+ KB
None
   player_id     player_name  match_played  value  team_id  team team_name  \
0       4947      Ashu Malik            23    276        2  None       DEL
1       2024   Arjun Deshwal            23    276        3  None       JAI
2        318  Pawan Sehrawat            21    202        8  None       HYD
3        143  Maninder Singh            21    197        4  None       KOL
4       5093        Narender            21    186       29  None       CHE

  rank  position_id position_name        team_full_name  points_per_match
0    1            8        Raider     Dabang Delhi K.C.         12.000000
1    2            8        Raider  Jaipur Pink Panthers         12.000000
2    3            8        Raider         Telugu Titans          9.619048
3    4            8        Raider       Bengal Warriors          9.380952
4    5            8        Raider       Tamil Thalaivas          8.857143
         player_id  match_played       value     team_id  position_id  \
count   142.000000    142.000000  142.000000  142.000000   142.000000
mean   3855.246479     12.795775   38.711268   13.774648     4.401408
std    1631.415429      7.432475   56.569744   12.303718     4.065178
min      36.000000      1.000000    1.000000    1.000000     0.000000
25%    3088.500000      5.000000    3.000000    4.000000     0.000000
50%    4879.500000     14.000000   11.000000    7.000000     8.000000
75%    5121.750000     19.750000   55.000000   29.000000     8.000000
max    5324.000000     24.000000  276.000000   31.000000     9.000000

       points_per_match
count        142.000000
mean           2.705707
std            2.856081
min            0.043478
25%            0.308333
50%            1.894444
75%            4.277632
max           12.000000

Top 10 players by total points:
             player_name  value team_name
0             Ashu Malik    276       DEL
1          Arjun Deshwal    276       JAI
2         Pawan Sehrawat    202       HYD
3         Maninder Singh    197       KOL
4               Narender    186       CHE
5                 Sachin    171       PAT
6            Nitin Kumar    169       KOL
7                  Vinay    163       HAR
8            Guman Singh    163       MUM
9  Aslam Mustafa Inamdar    142       PUN

Top 5 players by points per match (minimum 10 matches):
      player_name  points_per_match  match_played team_name
0      Ashu Malik         12.000000            23       DEL
1   Arjun Deshwal         12.000000            23       JAI
2  Pawan Sehrawat          9.619048            21       HYD
3  Maninder Singh          9.380952            21       KOL
8     Guman Singh          9.055556            18       MUM

Team performance (total points):
team_name
KOL     504
PAT     495
HAR     492
MUM     486
DEL     474
JAI     464
PUN     464
CHE     443
U.P.    434
GUJ     422
HYD     413
BLR     406
Name: value, dtype: int64

Position-wise analysis:
                          sum        mean  count
position_name
                            1    1.000000      1
All- Rounder               88   22.000000      4
All-Rounder               345   21.562500     16
All-rounder               142  142.000000      1
Defender                   21    2.333333      9
Defender - Left Corner     34    5.666667      6
Defender - Left Cover      13    2.166667      6
Defender - Right Corner    18    3.000000      6
Defender - Right Cover     19    2.714286      7
Defender-Right Corner       1    1.000000      1
Defender-Right Cover        8    8.000000      1
Left Raider               253   31.625000      8
Raider                   4147   60.985294     68
Right Raider              407   50.875000      8

Correlation between matches played and total points: 0.49

# this is the main script, run this!!!!!, everything else was building up to this!

In [5]:
import pandas as pd
import json
import re
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.firefox.options import Options
from bs4 import BeautifulSoup
import time


import requests
import csv
from bs4 import BeautifulSoup
from selenium  import webdriver
import pandas as pd
import numpy as np
from selenium.webdriver.common.by import By
import os


d={"s-10": "44", 
   "s-9": "25", 
   "s-8": "20",
   "s-7": "11",
   "s-6": "10",
   "s-5": "8",
   "s-4": "4",
   "s-3": "3",
   "s-2": "2",
   "s-1": "1",
   "s-all":"0" ,
   
   }


def extract_json_from_script(script_content):
    start = script_content.find('window.statsWidgetData = ')
    if start == -1:
        return None
    start += len('window.statsWidgetData = ')
    
    bracket_count = 0
    end = start
    for i, char in enumerate(script_content[start:]):
        if char == '{':
            bracket_count += 1
        elif char == '}':
            bracket_count -= 1
            if bracket_count == 0:
                end = start + i + 1
                break
    
    if bracket_count != 0:
        return None
    
    json_str = script_content[start:end]
    
    try:
        return json.loads(json_str)
    except json.JSONDecodeError:
        return None

def fetch_and_process_data(url):
    options = webdriver.FirefoxOptions()
    options.add_argument("--headless")
    driver = webdriver.Firefox(options=options)
    
    try:
        driver.get(url)
        
        for i in range(21):
            try:
                element = WebDriverWait(driver, 10).until(
                    EC.presence_of_element_located((By.CLASS_NAME, 'loadmore'))
                )
                driver.execute_script("arguments[0].click();", element)
                time.sleep(1)
            except:
                print(f"Stopped after {i} clicks")
                break
        
        soup = BeautifulSoup(driver.page_source, 'html.parser')
        script_tag = soup.find('script', string=lambda text: text and 'window.statsWidgetData' in text)
        
        if script_tag:
            json_data = extract_json_from_script(script_tag.string)
            if json_data:
                player_data = json_data['stats']['data']
                df = pd.DataFrame(player_data)
                
                df['value'] = pd.to_numeric(df['value'])
                df['match_played'] = pd.to_numeric(df['match_played'])
                
                df['points_per_match'] = df['value'] / df['match_played']
                
                return df, json_data['stats']['stat']
    
    finally:
        driver.quit()
    
    return None, None

urls = [
    f"https://www.prokabaddi.com/stats/{d['s-7']}-102-total-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-7']}-21-successful-raids-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-7']}-22-raid-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-7']}-23-successful-tackles-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-7']}-103-tackle-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-7']}-22-avg-raid-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-7']}-139-avg-tackle-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-7']}-132-do-or-die-raid-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-7']}-104-super-raids-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-7']}-28-super-tackles-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-7']}-100-super-10s-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-7']}-101-high-5s-statistics"
]   

x = 0
for url in urls:
    x+=1
    df, stat_name = fetch_and_process_data(url)
    if df is not None:
        # Create a file name based on the statistic
        file_name = f"{x}_df_season7_{stat_name.lower().replace(' ', '-')}.csv"
        
        # Export the DataFrame to CSV
        df.to_csv(file_name, index=False)
        print(f"Exported {file_name}")
        
        # Display basic information about the DataFrame
        print(f"\nStatistic: {stat_name}")
        print(df.info())
        
        # Display the first few rows
        print(df.head())
        
        # Basic statistics
        print(df.describe())
        
        # Top 10 players by the statistic
        top_10_players = df.sort_values('value', ascending=False).head(10)
        print(f"\nTop 10 players by {stat_name}:")
        print(top_10_players[['player_name', 'value', 'team_name']])
        
        # Team performance
        team_performance = df.groupby('team_name')['value'].sum().sort_values(ascending=False)
        print(f"\nTeam performance (total {stat_name}):")
        print(team_performance)
        
        # Position-wise analysis
        position_analysis = df.groupby('position_name')['value'].agg(['sum', 'mean', 'count'])
        print("\nPosition-wise analysis:")
        print(position_analysis)
        
        # Correlation between matches played and the statistic
        correlation = df['match_played'].corr(df['value'])
        print(f"\nCorrelation between matches played and {stat_name}: {correlation:.2f}")
        
        print("\n" + "="*50 + "\n")
    else:
        print(f"Failed to fetch or process data from {url}")

Stopped after 18 clicks
Exported 1_df_season7_player-total-points.csv

Statistic: Player Total Points
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         186 non-null    int64
 1   player_name       186 non-null    object
 2   match_played      186 non-null    int64
 3   value             186 non-null    int64
 4   team_id           186 non-null    int64
 5   team              0 non-null      object
 6   team_name         186 non-null    object
 7   rank              186 non-null    object
 8   position_id       186 non-null    int64
 9   position_name     186 non-null    object
 10  team_full_name    186 non-null    object
 11  points_per_match  186 non-null    float64
dtypes: float64(1), int64(5), object(6)
memory usage: 17.6+ KB
None
   player_id      player_name  match_played  value  team_id  team team_name  \
0        318      Pawan Kumar            24    360        1  None       BLR
1        197   Pardeep Narwal            22    304        6  None       PAT
2       2296     Naveen Kumar            23    303        2  None       DEL
3       2026  Siddharth Desai            22    220        8  None       HYD
4        143   Maninder Singh            20    205        4  None       KOL

  rank  position_id position_name     team_full_name  points_per_match
0    1            8        raider    Bengaluru Bulls         15.000000
1    2            8        Raider      Patna Pirates         13.818182
2    3            8        Raider  Dabang Delhi K.C.         13.173913
3    4            8        Raider      Telugu Titans         10.000000
4    5            8        raider    Bengal Warriors         10.250000
         player_id  match_played       value     team_id  position_id  \
count   186.000000    186.000000  186.000000  186.000000   186.000000
mean   1794.166667     13.139785   43.607527   12.887097     6.010753
std    1349.829130      7.314689   55.742960   11.945061     3.927711
min      12.000000      1.000000    1.000000    1.000000     0.000000
25%     294.500000      6.000000    7.250000    4.000000     0.000000
50%    2302.000000     14.000000   21.000000    7.000000     8.000000
75%    3099.750000     20.000000   61.000000   28.750000     9.000000
max    3241.000000     24.000000  360.000000   31.000000     9.000000

       points_per_match
count        186.000000
mean           2.700468
std            2.418292
min            0.333333
25%            1.000000
50%            2.000000
75%            3.333333
max           15.000000

Top 10 players by Player Total Points:
       player_name  value team_name
0      Pawan Kumar    360       BLR
1   Pardeep Narwal    304       PAT
2     Naveen Kumar    303       DEL
3  Siddharth Desai    220       HYD
4   Maninder Singh    205       KOL
5  Vikash Khandola    195       HAR
6   Abhishek Singh    163       MUM
7     Deepak Hooda    158       JAI
8  Shrikant Jadhav    152      U.P.
9         Manjeet     151       PUN

Team performance (total Player Total Points):
team_name
BLR     765
DEL     754
KOL     742
HAR     715
PUN     673
PAT     672
MUM     671
U.P.    668
HYD     660
JAI     625
GUJ     596
CHE     570
Name: value, dtype: int64

Position-wise analysis:
                          sum        mean  count
position_name
                          155    8.157895     19
All Rounder              1055   34.032258     31
Defender                 1808   28.698413     63
Defender - Left Corner      6    6.000000      1
Defender - Left Cover       4    4.000000      1
Defender - Right Corner   122   61.000000      2
Defender - Right corner    18   18.000000      1
Raider                   3110   64.791667     48
defender                  307   43.857143      7
raider                   1526  117.384615     13

Correlation between matches played and Player Total Points: 0.64

==================================================

Stopped after 11 clicks
Exported 2_df_season7_player-successful-raids.csv

Statistic: Player Successful Raids
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119 entries, 0 to 118
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         119 non-null    int64
 1   player_name       119 non-null    object
 2   match_played      119 non-null    int64
 3   value             119 non-null    int64
 4   team_id           119 non-null    int64
 5   team              0 non-null      object
 6   team_name         119 non-null    object
 7   rank              119 non-null    object
 8   position_id       119 non-null    int64
 9   position_name     119 non-null    object
 10  team_full_name    119 non-null    object
 11  points_per_match  119 non-null    float64
dtypes: float64(1), int64(5), object(6)
memory usage: 11.3+ KB
None
   player_id      player_name  match_played  value  team_id  team team_name  \
0        318      Pawan Kumar            24    262        1  None       BLR
1       2296     Naveen Kumar            23    251        2  None       DEL
2        197   Pardeep Narwal            22    234        6  None       PAT
3       2026  Siddharth Desai            22    177        8  None       HYD
4        143   Maninder Singh            20    171        4  None       KOL

  rank  position_id position_name     team_full_name  points_per_match
0    1            8        raider    Bengaluru Bulls         10.916667
1    2            8        Raider  Dabang Delhi K.C.         10.913043
2    3            8        Raider      Patna Pirates         10.636364
3    4            8        Raider      Telugu Titans          8.045455
4    5            8        raider    Bengal Warriors          8.550000
         player_id  match_played       value     team_id  position_id  \
count   119.000000    119.000000  119.000000  119.000000   119.000000
mean   1707.403361     13.361345   34.806723   13.478992     5.613445
std    1341.590034      7.376935   52.063240   12.035152     3.877596
min      12.000000      1.000000    1.000000    1.000000     0.000000
25%     267.500000      6.000000    3.000000    4.000000     0.000000
50%    2282.000000     15.000000    9.000000    7.000000     8.000000
75%    3081.500000     20.000000   48.500000   29.000000     8.000000
max    3241.000000     24.000000  262.000000   31.000000     9.000000

       points_per_match
count        119.000000
mean           2.161218
std            2.321233
min            0.041667
25%            0.414286
50%            1.437500
75%            3.160256
max           10.916667

Top 10 players by Player Successful Raids:
       player_name  value team_name
0      Pawan Kumar    262       BLR
1     Naveen Kumar    251       DEL
2   Pardeep Narwal    234       PAT
3  Siddharth Desai    177       HYD
4   Maninder Singh    171       KOL
5  Vikash Khandola    146       HAR
6   Abhishek Singh    140       MUM
7     Deepak Hooda    113       JAI
8  Shrikant Jadhav    112      U.P.
9  Rahul Chaudhari    109       CHE

Team performance (total Player Successful Raids):
team_name
DEL     419
KOL     403
BLR     402
HAR     370
HYD     345
MUM     343
PAT     342
PUN     318
U.P.    316
CHE     300
GUJ     296
JAI     288
Name: value, dtype: int64

Position-wise analysis:
                          sum       mean  count
position_name
                           46   3.285714     14
All Rounder               517  23.500000     22
Defender                  138   8.117647     17
Defender - Right Corner     1   1.000000      1
Defender - Right corner     1   1.000000      1
Raider                   2305  48.020833     48
defender                    3   1.000000      3
raider                   1131  87.000000     13

Correlation between matches played and Player Successful Raids: 0.52

==================================================

Stopped after 13 clicks
Exported 3_df_season7_player-raid-points.csv

Statistic: Player Raid Points
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         130 non-null    int64
 1   player_name       130 non-null    object
 2   match_played      130 non-null    int64
 3   value             130 non-null    int64
 4   team_id           130 non-null    int64
 5   team              0 non-null      object
 6   team_name         130 non-null    object
 7   rank              130 non-null    object
 8   position_id       130 non-null    int64
 9   position_name     130 non-null    object
 10  team_full_name    130 non-null    object
 11  points_per_match  130 non-null    float64
dtypes: float64(1), int64(5), object(6)
memory usage: 12.3+ KB
None
   player_id      player_name  match_played  value  team_id  team team_name  \
0        318      Pawan Kumar            24    346        1  None       BLR
1        197   Pardeep Narwal            22    302        6  None       PAT
2       2296     Naveen Kumar            23    301        2  None       DEL
3       2026  Siddharth Desai            22    217        8  None       HYD
4        143   Maninder Singh            20    205        4  None       KOL

  rank  position_id position_name     team_full_name  points_per_match
0    1            8        raider    Bengaluru Bulls         14.416667
1    2            8        Raider      Patna Pirates         13.727273
2    3            8        Raider  Dabang Delhi K.C.         13.086957
3    4            8        Raider      Telugu Titans          9.863636
4    5            8        raider    Bengal Warriors         10.250000
         player_id  match_played       value     team_id  position_id  \
count   130.000000    130.000000  130.000000  130.000000   130.000000
mean   1670.092308     13.738462   41.084615   13.053846     5.761538
std    1351.144249      7.310981   63.606717   11.976276     3.875592
min      12.000000      1.000000    1.000000    1.000000     0.000000
25%     261.750000      6.000000    3.000000    4.000000     0.000000
50%    2142.500000     15.000000   11.000000    7.000000     8.000000
75%    3082.750000     20.000000   60.000000   29.000000     8.000000
max    3241.000000     24.000000  346.000000   31.000000     9.000000

       points_per_match
count        130.000000
mean           2.602136
std            2.870300
min            0.041667
25%            0.388112
50%            1.571429
75%            4.000000
max           14.416667

Top 10 players by Player Raid Points:
       player_name  value team_name
0      Pawan Kumar    346       BLR
1   Pardeep Narwal    302       PAT
2     Naveen Kumar    301       DEL
3  Siddharth Desai    217       HYD
4   Maninder Singh    205       KOL
5  Vikash Khandola    190       HAR
6   Abhishek Singh    162       MUM
7  Shrikant Jadhav    148      U.P.
8     Deepak Hooda    146       JAI
9      Rohit Gulia    132       GUJ

Team performance (total Player Raid Points):
team_name
BLR     533
DEL     532
KOL     513
HAR     490
PAT     447
MUM     438
HYD     436
PUN     409
U.P.    408
JAI     385
CHE     378
GUJ     372
Name: value, dtype: int64

Position-wise analysis:
                          sum        mean  count
position_name
                           67    4.785714     14
All Rounder               681   28.375000     24
Defender                  197    7.880000     25
Defender - Right Corner     1    1.000000      1
Defender - Right corner     1    1.000000      1
Raider                   2940   61.250000     48
defender                    6    1.500000      4
raider                   1448  111.384615     13

Correlation between matches played and Player Raid Points: 0.46

==================================================

Stopped after 15 clicks
Exported 4_df_season7_player-successful-tackles.csv

Statistic: Player Successful Tackles
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         156 non-null    int64
 1   player_name       156 non-null    object
 2   match_played      156 non-null    int64
 3   value             156 non-null    int64
 4   team_id           156 non-null    int64
 5   team              0 non-null      object
 6   team_name         156 non-null    object
 7   rank              156 non-null    object
 8   position_id       156 non-null    int64
 9   position_name     156 non-null    object
 10  team_full_name    156 non-null    object
 11  points_per_match  156 non-null    float64
dtypes: float64(1), int64(5), object(6)
memory usage: 14.8+ KB
None
   player_id      player_name  match_played  value  team_id  team team_name  \
0        259  Fazel Atrachali            24     77        5  None       MUM
1       3240           Sumit             22     75       30  None      U.P.
2       3088     Nitesh Kumar            23     67       30  None      U.P.
3        290    Sandeep Dhull            22     66        3  None       JAI
4        157   Ravinder Pahal            23     63        2  None       DEL

  rank  position_id position_name        team_full_name  points_per_match
0    1            9      defender               U Mumba          3.208333
1    2            9      Defender           U.P. Yoddha          3.409091
2    3            9      Defender           U.P. Yoddha          2.913043
3    4            9      Defender  Jaipur Pink Panthers          3.000000
4    5            9      Defender     Dabang Delhi K.C.          2.739130
         player_id  match_played       value     team_id  position_id  \
count   156.000000    156.000000  156.000000  156.000000   156.000000
mean   1770.217949     14.455128   16.192308   12.557692     6.346154
std    1357.255515      6.859270   19.167552   11.896999     3.824630
min      12.000000      1.000000    1.000000    1.000000     0.000000
25%     286.000000      9.000000    2.000000    3.000000     0.000000
50%    2290.500000     15.500000    7.000000    7.000000     8.000000
75%    3099.250000     21.000000   27.000000   28.250000     9.000000
max    3241.000000     24.000000   77.000000   31.000000     9.000000

       points_per_match
count        156.000000
mean           0.954146
std            0.852581
min            0.045455
25%            0.250000
50%            0.601810
75%            1.448718
max            3.409091

Top 10 players by Player Successful Tackles:
       player_name  value team_name
0  Fazel Atrachali     77       MUM
1           Sumit      75      U.P.
2     Nitesh Kumar     67      U.P.
3    Sandeep Dhull     66       JAI
4   Ravinder Pahal     63       DEL
5     Baldev Singh     61       KOL
6     Rinku Narwal     60       KOL
7    Surjeet Singh     56       PUN
9     Neeraj Kumar     54       PAT
8           Sunil      54       HAR

Team performance (total Player Successful Tackles):
team_name
U.P.    241
PUN     235
KOL     217
MUM     216
DEL     214
HAR     210
JAI     209
BLR     206
GUJ     205
HYD     200
PAT     196
CHE     177
Name: value, dtype: int64

Position-wise analysis:
                          sum       mean  count
position_name
                           84   7.636364     11
All Rounder               336  13.440000     25
Defender                 1480  23.492063     63
Defender - Left Corner      6   6.000000      1
Defender - Left Cover       3   3.000000      1
Defender - Right Corner   115  57.500000      2
Defender - Right corner    15  15.000000      1
Raider                    143   4.205882     34
defender                  270  38.571429      7
raider                     74   6.727273     11

Correlation between matches played and Player Successful Tackles: 0.62

==================================================

Stopped after 15 clicks
Exported 5_df_season7_player-tackle-points.csv

Statistic: Player Tackle Points
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         156 non-null    int64
 1   player_name       156 non-null    object
 2   match_played      156 non-null    int64
 3   value             156 non-null    int64
 4   team_id           156 non-null    int64
 5   team              0 non-null      object
 6   team_name         156 non-null    object
 7   rank              156 non-null    object
 8   position_id       156 non-null    int64
 9   position_name     156 non-null    object
 10  team_full_name    156 non-null    object
 11  points_per_match  156 non-null    float64
dtypes: float64(1), int64(5), object(6)
memory usage: 14.8+ KB
None
   player_id      player_name  match_played  value  team_id  team team_name  \
0        259  Fazel Atrachali            24     82        5  None       MUM
1       3240           Sumit             22     77       30  None      U.P.
2       3088     Nitesh Kumar            23     75       30  None      U.P.
3        290    Sandeep Dhull            22     73        3  None       JAI
4        621     Baldev Singh            24     66        4  None       KOL

  rank  position_id            position_name        team_full_name  \
0    1            9                 defender               U Mumba
1    2            9                 Defender           U.P. Yoddha
2    3            9                 Defender           U.P. Yoddha
3    4            9                 Defender  Jaipur Pink Panthers
4    5            0  Defender - Right Corner       Bengal Warriors

   points_per_match
0          3.416667
1          3.500000
2          3.260870
3          3.318182
4          2.750000
         player_id  match_played      value     team_id  position_id  \
count   156.000000    156.000000  156.00000  156.000000   156.000000
mean   1770.217949     14.455128   17.75641   12.557692     6.346154
std    1357.255515      6.859270   20.69233   11.896999     3.824630
min      12.000000      1.000000    1.00000    1.000000     0.000000
25%     286.000000      9.000000    2.00000    3.000000     0.000000
50%    2290.500000     15.500000    8.00000    7.000000     8.000000
75%    3099.250000     21.000000   27.25000   28.250000     9.000000
max    3241.000000     24.000000   82.00000   31.000000     9.000000

       points_per_match
count        156.000000
mean           1.051342
std            0.917201
min            0.047619
25%            0.311842
50%            0.679487
75%            1.616667
max            3.500000

Top 10 players by Player Tackle Points:
        player_name  value team_name
0   Fazel Atrachali     82       MUM
1            Sumit      77      U.P.
2      Nitesh Kumar     75      U.P.
3     Sandeep Dhull     73       JAI
4      Baldev Singh     66       KOL
5      Rinku Narwal     64       KOL
6     Surjeet Singh     63       PUN
7    Ravinder Pahal     63       DEL
8  Vishal Bharadwaj     62       HYD
9    Mahender Singh     61       BLR

Team performance (total Player Tackle Points):
team_name
PUN     264
U.P.    260
JAI     240
MUM     233
BLR     232
KOL     229
HAR     225
PAT     225
GUJ     224
HYD     224
DEL     222
CHE     192
Name: value, dtype: int64

Position-wise analysis:
                          sum       mean  count
position_name
                           88   8.000000     11
All Rounder               374  14.960000     25
Defender                 1611  25.571429     63
Defender - Left Corner      6   6.000000      1
Defender - Left Cover       4   4.000000      1
Defender - Right Corner   121  60.500000      2
Defender - Right corner    17  17.000000      1
Raider                    170   5.000000     34
defender                  301  43.000000      7
raider                     78   7.090909     11

Correlation between matches played and Player Tackle Points: 0.62

==================================================


### season 6

In [6]:
import pandas as pd
import json
import re
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.firefox.options import Options
from bs4 import BeautifulSoup
import time


import requests
import csv
from bs4 import BeautifulSoup
from selenium  import webdriver
import pandas as pd
import numpy as np
from selenium.webdriver.common.by import By
import os


d={"s-10": "44", 
   "s-9": "25", 
   "s-8": "20",
   "s-7": "11",
   "s-6": "10",
   "s-5": "8",
   "s-4": "4",
   "s-3": "3",
   "s-2": "2",
   "s-1": "1",
   "s-all":"0" ,
   
   }


def extract_json_from_script(script_content):
    start = script_content.find('window.statsWidgetData = ')
    if start == -1:
        return None
    start += len('window.statsWidgetData = ')
    
    bracket_count = 0
    end = start
    for i, char in enumerate(script_content[start:]):
        if char == '{':
            bracket_count += 1
        elif char == '}':
            bracket_count -= 1
            if bracket_count == 0:
                end = start + i + 1
                break
    
    if bracket_count != 0:
        return None
    
    json_str = script_content[start:end]
    
    try:
        return json.loads(json_str)
    except json.JSONDecodeError:
        return None

def fetch_and_process_data(url):
    options = webdriver.FirefoxOptions()
    options.add_argument("--headless")
    driver = webdriver.Firefox(options=options)
    
    try:
        driver.get(url)
        
        for i in range(21):
            try:
                element = WebDriverWait(driver, 10).until(
                    EC.presence_of_element_located((By.CLASS_NAME, 'loadmore'))
                )
                driver.execute_script("arguments[0].click();", element)
                time.sleep(1)
            except:
                print(f"Stopped after {i} clicks")
                break
        
        soup = BeautifulSoup(driver.page_source, 'html.parser')
        script_tag = soup.find('script', string=lambda text: text and 'window.statsWidgetData' in text)
        
        if script_tag:
            json_data = extract_json_from_script(script_tag.string)
            if json_data:
                player_data = json_data['stats']['data']
                df = pd.DataFrame(player_data)
                
                df['value'] = pd.to_numeric(df['value'])
                df['match_played'] = pd.to_numeric(df['match_played'])
                
                df['points_per_match'] = df['value'] / df['match_played']
                
                return df, json_data['stats']['stat']
    
    finally:
        driver.quit()
    
    return None, None

urls = [
    f"https://www.prokabaddi.com/stats/{d['s-6']}-102-total-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-6']}-21-successful-raids-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-6']}-22-raid-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-6']}-23-successful-tackles-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-6']}-103-tackle-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-6']}-22-avg-raid-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-6']}-139-avg-tackle-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-6']}-132-do-or-die-raid-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-6']}-104-super-raids-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-6']}-28-super-tackles-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-6']}-100-super-10s-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-6']}-101-high-5s-statistics"
]   

x = 0
for url in urls:
    x+=1
    df, stat_name = fetch_and_process_data(url)
    if df is not None:
        # Create a file name based on the statistic
        file_name = f"{x}_df_season6_{stat_name.lower().replace(' ', '-')}.csv"
        
        # Export the DataFrame to CSV
        df.to_csv(file_name, index=False)
        print(f"Exported {file_name}")
        
        # Display basic information about the DataFrame
        print(f"\nStatistic: {stat_name}")
        print(df.info())
        
        # Display the first few rows
        print(df.head())
        
        # Basic statistics
        print(df.describe())
        
        # Top 10 players by the statistic
        top_10_players = df.sort_values('value', ascending=False).head(10)
        print(f"\nTop 10 players by {stat_name}:")
        print(top_10_players[['player_name', 'value', 'team_name']])
        
        # Team performance
        team_performance = df.groupby('team_name')['value'].sum().sort_values(ascending=False)
        print(f"\nTeam performance (total {stat_name}):")
        print(team_performance)
        
        # Position-wise analysis
        position_analysis = df.groupby('position_name')['value'].agg(['sum', 'mean', 'count'])
        print("\nPosition-wise analysis:")
        print(position_analysis)
        
        # Correlation between matches played and the statistic
        correlation = df['match_played'].corr(df['value'])
        print(f"\nCorrelation between matches played and {stat_name}: {correlation:.2f}")
        
        print("\n" + "="*50 + "\n")
    else:
        print(f"Failed to fetch or process data from {url}")

Stopped after 18 clicks
Exported 1_df_season6_player-total-points.csv

Statistic: Player Total Points
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187 entries, 0 to 186
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         187 non-null    int64
 1   player_name       187 non-null    object
 2   match_played      187 non-null    int64
 3   value             187 non-null    int64
 4   team_id           187 non-null    int64
 5   team              0 non-null      object
 6   team_name         187 non-null    object
 7   rank              187 non-null    object
 8   position_id       187 non-null    int64
 9   position_name     187 non-null    object
 10  team_full_name    187 non-null    object
 11  points_per_match  187 non-null    float64
dtypes: float64(1), int64(5), object(6)
memory usage: 17.7+ KB
None
   player_id      player_name  match_played  value  team_id  team team_name  \
0        318      Pawan Kumar            24    282        1  None       BLR
1        197   Pardeep Narwal            21    233        6  None       PAT
2       2026  Siddharth Desai            21    221        5  None       MUM
3         41     Deepak Hooda            22    208        3  None       JAI
4        143   Maninder Singh            22    206        4  None       KOL

  rank  position_id position_name        team_full_name  points_per_match
0    1            8        raider       Bengaluru Bulls         11.750000
1    2            8        Raider         Patna Pirates         11.095238
2    3            8        Raider               U Mumba         10.523810
3    4            0   All Rounder  Jaipur Pink Panthers          9.454545
4    5            8        raider       Bengal Warriors          9.363636
         player_id  match_played       value     team_id  position_id  \
count   187.000000    187.000000  187.000000  187.000000   187.000000
mean   1123.513369     13.171123   43.122995   12.989305     5.267380
std    1189.541731      7.343538   52.749467   12.113260     4.150807
min      12.000000      1.000000    1.000000    1.000000     0.000000
25%     188.000000      6.000000    8.000000    3.000000     0.000000
50%     390.000000     13.000000   23.000000    6.000000     8.000000
75%    2310.000000     20.000000   57.000000   29.000000     9.000000
max    3159.000000     25.000000  282.000000   31.000000     9.000000

       points_per_match
count        187.000000
mean           2.617016
std            2.243064
min            0.090909
25%            1.250000
50%            2.000000
75%            3.238636
max           11.750000

Top 10 players by Player Total Points:
       player_name  value team_name
0      Pawan Kumar    282       BLR
1   Pardeep Narwal    233       PAT
2  Siddharth Desai    221       MUM
3     Deepak Hooda    208       JAI
4   Maninder Singh    206       KOL
5      Ajay Thakur    204       CHE
6          Sachin     204       GUJ
7     Naveen Kumar    177       DEL
8  Vikash Khandola    177       HAR
9      Rohit Kumar    171       BLR

Team performance (total Player Total Points):
team_name
BLR     777
GUJ     754
MUM     748
U.P.    714
DEL     699
PAT     697
HAR     640
JAI     640
KOL     636
CHE     608
HYD     586
PUN     565
Name: value, dtype: int64

Position-wise analysis:
                          sum        mean  count
position_name
                          327   10.218750     32
All Rounder              1123   36.225806     31
Defender                 1585   31.078431     51
Defender - Left Corner     42   21.000000      2
Defender - Left Cover      30   15.000000      2
Defender - Right Corner    70   23.333333      3
Defender - Right corner    12   12.000000      1
Raider                   2987   66.377778     45
defender                  283   47.166667      6
raider                   1605  114.642857     14

Correlation between matches played and Player Total Points: 0.69

==================================================

Stopped after 11 clicks
Exported 2_df_season6_player-successful-raids.csv

Statistic: Player Successful Raids
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119 entries, 0 to 118
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         119 non-null    int64
 1   player_name       119 non-null    object
 2   match_played      119 non-null    int64
 3   value             119 non-null    int64
 4   team_id           119 non-null    int64
 5   team              0 non-null      object
 6   team_name         119 non-null    object
 7   rank              119 non-null    object
 8   position_id       119 non-null    int64
 9   position_name     119 non-null    object
 10  team_full_name    119 non-null    object
 11  points_per_match  119 non-null    float64
dtypes: float64(1), int64(5), object(6)
memory usage: 11.3+ KB
None
   player_id      player_name  match_played  value  team_id  team team_name  \
0        318      Pawan Kumar            24    209        1  None       BLR
1        197   Pardeep Narwal            21    185        6  None       PAT
2         26      Ajay Thakur            22    177       29  None       CHE
3       2026  Siddharth Desai            21    169        5  None       MUM
4         41     Deepak Hooda            22    162        3  None       JAI

  rank  position_id position_name        team_full_name  points_per_match
0    1            8        raider       Bengaluru Bulls          8.708333
1    2            8        Raider         Patna Pirates          8.809524
2    3            8        Raider       Tamil Thalaivas          8.045455
3    4            8        Raider               U Mumba          8.047619
4    5            0   All Rounder  Jaipur Pink Panthers          7.363636
         player_id  match_played       value     team_id  position_id  \
count   119.000000    119.000000  119.000000  119.000000   119.000000
mean   1134.033613     12.789916   35.285714   12.991597     4.882353
std    1167.566446      7.162608   49.532585   11.975608     4.042521
min      12.000000      2.000000    1.000000    1.000000     0.000000
25%     199.500000      6.000000    3.000000    4.000000     0.000000
50%     390.000000     13.000000   13.000000    7.000000     8.000000
75%    2304.000000     19.000000   49.000000   28.500000     8.000000
max    3159.000000     25.000000  209.000000   31.000000     9.000000

       points_per_match
count        119.000000
mean           2.075769
std            2.175917
min            0.052632
25%            0.500000
50%            1.285714
75%            2.657143
max            8.809524

Top 10 players by Player Successful Raids:
       player_name  value team_name
0      Pawan Kumar    209       BLR
1   Pardeep Narwal    185       PAT
2      Ajay Thakur    177       CHE
3  Siddharth Desai    169       MUM
4     Deepak Hooda    162       JAI
5          Sachin     159       GUJ
6   Maninder Singh    158       KOL
7     Naveen Kumar    144       DEL
8  Rahul Chaudhari    136       HYD
9  Vikash Khandola    136       HAR

Team performance (total Player Successful Raids):
team_name
BLR     421
PAT     394
DEL     387
GUJ     376
MUM     366
HAR     351
U.P.    348
CHE     340
JAI     329
KOL     329
HYD     282
PUN     276
Name: value, dtype: int64

Position-wise analysis:
                         sum       mean  count
position_name
                         100   4.545455     22
All Rounder              491  22.318182     22
Defender                 167  15.181818     11
Defender - Left Corner     3   1.500000      2
Defender - Left Cover      2   1.000000      2
Raider                  2230  50.681818     44
defender                   5   2.500000      2
raider                  1201  85.785714     14

Correlation between matches played and Player Successful Raids: 0.67

==================================================

Stopped after 12 clicks
Exported 3_df_season6_player-raid-points.csv

Statistic: Player Raid Points
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         125 non-null    int64
 1   player_name       125 non-null    object
 2   match_played      125 non-null    int64
 3   value             125 non-null    int64
 4   team_id           125 non-null    int64
 5   team              0 non-null      object
 6   team_name         125 non-null    object
 7   rank              125 non-null    object
 8   position_id       125 non-null    int64
 9   position_name     125 non-null    object
 10  team_full_name    125 non-null    object
 11  points_per_match  125 non-null    float64
dtypes: float64(1), int64(5), object(6)
memory usage: 11.8+ KB
None
   player_id      player_name  match_played  value  team_id  team team_name  \
0        318      Pawan Kumar            24    271        1  None       BLR
1        197   Pardeep Narwal            21    233        6  None       PAT
2       2026  Siddharth Desai            21    218        5  None       MUM
3        143   Maninder Singh            22    206        4  None       KOL
4         26      Ajay Thakur            22    203       29  None       CHE

  rank  position_id position_name   team_full_name  points_per_match
0    1            8        raider  Bengaluru Bulls         11.291667
1    2            8        Raider    Patna Pirates         11.095238
2    3            8        Raider          U Mumba         10.380952
3    4            8        raider  Bengal Warriors          9.363636
4    5            8        Raider  Tamil Thalaivas          9.227273
         player_id  match_played      value     team_id  position_id  \
count   125.000000    125.000000  125.00000  125.000000   125.000000
mean   1120.928000     13.064000   42.64000   13.008000     4.936000
std    1162.322946      7.143398   60.44024   11.957921     4.059525
min      12.000000      2.000000    1.00000    1.000000     0.000000
25%     202.000000      6.000000    3.00000    4.000000     0.000000
50%     390.000000     13.000000   13.00000    7.000000     8.000000
75%    2302.000000     19.000000   55.00000   29.000000     8.000000
max    3159.000000     25.000000  271.00000   31.000000     9.000000

       points_per_match
count        125.000000
mean           2.555416
std            2.653577
min            0.040000
25%            0.500000
50%            1.526316
75%            3.350000
max           11.291667

Top 10 players by Player Raid Points:
       player_name  value team_name
0      Pawan Kumar    271       BLR
1   Pardeep Narwal    233       PAT
2  Siddharth Desai    218       MUM
3   Maninder Singh    206       KOL
4      Ajay Thakur    203       CHE
5     Deepak Hooda    196       JAI
6          Sachin     190       GUJ
7     Naveen Kumar    172       DEL
8  Vikash Khandola    172       HAR
9      Rohit Kumar    162       BLR

Team performance (total Player Raid Points):
team_name
BLR     547
PAT     496
DEL     483
GUJ     480
MUM     459
U.P.    449
HAR     447
KOL     436
CHE     419
JAI     415
HYD     353
PUN     346
Name: value, dtype: int64

Position-wise analysis:
                          sum        mean  count
position_name
                          149    6.478261     23
All Rounder               634   28.818182     22
Defender                  221   14.733333     15
Defender - Left Corner      5    2.500000      2
Defender - Left Cover       5    2.500000      2
Defender - Right Corner     1    1.000000      1
Raider                   2775   63.068182     44
defender                    6    3.000000      2
raider                   1534  109.571429     14

Correlation between matches played and Player Raid Points: 0.62

==================================================

Stopped after 15 clicks
Exported 4_df_season6_player-successful-tackles.csv

Statistic: Player Successful Tackles
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155 entries, 0 to 154
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         155 non-null    int64
 1   player_name       155 non-null    object
 2   match_played      155 non-null    int64
 3   value             155 non-null    int64
 4   team_id           155 non-null    int64
 5   team              0 non-null      object
 6   team_name         155 non-null    object
 7   rank              155 non-null    object
 8   position_id       155 non-null    int64
 9   position_name     155 non-null    object
 10  team_full_name    155 non-null    object
 11  points_per_match  155 non-null    float64
dtypes: float64(1), int64(5), object(6)
memory usage: 14.7+ KB
None
   player_id        player_name  match_played  value  team_id  team team_name  \
0       3088       Nitesh Kumar            25     92       30  None      U.P.
1        357  Parvesh Bhainswal            25     82       31  None       GUJ
2        259    Fazel Atrachali            23     80        5  None       MUM
3        368        Sunil Kumar            25     72       31  None       GUJ
4        769     Mahender Singh            24     62        1  None       BLR

  rank  position_id position_name   team_full_name  points_per_match
0    1            9      Defender      U.P. Yoddha          3.680000
1    2            9      defender   Gujarat Giants          3.280000
2    3            9      defender          U Mumba          3.478261
3    4            9      Defender   Gujarat Giants          2.880000
4    5            9      Defender  Bengaluru Bulls          2.583333
         player_id  match_played       value     team_id  position_id  \
count   155.000000    155.000000  155.000000  155.000000   155.000000
mean   1045.645161     14.541935   16.180645   12.516129     5.419355
std    1190.691460      7.015973   19.155370   11.937257     4.165210
min      12.000000      1.000000    1.000000    1.000000     0.000000
25%     176.500000      8.000000    3.000000    3.000000     0.000000
50%     368.000000     16.000000    8.000000    6.000000     8.000000
75%    2302.000000     21.000000   22.000000   28.000000     9.000000
max    3159.000000     25.000000   92.000000   31.000000     9.000000

       points_per_match
count        155.000000
mean           0.996472
std            0.856104
min            0.045455
25%            0.320513
50%            0.764706
75%            1.361111
max            4.000000

Top 10 players by Player Successful Tackles:
         player_name  value team_name
0       Nitesh Kumar     92      U.P.
1  Parvesh Bhainswal     82       GUJ
2    Fazel Atrachali     80       MUM
3        Sunil Kumar     72       GUJ
4     Mahender Singh     62       BLR
5      Sandeep Dhull     62       JAI
6     Surinder Singh     59       MUM
7           Jaideep      56       PAT
8     Ravinder Pahal     56       DEL
9   Manjeet Chhillar     54       CHE

Team performance (total Player Successful Tackles):
team_name
MUM     274
GUJ     258
U.P.    240
BLR     219
HYD     202
JAI     202
DEL     198
PUN     189
KOL     186
PAT     186
HAR     180
CHE     174
Name: value, dtype: int64

Position-wise analysis:
                          sum       mean  count
position_name
                          157   6.826087     23
All Rounder               456  16.888889     27
Defender                 1255  25.100000     50
Defender - Left Corner     33  16.500000      2
Defender - Left Cover      20  20.000000      1
Defender - Right Corner    66  22.000000      3
Defender - Right corner     9   9.000000      1
Raider                    189   6.517241     29
defender                  255  42.500000      6
raider                     68   5.230769     13

Correlation between matches played and Player Successful Tackles: 0.59

==================================================

Stopped after 15 clicks
Exported 5_df_season6_player-tackle-points.csv

Statistic: Player Tackle Points
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155 entries, 0 to 154
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         155 non-null    int64
 1   player_name       155 non-null    object
 2   match_played      155 non-null    int64
 3   value             155 non-null    int64
 4   team_id           155 non-null    int64
 5   team              0 non-null      object
 6   team_name         155 non-null    object
 7   rank              155 non-null    object
 8   position_id       155 non-null    int64
 9   position_name     155 non-null    object
 10  team_full_name    155 non-null    object
 11  points_per_match  155 non-null    float64
dtypes: float64(1), int64(5), object(6)
memory usage: 14.7+ KB
None
   player_id        player_name  match_played  value  team_id  team team_name  \
0       3088       Nitesh Kumar            25    100       30  None      U.P.
1        357  Parvesh Bhainswal            25     86       31  None       GUJ
2        259    Fazel Atrachali            23     83        5  None       MUM
3        368        Sunil Kumar            25     76       31  None       GUJ
4        290      Sandeep Dhull            22     67        3  None       JAI

  rank  position_id position_name        team_full_name  points_per_match
0    1            9      Defender           U.P. Yoddha          4.000000
1    2            9      defender        Gujarat Giants          3.440000
2    3            9      defender               U Mumba          3.608696
3    4            9      Defender        Gujarat Giants          3.040000
4    5            9      Defender  Jaipur Pink Panthers          3.045455
         player_id  match_played       value     team_id  position_id  \
count   155.000000    155.000000  155.000000  155.000000   155.000000
mean   1045.645161     14.541935   17.638710   12.516129     5.419355
std    1190.691460      7.015973   20.488794   11.937257     4.165210
min      12.000000      1.000000    1.000000    1.000000     0.000000
25%     176.500000      8.000000    3.000000    3.000000     0.000000
50%     368.000000     16.000000   10.000000    6.000000     8.000000
75%    2302.000000     21.000000   25.000000   28.000000     9.000000
max    3159.000000     25.000000  100.000000   31.000000     9.000000

       points_per_match
count        155.000000
mean           1.096483
std            0.914391
min            0.045455
25%            0.333333
50%            0.850000
75%            1.605556
max            4.000000

Top 10 players by Player Tackle Points:
         player_name  value team_name
0       Nitesh Kumar    100      U.P.
1  Parvesh Bhainswal     86       GUJ
2    Fazel Atrachali     83       MUM
3        Sunil Kumar     76       GUJ
4      Sandeep Dhull     67       JAI
5     Mahender Singh     63       BLR
6     Surinder Singh     62       MUM
7   Vishal Bharadwaj     60       HYD
8   Manjeet Chhillar     59       CHE
9     Ravinder Pahal     59       DEL

Team performance (total Player Tackle Points):
team_name
MUM     289
GUJ     274
U.P.    265
HYD     233
BLR     230
JAI     225
PUN     219
DEL     216
PAT     201
KOL     200
HAR     193
CHE     189
Name: value, dtype: int64

Position-wise analysis:
                          sum       mean  count
position_name
                          178   7.739130     23
All Rounder               489  18.111111     27
Defender                 1364  27.280000     50
Defender - Left Corner     37  18.500000      2
Defender - Left Cover      25  25.000000      1
Defender - Right Corner    69  23.000000      3
Defender - Right corner    12  12.000000      1
Raider                    212   7.310345     29
defender                  277  46.166667      6
raider                     71   5.461538     13

Correlation between matches played and Player Tackle Points: 0.59

==================================================


### season 5

In [7]:
import pandas as pd
import json
import re
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.firefox.options import Options
from bs4 import BeautifulSoup
import time


import requests
import csv
from bs4 import BeautifulSoup
from selenium  import webdriver
import pandas as pd
import numpy as np
from selenium.webdriver.common.by import By
import os


d={"s-10": "44", 
   "s-9": "25", 
   "s-8": "20",
   "s-7": "11",
   "s-6": "10",
   "s-5": "8",
   "s-4": "4",
   "s-3": "3",
   "s-2": "2",
   "s-1": "1",
   "s-all":"0" ,
   
   }


def extract_json_from_script(script_content):
    start = script_content.find('window.statsWidgetData = ')
    if start == -1:
        return None
    start += len('window.statsWidgetData = ')
    
    bracket_count = 0
    end = start
    for i, char in enumerate(script_content[start:]):
        if char == '{':
            bracket_count += 1
        elif char == '}':
            bracket_count -= 1
            if bracket_count == 0:
                end = start + i + 1
                break
    
    if bracket_count != 0:
        return None
    
    json_str = script_content[start:end]
    
    try:
        return json.loads(json_str)
    except json.JSONDecodeError:
        return None

def fetch_and_process_data(url):
    options = webdriver.FirefoxOptions()
    options.add_argument("--headless")
    driver = webdriver.Firefox(options=options)
    
    try:
        driver.get(url)
        
        for i in range(21):
            try:
                element = WebDriverWait(driver, 10).until(
                    EC.presence_of_element_located((By.CLASS_NAME, 'loadmore'))
                )
                driver.execute_script("arguments[0].click();", element)
                time.sleep(1)
            except:
                print(f"Stopped after {i} clicks")
                break
        
        soup = BeautifulSoup(driver.page_source, 'html.parser')
        script_tag = soup.find('script', string=lambda text: text and 'window.statsWidgetData' in text)
        
        if script_tag:
            json_data = extract_json_from_script(script_tag.string)
            if json_data:
                player_data = json_data['stats']['data']
                df = pd.DataFrame(player_data)
                
                df['value'] = pd.to_numeric(df['value'])
                df['match_played'] = pd.to_numeric(df['match_played'])
                
                df['points_per_match'] = df['value'] / df['match_played']
                
                return df, json_data['stats']['stat']
    
    finally:
        driver.quit()
    
    return None, None

urls = [
    f"https://www.prokabaddi.com/stats/{d['s-5']}-102-total-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-5']}-21-successful-raids-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-5']}-22-raid-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-5']}-23-successful-tackles-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-5']}-103-tackle-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-5']}-22-avg-raid-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-5']}-139-avg-tackle-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-5']}-132-do-or-die-raid-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-5']}-104-super-raids-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-5']}-28-super-tackles-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-5']}-100-super-10s-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-5']}-101-high-5s-statistics"
]   

x = 0
for url in urls:
    x+=1
    df, stat_name = fetch_and_process_data(url)
    if df is not None:
        # Create a file name based on the statistic
        file_name = f"{x}_df_season5_{stat_name.lower().replace(' ', '-')}.csv"
        
        # Export the DataFrame to CSV
        df.to_csv(file_name, index=False)
        print(f"Exported {file_name}")
        
        # Display basic information about the DataFrame
        print(f"\nStatistic: {stat_name}")
        print(df.info())
        
        # Display the first few rows
        print(df.head())
        
        # Basic statistics
        print(df.describe())
        
        # Top 10 players by the statistic
        top_10_players = df.sort_values('value', ascending=False).head(10)
        print(f"\nTop 10 players by {stat_name}:")
        print(top_10_players[['player_name', 'value', 'team_name']])
        
        # Team performance
        team_performance = df.groupby('team_name')['value'].sum().sort_values(ascending=False)
        print(f"\nTeam performance (total {stat_name}):")
        print(team_performance)
        
        # Position-wise analysis
        position_analysis = df.groupby('position_name')['value'].agg(['sum', 'mean', 'count'])
        print("\nPosition-wise analysis:")
        print(position_analysis)
        
        # Correlation between matches played and the statistic
        correlation = df['match_played'].corr(df['value'])
        print(f"\nCorrelation between matches played and {stat_name}: {correlation:.2f}")
        
        print("\n" + "="*50 + "\n")
    else:
        print(f"Failed to fetch or process data from {url}")

Stopped after 18 clicks
Exported 1_df_season5_player-total-points.csv

Statistic: Player Total Points
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181 entries, 0 to 180
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         181 non-null    int64
 1   player_name       181 non-null    object
 2   match_played      181 non-null    int64
 3   value             181 non-null    int64
 4   team_id           181 non-null    int64
 5   team              0 non-null      object
 6   team_name         181 non-null    object
 7   rank              181 non-null    object
 8   position_id       181 non-null    int64
 9   position_name     181 non-null    object
 10  team_full_name    181 non-null    object
 11  points_per_match  181 non-null    float64
dtypes: float64(1), int64(5), object(6)
memory usage: 17.1+ KB
None
   player_id      player_name  match_played  value  team_id  team team_name  \
0        197   Pardeep Narwal            26    369        6  None       PAT
1        326      Rohit Kumar            22    231        1  None       BLR
2         26      Ajay Thakur            22    222       29  None       CHE
3        388       Monu Goyat            26    202        6  None       PAT
4         81  Rahul Chaudhari            22    193        8  None       HYD

  rank  position_id position_name   team_full_name  points_per_match
0    1            8        Raider    Patna Pirates         14.192308
1    2            8        Raider  Bengaluru Bulls         10.500000
2    3            8        Raider  Tamil Thalaivas         10.090909
3    4            8        Raider    Patna Pirates          7.769231
4    5            8        Raider    Telugu Titans          8.772727
         player_id  match_played       value     team_id  position_id  \
count   181.000000    181.000000  181.000000  181.000000   181.000000
mean    644.469613     13.596685   42.038674   12.988950     6.784530
std     891.614419      7.382245   52.844990   12.003698     3.419386
min      11.000000      1.000000    1.000000    1.000000     0.000000
25%     157.000000      6.000000    7.000000    4.000000     8.000000
50%     300.000000     15.000000   24.000000    7.000000     8.000000
75%     712.000000     20.000000   58.000000   28.000000     9.000000
max    3159.000000     26.000000  369.000000   31.000000     9.000000

       points_per_match
count        181.000000
mean           2.476514
std            2.200735
min            0.142857
25%            1.000000
50%            1.800000
75%            3.000000
max           14.192308

Top 10 players by Player Total Points:
        player_name  value team_name
0    Pardeep Narwal    369       PAT
1       Rohit Kumar    231       BLR
2       Ajay Thakur    222       CHE
3        Monu Goyat    202       PAT
4   Rahul Chaudhari    193       HYD
5    Maninder Singh    192       KOL
6      Deepak Hooda    186       PUN
7       Nitin Tomar    177      U.P.
8            Sachin    173       GUJ
9  Rishank Devadiga    170      U.P.

Team performance (total Player Total Points):
team_name
PAT     889
U.P.    662
GUJ     659
PUN     650
KOL     648
HAR     631
MUM     621
CHE     611
HYD     607
BLR     594
JAI     524
DEL     513
Name: value, dtype: int64

Position-wise analysis:
                sum       mean  count
position_name
All Rounder    1203  33.416667     36
Defender       1678  24.676471     68
Raider         4728  61.402597     77

Correlation between matches played and Player Total Points: 0.65

==================================================

Stopped after 11 clicks
Exported 2_df_season5_player-successful-raids.csv

Statistic: Player Successful Raids
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112 entries, 0 to 111
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         112 non-null    int64
 1   player_name       112 non-null    object
 2   match_played      112 non-null    int64
 3   value             112 non-null    int64
 4   team_id           112 non-null    int64
 5   team              0 non-null      object
 6   team_name         112 non-null    object
 7   rank              112 non-null    object
 8   position_id       112 non-null    int64
 9   position_name     112 non-null    object
 10  team_full_name    112 non-null    object
 11  points_per_match  112 non-null    float64
dtypes: float64(1), int64(5), object(6)
memory usage: 10.6+ KB
None
   player_id      player_name  match_played  value  team_id  team team_name  \
0        197   Pardeep Narwal            26    271        6  None       PAT
1        326      Rohit Kumar            22    192        1  None       BLR
2         26      Ajay Thakur            22    182       29  None       CHE
3         81  Rahul Chaudhari            22    159        8  None       HYD
4        388       Monu Goyat            26    159        6  None       PAT

  rank  position_id position_name   team_full_name  points_per_match
0    1            8        Raider    Patna Pirates         10.423077
1    2            8        Raider  Bengaluru Bulls          8.727273
2    3            8        Raider  Tamil Thalaivas          8.272727
3    4            8        Raider    Telugu Titans          7.227273
4    5            8        Raider    Patna Pirates          6.115385
         player_id  match_played       value     team_id  position_id  \
count   112.000000    112.000000  112.000000  112.000000   112.000000
mean    621.160714     14.544643   35.678571   12.714286     6.276786
std     920.193904      6.946239   49.533538   11.970255     3.482802
min      12.000000      1.000000    1.000000    1.000000     0.000000
25%     136.750000      9.000000    3.000000    3.000000     8.000000
50%     267.000000     16.000000   13.000000    7.000000     8.000000
75%     641.750000     21.000000   49.000000   28.000000     8.000000
max    3159.000000     26.000000  271.000000   31.000000     9.000000

       points_per_match
count        112.000000
mean           2.016926
std            2.131130
min            0.041667
25%            0.484375
50%            1.155556
75%            3.191919
max           10.423077

Top 10 players by Player Successful Raids:
        player_name  value team_name
0    Pardeep Narwal    271       PAT
1       Rohit Kumar    192       BLR
2       Ajay Thakur    182       CHE
3   Rahul Chaudhari    159       HYD
4        Monu Goyat    159       PAT
5    Maninder Singh    154       KOL
6       Nitin Tomar    135      U.P.
7            Sachin    132       GUJ
8      Deepak Hooda    127       PUN
9  Rishank Devadiga    126      U.P.

Team performance (total Player Successful Raids):
team_name
PAT     479
KOL     368
U.P.    353
CHE     343
GUJ     330
BLR     327
HYD     325
HAR     318
MUM     312
PUN     293
DEL     275
JAI     273
Name: value, dtype: int64

Position-wise analysis:
                sum       mean  count
position_name
All Rounder     434  16.692308     26
Defender         40   2.666667     15
Raider         3522  49.605634     71

Correlation between matches played and Player Successful Raids: 0.56

==================================================

Stopped after 12 clicks
Exported 3_df_season5_player-raid-points.csv

Statistic: Player Raid Points
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         122 non-null    int64
 1   player_name       122 non-null    object
 2   match_played      122 non-null    int64
 3   value             122 non-null    int64
 4   team_id           122 non-null    int64
 5   team              0 non-null      object
 6   team_name         122 non-null    object
 7   rank              122 non-null    object
 8   position_id       122 non-null    int64
 9   position_name     122 non-null    object
 10  team_full_name    122 non-null    object
 11  points_per_match  122 non-null    float64
dtypes: float64(1), int64(5), object(6)
memory usage: 11.6+ KB
None
   player_id     player_name  match_played  value  team_id  team team_name  \
0        197  Pardeep Narwal            26    369        6  None       PAT
1        326     Rohit Kumar            22    219        1  None       BLR
2         26     Ajay Thakur            22    213       29  None       CHE
3        388      Monu Goyat            26    191        6  None       PAT
4        143  Maninder Singh            21    190        4  None       KOL

  rank  position_id position_name   team_full_name  points_per_match
0    1            8        Raider    Patna Pirates         14.192308
1    2            8        Raider  Bengaluru Bulls          9.954545
2    3            8        Raider  Tamil Thalaivas          9.681818
3    4            8        Raider    Patna Pirates          7.346154
4    5            8        Raider  Bengal Warriors          9.047619
         player_id  match_played      value     team_id  position_id  \
count   122.000000    122.000000  122.00000  122.000000   122.000000
mean    614.877049     14.204918   41.47541   13.032787     6.336066
std     885.297994      7.100155   60.37845   12.083001     3.491692
min      11.000000      1.000000    1.00000    1.000000     0.000000
25%     142.250000      8.250000    3.25000    3.250000     8.000000
50%     273.500000     16.000000   13.50000    7.000000     8.000000
75%     683.500000     20.000000   60.50000   28.000000     8.000000
max    3159.000000     26.000000  369.00000   31.000000     9.000000

       points_per_match
count        122.000000
mean           2.382983
std            2.596091
min            0.041667
25%            0.500000
50%            1.527778
75%            3.761029
max           14.192308

Top 10 players by Player Raid Points:
        player_name  value team_name
0    Pardeep Narwal    369       PAT
1       Rohit Kumar    219       BLR
2       Ajay Thakur    213       CHE
3        Monu Goyat    191       PAT
4    Maninder Singh    190       KOL
5   Rahul Chaudhari    184       HYD
6      Deepak Hooda    172       PUN
7       Nitin Tomar    167      U.P.
8  Rishank Devadiga    165      U.P.
9            Sachin    159       GUJ

Team performance (total Player Raid Points):
team_name
PAT     637
U.P.    461
KOL     455
MUM     419
CHE     410
GUJ     405
HAR     404
HYD     400
BLR     393
PUN     379
JAI     353
DEL     344
Name: value, dtype: int64

Position-wise analysis:
                sum       mean  count
position_name
All Rounder     582  20.785714     28
Defender         66   3.142857     21
Raider         4412  60.438356     73

Correlation between matches played and Player Raid Points: 0.54

==================================================

Stopped after 15 clicks
Exported 4_df_season5_player-successful-tackles.csv

Statistic: Player Successful Tackles
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         150 non-null    int64
 1   player_name       150 non-null    object
 2   match_played      150 non-null    int64
 3   value             150 non-null    int64
 4   team_id           150 non-null    int64
 5   team              0 non-null      object
 6   team_name         150 non-null    object
 7   rank              150 non-null    object
 8   position_id       150 non-null    int64
 9   position_name     150 non-null    object
 10  team_full_name    150 non-null    object
 11  points_per_match  150 non-null    float64
dtypes: float64(1), int64(5), object(6)
memory usage: 14.2+ KB
None
   player_id      player_name  match_played  value  team_id  team team_name  \
0        146    Surender Nada            21     74       28  None       HAR
1        322    Surjeet Singh            24     72        4  None       KOL
2       3083  Vishal Bhardwaj            22     68        8  None       HYD
3        579          Jaideep            26     66        6  None       PAT
4        489   Abozar Mighani            24     63       31  None       GUJ

  rank  position_id position_name    team_full_name  points_per_match
0    1            9      Defender  Haryana Steelers          3.523810
1    2            9      Defender   Bengal Warriors          3.000000
2    3            0   All Rounder     Telugu Titans          3.090909
3    4            9      Defender     Patna Pirates          2.538462
4    5            9      Defender    Gujarat Giants          2.625000
         player_id  match_played       value     team_id  position_id  \
count   150.000000    150.000000  150.000000  150.000000   150.000000
mean    627.473333     14.553333   15.646667   13.780000     6.800000
std     881.099166      7.043048   17.672311   12.228732     3.510292
min      26.000000      1.000000    1.000000    1.000000     0.000000
25%     151.250000      8.250000    3.000000    4.000000     8.000000
50%     290.000000     16.000000    9.000000    7.000000     8.000000
75%     711.500000     21.000000   22.750000   29.000000     9.000000
max    3159.000000     26.000000   74.000000   31.000000     9.000000

       points_per_match
count        150.000000
mean           0.962041
std            0.780005
min            0.041667
25%            0.333333
50%            0.758454
75%            1.315559
max            3.523810

Top 10 players by Player Successful Tackles:
           player_name  value team_name
0        Surender Nada     74       HAR
1        Surjeet Singh     72       KOL
2      Vishal Bhardwaj     68       HYD
3              Jaideep     66       PAT
4       Abozar Mighani     63       GUJ
5  Girish Maruti Ernak     61       PUN
6       Surinder Singh     58       MUM
8          Sunil Kumar     55       GUJ
7           Amit Hooda     55       CHE
9      Fazel Atrachali     54       GUJ

Team performance (total Player Successful Tackles):
team_name
PUN     252
GUJ     242
PAT     226
HAR     206
HYD     191
BLR     185
CHE     184
U.P.    183
KOL     181
MUM     176
JAI     162
DEL     159
Name: value, dtype: int64

Position-wise analysis:
                sum       mean  count
position_name
All Rounder     570  18.387097     31
Defender       1502  22.088235     68
Raider          275   5.392157     51

Correlation between matches played and Player Successful Tackles: 0.59

==================================================

Stopped after 15 clicks
Exported 5_df_season5_player-tackle-points.csv

Statistic: Player Tackle Points
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         150 non-null    int64
 1   player_name       150 non-null    object
 2   match_played      150 non-null    int64
 3   value             150 non-null    int64
 4   team_id           150 non-null    int64
 5   team              0 non-null      object
 6   team_name         150 non-null    object
 7   rank              150 non-null    object
 8   position_id       150 non-null    int64
 9   position_name     150 non-null    object
 10  team_full_name    150 non-null    object
 11  points_per_match  150 non-null    float64
dtypes: float64(1), int64(5), object(6)
memory usage: 14.2+ KB
None
   player_id      player_name  match_played  value  team_id  team team_name  \
0        146    Surender Nada            21     80       28  None       HAR
1        322    Surjeet Singh            24     76        4  None       KOL
2        579          Jaideep            26     71        6  None       PAT
3       3083  Vishal Bhardwaj            22     71        8  None       HYD
4        489   Abozar Mighani            24     65       31  None       GUJ

  rank  position_id position_name    team_full_name  points_per_match
0    1            9      Defender  Haryana Steelers          3.809524
1    2            9      Defender   Bengal Warriors          3.166667
2    3            9      Defender     Patna Pirates          2.730769
3    4            0   All Rounder     Telugu Titans          3.227273
4    5            9      Defender    Gujarat Giants          2.708333
         player_id  match_played       value     team_id  position_id  \
count   150.000000    150.000000  150.000000  150.000000   150.000000
mean    627.473333     14.553333   16.993333   13.780000     6.800000
std     881.099166      7.043048   18.757548   12.228732     3.510292
min      26.000000      1.000000    1.000000    1.000000     0.000000
25%     151.250000      8.250000    3.000000    4.000000     8.000000
50%     290.000000     16.000000    9.000000    7.000000     8.000000
75%     711.500000     21.000000   24.000000   29.000000     9.000000
max    3159.000000     26.000000   80.000000   31.000000     9.000000

       points_per_match
count        150.000000
mean           1.050168
std            0.830096
min            0.041667
25%            0.375000
50%            0.837719
75%            1.500000
max            3.809524

Top 10 players by Player Tackle Points:
            player_name  value team_name
0         Surender Nada     80       HAR
1         Surjeet Singh     76       KOL
2               Jaideep     71       PAT
3       Vishal Bhardwaj     71       HYD
4        Abozar Mighani     65       GUJ
5   Girish Maruti Ernak     64       PUN
6            Amit Hooda     61       CHE
7        Surinder Singh     58       MUM
10       Mahender Singh     57       BLR
9           Sunil Kumar     57       GUJ

Team performance (total Player Tackle Points):
team_name
PUN     271
GUJ     254
PAT     252
HAR     227
HYD     207
MUM     202
BLR     201
CHE     201
U.P.    201
KOL     193
JAI     171
DEL     169
Name: value, dtype: int64

Position-wise analysis:
                sum       mean  count
position_name
All Rounder     621  20.032258     31
Defender       1612  23.705882     68
Raider          316   6.196078     51

Correlation between matches played and Player Tackle Points: 0.60

==================================================

Stopped after 12 clicks
Exported 6_df_season5_player-raid-points.csv

Statistic: Player Raid Points
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         122 non-null    int64
 1   player_name       122 non-null    object
 2   match_played      122 non-null    int64
 3   value             122 non-null    int64
 4   team_id           122 non-null    int64
 5   team              0 non-null      object
 6   team_name         122 non-null    object
 7   rank              122 non-null    object
 8   position_id       122 non-null    int64
 9   position_name     122 non-null    object
 10  team_full_name    122 non-null    object
 11  points_per_match  122 non-null    float64
dtypes: float64(1), int64(5), object(6)
memory usage: 11.6+ KB
None
   player_id     player_name  match_played  value  team_id  team team_name  \
0        197  Pardeep Narwal            26    369        6  None       PAT
1        326     Rohit Kumar            22    219        1  None       BLR
2         26     Ajay Thakur            22    213       29  None       CHE
3        388      Monu Goyat            26    191        6  None       PAT
4        143  Maninder Singh            21    190        4  None       KOL

  rank  position_id position_name   team_full_name  points_per_match
0    1            8        Raider    Patna Pirates         14.192308
1    2            8        Raider  Bengaluru Bulls          9.954545
2    3            8        Raider  Tamil Thalaivas          9.681818
3    4            8        Raider    Patna Pirates          7.346154

### season 4

In [8]:
import pandas as pd
import json
import re
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.firefox.options import Options
from bs4 import BeautifulSoup
import time


import requests
import csv
from bs4 import BeautifulSoup
from selenium  import webdriver
import pandas as pd
import numpy as np
from selenium.webdriver.common.by import By
import os


d={"s-10": "44", 
   "s-9": "25", 
   "s-8": "20",
   "s-7": "11",
   "s-6": "10",
   "s-5": "8",
   "s-4": "4",
   "s-3": "3",
   "s-2": "2",
   "s-1": "1",
   "s-all":"0" ,
   
   }


def extract_json_from_script(script_content):
    start = script_content.find('window.statsWidgetData = ')
    if start == -1:
        return None
    start += len('window.statsWidgetData = ')
    
    bracket_count = 0
    end = start
    for i, char in enumerate(script_content[start:]):
        if char == '{':
            bracket_count += 1
        elif char == '}':
            bracket_count -= 1
            if bracket_count == 0:
                end = start + i + 1
                break
    
    if bracket_count != 0:
        return None
    
    json_str = script_content[start:end]
    
    try:
        return json.loads(json_str)
    except json.JSONDecodeError:
        return None

def fetch_and_process_data(url):
    options = webdriver.FirefoxOptions()
    options.add_argument("--headless")
    driver = webdriver.Firefox(options=options)
    
    try:
        driver.get(url)
        
        for i in range(21):
            try:
                element = WebDriverWait(driver, 10).until(
                    EC.presence_of_element_located((By.CLASS_NAME, 'loadmore'))
                )
                driver.execute_script("arguments[0].click();", element)
                time.sleep(1)
            except:
                print(f"Stopped after {i} clicks")
                break
        
        soup = BeautifulSoup(driver.page_source, 'html.parser')
        script_tag = soup.find('script', string=lambda text: text and 'window.statsWidgetData' in text)
        
        if script_tag:
            json_data = extract_json_from_script(script_tag.string)
            if json_data:
                player_data = json_data['stats']['data']
                df = pd.DataFrame(player_data)
                
                df['value'] = pd.to_numeric(df['value'])
                df['match_played'] = pd.to_numeric(df['match_played'])
                
                df['points_per_match'] = df['value'] / df['match_played']
                
                return df, json_data['stats']['stat']
    
    finally:
        driver.quit()
    
    return None, None

urls = [
    f"https://www.prokabaddi.com/stats/{d['s-4']}-102-total-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-4']}-21-successful-raids-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-4']}-22-raid-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-4']}-23-successful-tackles-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-4']}-103-tackle-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-4']}-22-avg-raid-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-4']}-139-avg-tackle-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-4']}-132-do-or-die-raid-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-4']}-104-super-raids-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-4']}-28-super-tackles-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-4']}-100-super-10s-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-4']}-101-high-5s-statistics"
]   

x = 0
for url in urls:
    x+=1
    df, stat_name = fetch_and_process_data(url)
    if df is not None:
        # Create a file name based on the statistic
        file_name = f"{x}_df_season4_{stat_name.lower().replace(' ', '-')}.csv"
        
        # Export the DataFrame to CSV
        df.to_csv(file_name, index=False)
        print(f"Exported {file_name}")
        
        # Display basic information about the DataFrame
        print(f"\nStatistic: {stat_name}")
        print(df.info())
        
        # Display the first few rows
        print(df.head())
        
        # Basic statistics
        print(df.describe())
        
        # Top 10 players by the statistic
        top_10_players = df.sort_values('value', ascending=False).head(10)
        print(f"\nTop 10 players by {stat_name}:")
        print(top_10_players[['player_name', 'value', 'team_name']])
        
        # Team performance
        team_performance = df.groupby('team_name')['value'].sum().sort_values(ascending=False)
        print(f"\nTeam performance (total {stat_name}):")
        print(team_performance)
        
        # Position-wise analysis
        position_analysis = df.groupby('position_name')['value'].agg(['sum', 'mean', 'count'])
        print("\nPosition-wise analysis:")
        print(position_analysis)
        
        # Correlation between matches played and the statistic
        correlation = df['match_played'].corr(df['value'])
        print(f"\nCorrelation between matches played and {stat_name}: {correlation:.2f}")
        
        print("\n" + "="*50 + "\n")
    else:
        print(f"Failed to fetch or process data from {url}")

Stopped after 10 clicks
Exported 1_df_season4_player-total-points.csv

Statistic: Player Total Points
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         104 non-null    int64
 1   player_name       104 non-null    object
 2   match_played      104 non-null    int64
 3   value             104 non-null    int64
 4   team_id           104 non-null    int64
 5   team              0 non-null      object
 6   team_name         104 non-null    object
 7   rank              104 non-null    object
 8   position_id       104 non-null    int64
 9   position_name     104 non-null    object
 10  team_full_name    104 non-null    object
 11  points_per_match  104 non-null    float64
dtypes: float64(1), int64(5), object(6)
memory usage: 9.9+ KB
None
   player_id         player_name  match_played  value  team_id  team  \
0         81     Rahul Chaudhari            16    150        8  None
1        197      Pardeep Narwal            16    133        6  None
2         41  Deepak Niwas Hooda            16    130        7  None
3        326         Rohit Kumar            14    100        1  None
4         58     Kashiling Adake            13     89        2  None

  team_name rank  position_id position_name     team_full_name  \
0       HYD    1            8        Raider      Telugu Titans
1       PAT    2            8        Raider      Patna Pirates
2       PUN    3            0   All Rounder      Puneri Paltan
3       BLR    4            8        Raider    Bengaluru Bulls
4       DEL    5            8        Raider  Dabang Delhi K.C.

   points_per_match
0          9.375000
1          8.312500
2          8.125000
3          7.142857
4          6.846154
         player_id  match_played       value     team_id  position_id  \
count   104.000000    104.000000  104.000000  104.000000   104.000000
mean    280.048077      9.769231   29.471154    4.403846     6.653846
std     499.594717      4.663910   30.952816    2.333876     3.491374
min      12.000000      1.000000    1.000000    1.000000     0.000000
25%     103.000000      6.000000    7.000000    2.000000     8.000000
50%     187.500000     11.000000   19.000000    4.000000     8.000000
75%     300.250000     14.000000   41.250000    6.000000     9.000000
max    3104.000000     16.000000  150.000000    8.000000     9.000000

       points_per_match
count        104.000000
mean           2.519177
std            1.899934
min            0.222222
25%            1.086039
50%            2.087121
75%            3.265625
max            9.375000

Top 10 players by Player Total Points:
          player_name  value team_name
0     Rahul Chaudhari    150       HYD
1      Pardeep Narwal    133       PAT
2  Deepak Niwas Hooda    130       PUN
3         Rohit Kumar    100       BLR
4     Kashiling Adake     89       DEL
5        Jasvir Singh     88       JAI
6       Rajesh Narwal     85       JAI
7          Anup Kumar     82       MUM
8        Meraj Sheykh     75       DEL
9        Rakesh Kumar     70       MUM

Team performance (total Player Total Points):
team_name
PUN    436
PAT    435
HYD    429
JAI    405
DEL    360
MUM    348
KOL    327
BLR    325
Name: value, dtype: int64

Position-wise analysis:
                sum       mean  count
position_name
All Rounder     675  30.681818     22
Defender        773  21.472222     36
Raider         1617  35.152174     46

Correlation between matches played and Player Total Points: 0.72

==================================================

Stopped after 6 clicks
Exported 2_df_season4_player-successful-raids.csv

Statistic: Player Successful Raids
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67 entries, 0 to 66
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         67 non-null     int64
 1   player_name       67 non-null     object
 2   match_played      67 non-null     int64
 3   value             67 non-null     int64
 4   team_id           67 non-null     int64
 5   team              0 non-null      object
 6   team_name         67 non-null     object
 7   rank              67 non-null     object
 8   position_id       67 non-null     int64
 9   position_name     67 non-null     object
 10  team_full_name    67 non-null     object
 11  points_per_match  67 non-null     float64
dtypes: float64(1), int64(5), object(6)
memory usage: 6.4+ KB
None
   player_id         player_name  match_played  value  team_id  team  \
0         81     Rahul Chaudhari            16    110        8  None
1         41  Deepak Niwas Hooda            16    108        7  None
2        197      Pardeep Narwal            16    100        6  None
3        326         Rohit Kumar            14     75        1  None
4         52        Jasvir Singh            14     64        3  None

  team_name rank  position_id position_name        team_full_name  \
0       HYD    1            8        Raider         Telugu Titans
1       PUN    2            0   All Rounder         Puneri Paltan
2       PAT    3            8        Raider         Patna Pirates
3       BLR    4            8        Raider       Bengaluru Bulls
4       JAI    5            8        Raider  Jaipur Pink Panthers

   points_per_match
0          6.875000
1          6.750000
2          6.250000
3          5.357143
4          4.571429
         player_id  match_played       value    team_id  position_id  \
count    67.000000     67.000000   67.000000  67.000000    67.000000
mean    319.895522      9.985075   22.671642   4.283582     6.447761
std     615.843229      4.733800   26.764058   2.353630     3.354254
min      12.000000      1.000000    1.000000   1.000000     0.000000
25%      87.000000      6.000000    4.000000   2.000000     8.000000
50%     174.000000     11.000000   10.000000   4.000000     8.000000
75%     309.000000     14.000000   40.500000   6.000000     8.000000
max    3104.000000     16.000000  110.000000   8.000000     9.000000

       points_per_match
count         67.000000
mean           1.938554
std            1.650218
min            0.071429
25%            0.708333
50%            1.363636
75%            2.778571
max            6.875000

Top 10 players by Player Successful Raids:
          player_name  value team_name
0     Rahul Chaudhari    110       HYD
1  Deepak Niwas Hooda    108       PUN
2      Pardeep Narwal    100       PAT
3         Rohit Kumar     75       BLR
4        Jasvir Singh     64       JAI
5          Anup Kumar     60       MUM
6     Kashiling Adake     58       DEL
7    Rishank Devadiga     57       MUM
8       Rajesh Narwal     52       JAI
9          Monu Goyat     52       KOL

Team performance (total Player Successful Raids):
team_name
PUN    230
HYD    206
PAT    206
JAI    203
MUM    188
KOL    167
DEL    162
BLR    157
Name: value, dtype: int64

Position-wise analysis:
                sum       mean  count
position_name
All Rounder     309  22.071429     14
Defender         23   2.875000      8
Raider         1187  26.377778     45

Correlation between matches played and Player Successful Raids: 0.60

==================================================

Stopped after 8 clicks
Exported 3_df_season4_player-raid-points.csv

Statistic: Player Raid Points
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         71 non-null     int64
 1   player_name       71 non-null     object
 2   match_played      71 non-null     int64
 3   value             71 non-null     int64
 4   team_id           71 non-null     int64
 5   team              0 non-null      object
 6   team_name         71 non-null     object
 7   rank              71 non-null     object
 8   position_id       71 non-null     int64
 9   position_name     71 non-null     object
 10  team_full_name    71 non-null     object
 11  points_per_match  71 non-null     float64
dtypes: float64(1), int64(5), object(6)
memory usage: 6.8+ KB
None
   player_id         player_name  match_played  value  team_id  team  \
0         81     Rahul Chaudhari            16    146        8  None
1        197      Pardeep Narwal            16    131        6  None
2         41  Deepak Niwas Hooda            16    126        7  None
3        326         Rohit Kumar            14     93        1  None
4         52        Jasvir Singh            14     82        3  None

  team_name rank  position_id position_name        team_full_name  \
0       HYD    1            8        Raider         Telugu Titans
1       PAT    2            8        Raider         Patna Pirates
2       PUN    3            0   All Rounder         Puneri Paltan
3       BLR    4            8        Raider       Bengaluru Bulls
4       JAI    5            8        Raider  Jaipur Pink Panthers

   points_per_match
0          9.125000
1          8.187500
2          7.875000
3          6.642857
4          5.857143
         player_id  match_played       value    team_id  position_id  \
count    71.000000     71.000000   71.000000  71.000000    71.000000
mean    314.239437      9.929577   27.422535   4.323944     6.450704
std     598.457170      4.739873   33.504227   2.310069     3.379724
min      12.000000      1.000000    1.000000   1.000000     0.000000
25%      90.000000      6.000000    4.000000   2.000000     8.000000
50%     194.000000     11.000000   13.000000   4.000000     8.000000
75%     296.500000     14.000000   44.500000   6.000000     8.000000
max    3104.000000     16.000000  146.000000   8.000000     9.000000

       points_per_match
count         71.000000
mean           2.333156
std            2.088742
min            0.100000
25%            0.797980
50%            1.818182
75%            3.380769
max            9.125000

Top 10 players by Player Raid Points:
          player_name  value team_name
0     Rahul Chaudhari    146       HYD
1      Pardeep Narwal    131       PAT
2  Deepak Niwas Hooda    126       PUN
3         Rohit Kumar     93       BLR
4        Jasvir Singh     82       JAI
5     Kashiling Adake     78       DEL
6          Anup Kumar     72       MUM
7    Rishank Devadiga     70       MUM
8       Rajesh Narwal     66       JAI
9         Ajay Thakur     63       PUN

Team performance (total Player Raid Points):
team_name
PUN    290
JAI    270
HYD    267
PAT    264
MUM    227
DEL    226
KOL    202
BLR    201
Name: value, dtype: int64

Position-wise analysis:
                sum       mean  count
position_name
All Rounder     387  25.800000     15
Defender         34   3.400000     10
Raider         1526  33.173913     46

Correlation between matches played and Player Raid Points: 0.59

==================================================

Stopped after 8 clicks
Exported 4_df_season4_player-successful-tackles.csv

Statistic: Player Successful Tackles
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         80 non-null     int64
 1   player_name       80 non-null     object
 2   match_played      80 non-null     int64
 3   value             80 non-null     int64
 4   team_id           80 non-null     int64
 5   team              0 non-null      object
 6   team_name         80 non-null     object
 7   rank              80 non-null     object
 8   position_id       80 non-null     int64
 9   position_name     80 non-null     object
 10  team_full_name    80 non-null     object
 11  points_per_match  80 non-null     float64
dtypes: float64(1), int64(5), object(6)
memory usage: 7.6+ KB
None
   player_id       player_name  match_played  value  team_id  team team_name  \
0        212        Amit Hooda            16     47        3  None       JAI
1        259   Fazel Atrachali            16     45        6  None       PAT
2         71    Mohit Chhillar            14     44        1  None       BLR
3         69  Manjeet Chhillar            12     43        7  None       PUN
4        142    Sandeep Narwal            16     40        8  None       HYD

  rank  position_id position_name        team_full_name  points_per_match
0    1            9      Defender  Jaipur Pink Panthers          2.937500
1    2            9      Defender         Patna Pirates          2.812500
2    3            9      Defender       Bengaluru Bulls          3.142857
3    4            0   All Rounder         Puneri Paltan          3.583333
4    5            0   All Rounder         Telugu Titans          2.500000
         player_id  match_played      value    team_id  position_id  \
count    80.000000     80.000000  80.000000  80.000000    80.000000
mean    291.875000     10.712500  12.662500   4.350000     6.437500
std     566.397172      4.395607  13.443688   2.355172     3.764739
min      12.000000      1.000000   1.000000   1.000000     0.000000
25%      94.000000      8.000000   2.000000   2.000000     6.000000
50%     166.000000     12.000000   6.000000   4.000000     8.000000
75%     276.000000     14.000000  21.500000   6.000000     9.000000
max    3104.000000     16.000000  47.000000   8.000000     9.000000

       points_per_match
count         80.000000
mean           1.093308
std            0.932953
min            0.062500
25%            0.267045
50%            0.900000
75%            1.694196
max            3.583333

Top 10 players by Player Successful Tackles:
             player_name  value team_name
0             Amit Hooda     47       JAI
1        Fazel Atrachali     45       PAT
2         Mohit Chhillar     44       BLR
3       Manjeet Chhillar     43       PUN
4         Sandeep Narwal     40       HYD
5        Sachin Shingade     39       DEL
6    Sandeep Kumar Dhull     35       HYD
7         Ravinder Pahal     35       PUN
8          Surjeet Singh     33       MUM
9  Joginder Singh Narwal     32       PUN

Team performance (total Player Successful Tackles):
team_name
HYD    157
PAT    145
PUN    140
JAI    119
KOL    117
DEL    116
MUM    110
BLR    109
Name: value, dtype: int64

Position-wise analysis:
               sum       mean  count
position_name
All Rounder    264  13.200000     20
Defender       676  19.314286     35
Raider          73   2.920000     25

Correlation between matches played and Player Successful Tackles: 0.53

==================================================

Stopped after 8 clicks
Exported 5_df_season4_player-tackle-points.csv

Statistic: Player Tackle Points
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80 entries, 0 to 79
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         80 non-null     int64
 1   player_name       80 non-null     object
 2   match_played      80 non-null     int64
 3   value             80 non-null     int64
 4   team_id           80 non-null     int64
 5   team              0 non-null      object
 6   team_name         80 non-null     object
 7   rank              80 non-null     object
 8   position_id       80 non-null     int64
 9   position_name     80 non-null     object
 10  team_full_name    80 non-null     object
 11  points_per_match  80 non-null     float64
dtypes: float64(1), int64(5), object(6)
memory usage: 7.6+ KB
None
   player_id       player_name  match_played  value  team_id  team team_name  \
0        259   Fazel Atrachali            16     52        6  None       PAT
1        212        Amit Hooda            16     51        3  None       JAI
2         71    Mohit Chhillar            14     47        1  None       BLR
3         69  Manjeet Chhillar            12     44        7  None       PUN
4        165   Sachin Shingade            14     44        2  None       DEL

  rank  position_id position_name        team_full_name  points_per_match
0    1            9      Defender         Patna Pirates          3.250000
1    2            9      Defender  Jaipur Pink Panthers          3.187500
2    3            9      Defender       Bengaluru Bulls          3.357143
3    4            0   All Rounder         Puneri Paltan          3.666667
4    5            9      Defender     Dabang Delhi K.C.          3.142857
         player_id  match_played     value    team_id  position_id  \
count    80.000000     80.000000  80.00000  80.000000    80.000000
mean    291.875000     10.712500  13.97500   4.350000     6.437500
std     566.397172      4.395607  14.57497   2.355172     3.764739
min      12.000000      1.000000   1.00000   1.000000     0.000000
25%      94.000000      8.000000   2.00000   2.000000     6.000000
50%     166.000000     12.000000   7.00000   4.000000     8.000000
75%     276.000000     14.000000  23.50000   6.000000     9.000000
max    3104.000000     16.000000  52.00000   8.000000     9.000000

       points_per_match
count         80.000000
mean           1.204254
std            1.000243
min            0.062500
25%            0.356061
50%            0.958333
75%            1.857143
max            3.666667

Top 10 players by Player Tackle Points:
             player_name  value team_name
0        Fazel Atrachali     52       PAT
1             Amit Hooda     51       JAI
2         Mohit Chhillar     47       BLR
3       Manjeet Chhillar     44       PUN
4        Sachin Shingade     44       DEL
5         Sandeep Narwal     42       HYD
6  Dharmaraj Cheralathan     39       PAT
7         Ravinder Pahal     37       PUN
8          Surjeet Singh     37       MUM
9    Sandeep Kumar Dhull     35       HYD

Team performance (total Player Tackle Points):
team_name
PAT    171
HYD    162
PUN    146
JAI    135
DEL    134
KOL    125
BLR    124
MUM    121
Name: value, dtype: int64

Position-wise analysis:
               sum       mean  count
position_name
All Rounder    288  14.400000     20
Defender       739  21.114286     35
Raider          91   3.640000     25

Correlation between matches played and Player Tackle Points: 0.54

==================================================

Stopped after 7 clicks
Exported 6_df_season4_player-raid-points.csv

Statistic: Player Raid Points
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         71 non-null     int64
 1   player_name       71 non-null     object
 2   match_played      71 non-null     int64
 3   value             71 non-null     int64
 4   team_id           71 non-null     int64
 5   team              0 non-null      object
 6   team_name         71 non-null     object
 7   rank              71 non-null     object
 8   position_id       71 non-null     int64
 9   position_name     71 non-null     object
 10  team_full_name    71 non-null     object
 11  points_per_match  71 non-null     float64
dtypes: float64(1), int64(5), object(6)
memory usage: 6.8+ KB
None
   player_id         player_name  match_played  value  team_id  team  \
0         81     Rahul Chaudhari            16    146        8  None
1        197      Pardeep Narwal            16    131        6  None
2         41  Deepak Niwas Hooda            16    126        7  None
3        326         Rohit Kumar            14     93        1  None
4         52        Jasvir Singh            14     82        3  None

  team_name rank  position_id position_name        team_full_name  \
0       HYD    1            8        Raider         Telugu Titans
1       PAT    2            8        Raider         Patna Pirates
2       PUN    3            0   All Rounder         Puneri Paltan
3       BLR    4            8        Raider       Bengaluru Bulls
4       JAI    5            8        Raider  Jaipur Pink Panthers

   points_per_match
0          9.125000
1          8.187500

### season 3

In [9]:
import pandas as pd
import json
import re
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.firefox.options import Options
from bs4 import BeautifulSoup
import time


import requests
import csv
from bs4 import BeautifulSoup
from selenium  import webdriver
import pandas as pd
import numpy as np
from selenium.webdriver.common.by import By
import os


d={"s-10": "44", 
   "s-9": "25", 
   "s-8": "20",
   "s-7": "11",
   "s-6": "10",
   "s-5": "8",
   "s-4": "4",
   "s-3": "3",
   "s-2": "2",
   "s-1": "1",
   "s-all":"0" ,
   
   }


def extract_json_from_script(script_content):
    start = script_content.find('window.statsWidgetData = ')
    if start == -1:
        return None
    start += len('window.statsWidgetData = ')
    
    bracket_count = 0
    end = start
    for i, char in enumerate(script_content[start:]):
        if char == '{':
            bracket_count += 1
        elif char == '}':
            bracket_count -= 1
            if bracket_count == 0:
                end = start + i + 1
                break
    
    if bracket_count != 0:
        return None
    
    json_str = script_content[start:end]
    
    try:
        return json.loads(json_str)
    except json.JSONDecodeError:
        return None

def fetch_and_process_data(url):
    options = webdriver.FirefoxOptions()
    options.add_argument("--headless")
    driver = webdriver.Firefox(options=options)
    
    try:
        driver.get(url)
        
        for i in range(21):
            try:
                element = WebDriverWait(driver, 10).until(
                    EC.presence_of_element_located((By.CLASS_NAME, 'loadmore'))
                )
                driver.execute_script("arguments[0].click();", element)
                time.sleep(1)
            except:
                print(f"Stopped after {i} clicks")
                break
        
        soup = BeautifulSoup(driver.page_source, 'html.parser')
        script_tag = soup.find('script', string=lambda text: text and 'window.statsWidgetData' in text)
        
        if script_tag:
            json_data = extract_json_from_script(script_tag.string)
            if json_data:
                player_data = json_data['stats']['data']
                df = pd.DataFrame(player_data)
                
                df['value'] = pd.to_numeric(df['value'])
                df['match_played'] = pd.to_numeric(df['match_played'])
                
                df['points_per_match'] = df['value'] / df['match_played']
                
                return df, json_data['stats']['stat']
    
    finally:
        driver.quit()
    
    return None, None

urls = [
    f"https://www.prokabaddi.com/stats/{d['s-3']}-102-total-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-3']}-21-successful-raids-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-3']}-22-raid-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-3']}-23-successful-tackles-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-3']}-103-tackle-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-3']}-22-avg-raid-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-3']}-139-avg-tackle-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-3']}-132-do-or-die-raid-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-3']}-104-super-raids-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-3']}-28-super-tackles-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-3']}-100-super-10s-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-3']}-101-high-5s-statistics"
]   

x = 0
for url in urls:
    x+=1
    df, stat_name = fetch_and_process_data(url)
    if df is not None:
        # Create a file name based on the statistic
        file_name = f"{x}_df_season3_{stat_name.lower().replace(' ', '-')}.csv"
        
        # Export the DataFrame to CSV
        df.to_csv(file_name, index=False)
        print(f"Exported {file_name}")
        
        # Display basic information about the DataFrame
        print(f"\nStatistic: {stat_name}")
        print(df.info())
        
        # Display the first few rows
        print(df.head())
        
        # Basic statistics
        print(df.describe())
        
        # Top 10 players by the statistic
        top_10_players = df.sort_values('value', ascending=False).head(10)
        print(f"\nTop 10 players by {stat_name}:")
        print(top_10_players[['player_name', 'value', 'team_name']])
        
        # Team performance
        team_performance = df.groupby('team_name')['value'].sum().sort_values(ascending=False)
        print(f"\nTeam performance (total {stat_name}):")
        print(team_performance)
        
        # Position-wise analysis
        position_analysis = df.groupby('position_name')['value'].agg(['sum', 'mean', 'count'])
        print("\nPosition-wise analysis:")
        print(position_analysis)
        
        # Correlation between matches played and the statistic
        correlation = df['match_played'].corr(df['value'])
        print(f"\nCorrelation between matches played and {stat_name}: {correlation:.2f}")
        
        print("\n" + "="*50 + "\n")
    else:
        print(f"Failed to fetch or process data from {url}")

Stopped after 12 clicks
Exported 1_df_season3_player-total-points.csv

Statistic: Player Total Points
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         122 non-null    int64
 1   player_name       122 non-null    object
 2   match_played      122 non-null    int64
 3   value             122 non-null    int64
 4   team_id           122 non-null    int64
 5   team              0 non-null      object
 6   team_name         122 non-null    object
 7   rank              122 non-null    object
 8   position_id       122 non-null    int64
 9   position_name     122 non-null    object
 10  team_full_name    122 non-null    object
 11  points_per_match  122 non-null    float64
dtypes: float64(1), int64(5), object(6)
memory usage: 11.6+ KB
None
   player_id       player_name  match_played  value  team_id  team team_name  \
0        197    Pardeep Narwal            16    121        6  None       PAT
1         94  Rishank Devadiga            16    115        5  None       MUM
2        326       Rohit Kumar            12    109        6  None       PAT
3         69  Manjeet Chhillar            15    106        7  None       PUN
4         81   Rahul Chaudhari            13     99        8  None       HYD

  rank  position_id position_name team_full_name  points_per_match
0    1            8        Raider  Patna Pirates          7.562500
1    2            8        Raider        U Mumba          7.187500
2    3            8        Raider  Patna Pirates          9.083333
3    4            0   All Rounder  Puneri Paltan          7.066667
4    5            8        Raider  Telugu Titans          7.615385
        player_id  match_played       value     team_id  position_id  \
count  122.000000    122.000000  122.000000  122.000000   122.000000
mean   175.516393      8.540984   25.401639    4.377049     7.098361
std     93.638944      4.558432   27.800844    2.275736     3.189367
min     10.000000      1.000000    1.000000    1.000000     0.000000
25%     87.250000      4.000000    4.250000    2.000000     8.000000
50%    172.500000      9.000000   16.000000    4.000000     8.000000
75%    257.250000     12.000000   36.000000    6.000000     9.000000
max    326.000000     16.000000  121.000000    8.000000     9.000000

       points_per_match
count        122.000000
mean           2.460949
std            1.966015
min            0.142857
25%            1.000000
50%            1.854545
75%            3.237500
max            9.083333

Top 10 players by Player Total Points:
        player_name  value team_name
0    Pardeep Narwal    121       PAT
1  Rishank Devadiga    115       MUM
2       Rohit Kumar    109       PAT
3  Manjeet Chhillar    106       PUN
4   Rahul Chaudhari     99       HYD
5      Jang Kun Lee     90       KOL
6       Nitin Tomar     81       KOL
7     Rajesh Narwal     80       JAI
8        Anup Kumar     79       MUM
9   Kashiling Adake     78       DEL

Team performance (total Player Total Points):
team_name
PAT    506
PUN    438
MUM    422
KOL    400
HYD    370
DEL    344
BLR    310
JAI    309
Name: value, dtype: int64

Position-wise analysis:
                sum   mean  count
position_name
All Rounder     673  33.65     20
Defender        723  14.46     50
Raider         1703  32.75     52

Correlation between matches played and Player Total Points: 0.70

==================================================

Stopped after 8 clicks
Exported 2_df_season3_player-successful-raids.csv

Statistic: Player Successful Raids
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         78 non-null     int64
 1   player_name       78 non-null     object
 2   match_played      78 non-null     int64
 3   value             78 non-null     int64
 4   team_id           78 non-null     int64
 5   team              0 non-null      object
 6   team_name         78 non-null     object
 7   rank              78 non-null     object
 8   position_id       78 non-null     int64
 9   position_name     78 non-null     object
 10  team_full_name    78 non-null     object
 11  points_per_match  78 non-null     float64
dtypes: float64(1), int64(5), object(6)
memory usage: 7.4+ KB
None
   player_id       player_name  match_played  value  team_id  team team_name  \
0         94  Rishank Devadiga            16     86        5  None       MUM
1        197    Pardeep Narwal            16     83        6  None       PAT
2        326       Rohit Kumar            12     80        6  None       PAT
3         81   Rahul Chaudhari            13     77        8  None       HYD
4        320       Nitin Tomar            10     68        4  None       KOL

  rank  position_id position_name   team_full_name  points_per_match
0    1            8        Raider          U Mumba          5.375000
1    2            8        Raider    Patna Pirates          5.187500
2    3            8        Raider    Patna Pirates          6.666667
3    4            8        Raider    Telugu Titans          5.923077
4    5            8        Raider  Bengal Warriors          6.800000
        player_id  match_played      value    team_id  position_id  \
count   78.000000     78.000000  78.000000  78.000000    78.000000
mean   169.769231      9.358974  19.833333   4.320513     6.525641
std     96.288517      4.279138  23.271641   2.299032     3.356422
min     10.000000      1.000000   1.000000   1.000000     0.000000
25%     85.250000      6.000000   3.000000   2.000000     8.000000
50%    169.500000     10.000000   8.500000   4.000000     8.000000
75%    251.750000     13.000000  29.000000   6.000000     8.000000
max    326.000000     16.000000  86.000000   8.000000     9.000000

       points_per_match
count         78.000000
mean           1.863992
std            1.739185
min            0.066667
25%            0.500000
50%            1.215385
75%            2.733173
max            6.800000

Top 10 players by Player Successful Raids:
          player_name  value team_name
0    Rishank Devadiga     86       MUM
1      Pardeep Narwal     83       PAT
2         Rohit Kumar     80       PAT
3     Rahul Chaudhari     77       HYD
4         Nitin Tomar     68       KOL
5        Jang Kun Lee     64       KOL
6          Anup Kumar     63       MUM
7  Deepak Niwas Hooda     62       PUN
8     Kashiling Adake     55       DEL
9       Surjeet Singh     54       DEL

Team performance (total Player Successful Raids):
team_name
PAT    241
KOL    213
HYD    206
MUM    206
PUN    203
DEL    171
BLR    158
JAI    149
Name: value, dtype: int64

Position-wise analysis:
                sum       mean  count
position_name
All Rounder     273  17.062500     16
Defender         30   2.307692     13
Raider         1244  25.387755     49

Correlation between matches played and Player Successful Raids: 0.53

==================================================

Stopped after 8 clicks
Exported 3_df_season3_player-raid-points.csv

Statistic: Player Raid Points
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         84 non-null     int64
 1   player_name       84 non-null     object
 2   match_played      84 non-null     int64
 3   value             84 non-null     int64
 4   team_id           84 non-null     int64
 5   team              0 non-null      object
 6   team_name         84 non-null     object
 7   rank              84 non-null     object
 8   position_id       84 non-null     int64
 9   position_name     84 non-null     object
 10  team_full_name    84 non-null     object
 11  points_per_match  84 non-null     float64
dtypes: float64(1), int64(5), object(6)
memory usage: 8.0+ KB
None
   player_id       player_name  match_played  value  team_id  team team_name  \
0        197    Pardeep Narwal            16    116        6  None       PAT
1         94  Rishank Devadiga            16    106        5  None       MUM
2        326       Rohit Kumar            12    102        6  None       PAT
3         81   Rahul Chaudhari            13     87        8  None       HYD
4         12      Jang Kun Lee            15     79        4  None       KOL

  rank  position_id position_name   team_full_name  points_per_match
0    1            8        Raider    Patna Pirates          7.250000
1    2            8        Raider          U Mumba          6.625000
2    3            8        Raider    Patna Pirates          8.500000
3    4            8        Raider    Telugu Titans          6.692308
4    5            8        Raider  Bengal Warriors          5.266667
        player_id  match_played       value    team_id  position_id  \
count   84.000000     84.000000   84.000000  84.000000    84.000000
mean   170.119048      9.428571   23.416667   4.261905     6.702381
std     95.583232      4.186282   28.337131   2.255484     3.295780
min     10.000000      1.000000    1.000000   1.000000     0.000000
25%     85.750000      6.000000    2.000000   2.000000     8.000000
50%    165.000000     10.500000   10.000000   4.000000     8.000000
75%    253.750000     13.000000   34.000000   6.000000     8.000000
max    326.000000     16.000000  116.000000   8.000000     9.000000

       points_per_match
count         84.000000
mean           2.218111
std            2.155868
min            0.066667
25%            0.500000
50%            1.464286
75%            3.448718
max            8.500000

Top 10 players by Player Raid Points:
          player_name  value team_name
0      Pardeep Narwal    116       PAT
1    Rishank Devadiga    106       MUM
2         Rohit Kumar    102       PAT
3     Rahul Chaudhari     87       HYD
4        Jang Kun Lee     79       KOL
5         Nitin Tomar     77       KOL
6          Anup Kumar     76       MUM
7     Kashiling Adake     75       DEL
8  Deepak Niwas Hooda     69       PUN
9       Surjeet Singh     68       DEL

Team performance (total Player Raid Points):
team_name
PAT    324
HYD    254
MUM    253
PUN    251
KOL    250
DEL    233
BLR    209
JAI    193
Name: value, dtype: int64

Position-wise analysis:
                sum       mean  count
position_name
All Rounder     339  21.187500     16
Defender         51   2.684211     19
Raider         1577  32.183673     49

Correlation between matches played and Player Raid Points: 0.50

==================================================

Stopped after 9 clicks
Exported 4_df_season3_player-successful-tackles.csv

Statistic: Player Successful Tackles
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         99 non-null     int64
 1   player_name       99 non-null     object
 2   match_played      99 non-null     int64
 3   value             99 non-null     int64
 4   team_id           99 non-null     int64
 5   team              0 non-null      object
 6   team_name         99 non-null     object
 7   rank              99 non-null     object
 8   position_id       99 non-null     int64
 9   position_name     99 non-null     object
 10  team_full_name    99 non-null     object
 11  points_per_match  99 non-null     float64
dtypes: float64(1), int64(5), object(6)
memory usage: 9.4+ KB
None
   player_id         player_name  match_played  value  team_id  team  \
0         69    Manjeet Chhillar            15     56        7  None
1        142      Sandeep Narwal            14     53        6  None
2        322       Surjeet Singh            12     47        7  None
3         71      Mohit Chhillar            13     44        5  None
4         51  Jasmer Singh Gulia            16     41        7  None

  team_name rank  position_id position_name team_full_name  points_per_match
0       PUN    1            0   All Rounder  Puneri Paltan          3.733333
1       PAT    2            0   All Rounder  Patna Pirates          3.785714
2       PUN    3            9      Defender  Puneri Paltan          3.916667
3       MUM    4            9      Defender        U Mumba          3.384615
4       PUN    5            0   All Rounder  Puneri Paltan          2.562500
        player_id  match_played      value    team_id  position_id  \
count   99.000000     99.000000  99.000000  99.000000    99.000000
mean   176.444444      9.151515  10.525253   4.404040     6.959596
std     95.837365      4.495720  12.414889   2.280884     3.437249
min     12.000000      1.000000   1.000000   1.000000     0.000000
25%     85.500000      5.500000   2.000000   2.000000     8.000000
50%    167.000000     10.000000   5.000000   4.000000     8.000000
75%    262.500000     13.000000  15.000000   6.000000     9.000000
max    326.000000     16.000000  56.000000   8.000000     9.000000

       points_per_match
count         99.000000
mean           1.064535
std            0.919264
min            0.076923
25%            0.354167
50%            0.818182
75%            1.380952
max            3.916667

Top 10 players by Player Successful Tackles:
           player_name  value team_name
0     Manjeet Chhillar     56       PUN
1       Sandeep Narwal     53       PAT
2        Surjeet Singh     47       PUN
3       Mohit Chhillar     44       MUM
4   Jasmer Singh Gulia     41       PUN
5       Bajirao Hodage     36       KOL
6  Girish Maruti Ernak     33       KOL
7      Fazel Atrachali     32       MUM
8          Jeeva Kumar     30       MUM
9        Nilesh Shinde     30       KOL

Team performance (total Player Successful Tackles):
team_name
PAT    175
PUN    174
MUM    163
KOL    137
HYD    101
JAI    100
DEL     98
BLR     94
Name: value, dtype: int64

Position-wise analysis:
               sum       mean  count
position_name
All Rounder    308  16.210526     19
Defender       626  12.775510     49
Raider         108   3.483871     31

Correlation between matches played and Player Successful Tackles: 0.57

==================================================

Stopped after 9 clicks
Exported 5_df_season3_player-tackle-points.csv

Statistic: Player Tackle Points
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         99 non-null     int64
 1   player_name       99 non-null     object
 2   match_played      99 non-null     int64
 3   value             99 non-null     int64
 4   team_id           99 non-null     int64
 5   team              0 non-null      object
 6   team_name         99 non-null     object
 7   rank              99 non-null     object
 8   position_id       99 non-null     int64
 9   position_name     99 non-null     object
 10  team_full_name    99 non-null     object
 11  points_per_match  99 non-null     float64
dtypes: float64(1), int64(5), object(6)
memory usage: 9.4+ KB
None
   player_id         player_name  match_played  value  team_id  team  \
0         69    Manjeet Chhillar            15     61        7  None
1        142      Sandeep Narwal            14     55        6  None
2        322       Surjeet Singh            12     48        7  None
3         71      Mohit Chhillar            13     46        5  None
4         51  Jasmer Singh Gulia            16     46        7  None

  team_name rank  position_id position_name team_full_name  points_per_match
0       PUN    1            0   All Rounder  Puneri Paltan          4.066667
1       PAT    2            0   All Rounder  Patna Pirates          3.928571
2       PUN    3            9      Defender  Puneri Paltan          4.000000
3       MUM    4            9      Defender        U Mumba          3.538462
4       PUN    5            0   All Rounder  Puneri Paltan          2.875000
        player_id  match_played      value    team_id  position_id  \
count   99.000000     99.000000  99.000000  99.000000    99.000000
mean   176.444444      9.151515  11.434343   4.404040     6.959596
std     95.837365      4.495720  13.207266   2.280884     3.437249
min     12.000000      1.000000   1.000000   1.000000     0.000000
25%     85.500000      5.500000   2.000000   2.000000     8.000000
50%    167.000000     10.000000   6.000000   4.000000     8.000000
75%    262.500000     13.000000  17.000000   6.000000     9.000000
max    326.000000     16.000000  61.000000   8.000000     9.000000

       points_per_match
count         99.000000
mean           1.150650
std            0.970792
min            0.076923
25%            0.392308
50%            0.900000
75%            1.522727
max            4.066667

Top 10 players by Player Tackle Points:
           player_name  value team_name
0     Manjeet Chhillar     61       PUN
1       Sandeep Narwal     55       PAT
2        Surjeet Singh     48       PUN
4   Jasmer Singh Gulia     46       PUN
3       Mohit Chhillar     46       MUM
5       Bajirao Hodage     37       KOL
6        Nilesh Shinde     34       KOL
7  Girish Maruti Ernak     33       KOL
8      Fazel Atrachali     32       MUM
9  Sandeep Kumar Dhull     32       DEL

Team performance (total Player Tackle Points):
team_name
PUN    187
PAT    182
MUM    169
KOL    150
HYD    116
JAI    116
DEL    111
BLR    101
Name: value, dtype: int64

Position-wise analysis:
               sum       mean  count
position_name
All Rounder    334  17.578947     19
Defender       672  13.714286     49
Raider         126   4.064516     31

Correlation between matches played and Player Tackle Points: 0.58

==================================================

Stopped after 8 clicks
Exported 6_df_season3_player-raid-points.csv

Statistic: Player Raid Points
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84 entries, 0 to 83
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         84 non-null     int64
 1   player_name       84 non-null     object
 2   match_played      84 non-null     int64
 3   value             84 non-null     int64
 4   team_id           84 non-null     int64
 5   team              0 non-null      object
 6   team_name         84 non-null     object
 7   rank              84 non-null     object
 8   position_id       84 non-null     int64
 9   position_name     84 non-null     object
 10  team_full_name    84 non-null     object
 11  points_per_match  84 non-null     float64
dtypes: float64(1), int64(5), object(6)
memory usage: 8.0+ KB
None
   player_id       player_name  match_played  value  team_id  team team_name  \
0        197    Pardeep Narwal            16    116        6  None       PAT
1         94  Rishank Devadiga            16    106        5  None       MUM
2        326       Rohit Kumar            12    102        6  None       PAT
3         81   Rahul Chaudhari            13     87        8  None       HYD
4         12      Jang Kun Lee            15     79        4  None       KOL

  rank  position_id position_name   team_full_name  points_per_match
0    1            8        Raider    Patna Pirates          7.250000
1    2            8        Raider          U Mumba          6.625000
2    3            8        Raider    Patna Pirates          8.500000
3    4            8        Raider    Telugu Titans          6.692308
4    5            8        Raider  Bengal Warriors          5.266667
        player_id  match_played       value    team_id  position_id  \
count   84.000000     84.000000   84.000000  84.000000    84.000000
mean   170.119048      9.428571   23.416667   4.261905     6.702381
std     95.583232      4.186282   28.337131   2.255484     3.295780
min     10.000000      1.000000    1.000000   1.000000     0.000000

### season 2

In [10]:
import pandas as pd
import json
import re
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.firefox.options import Options
from bs4 import BeautifulSoup
import time


import requests
import csv
from bs4 import BeautifulSoup
from selenium  import webdriver
import pandas as pd
import numpy as np
from selenium.webdriver.common.by import By
import os


d={"s-10": "44", 
   "s-9": "25", 
   "s-8": "20",
   "s-7": "11",
   "s-6": "10",
   "s-5": "8",
   "s-4": "4",
   "s-3": "3",
   "s-2": "2",
   "s-1": "1",
   "s-all":"0" ,
   
   }


def extract_json_from_script(script_content):
    start = script_content.find('window.statsWidgetData = ')
    if start == -1:
        return None
    start += len('window.statsWidgetData = ')
    
    bracket_count = 0
    end = start
    for i, char in enumerate(script_content[start:]):
        if char == '{':
            bracket_count += 1
        elif char == '}':
            bracket_count -= 1
            if bracket_count == 0:
                end = start + i + 1
                break
    
    if bracket_count != 0:
        return None
    
    json_str = script_content[start:end]
    
    try:
        return json.loads(json_str)
    except json.JSONDecodeError:
        return None

def fetch_and_process_data(url):
    options = webdriver.FirefoxOptions()
    options.add_argument("--headless")
    driver = webdriver.Firefox(options=options)
    
    try:
        driver.get(url)
        
        for i in range(21):
            try:
                element = WebDriverWait(driver, 10).until(
                    EC.presence_of_element_located((By.CLASS_NAME, 'loadmore'))
                )
                driver.execute_script("arguments[0].click();", element)
                time.sleep(1)
            except:
                print(f"Stopped after {i} clicks")
                break
        
        soup = BeautifulSoup(driver.page_source, 'html.parser')
        script_tag = soup.find('script', string=lambda text: text and 'window.statsWidgetData' in text)
        
        if script_tag:
            json_data = extract_json_from_script(script_tag.string)
            if json_data:
                player_data = json_data['stats']['data']
                df = pd.DataFrame(player_data)
                
                df['value'] = pd.to_numeric(df['value'])
                df['match_played'] = pd.to_numeric(df['match_played'])
                
                df['points_per_match'] = df['value'] / df['match_played']
                
                return df, json_data['stats']['stat']
    
    finally:
        driver.quit()
    
    return None, None

urls = [
    f"https://www.prokabaddi.com/stats/{d['s-2']}-102-total-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-2']}-21-successful-raids-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-2']}-22-raid-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-2']}-23-successful-tackles-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-2']}-103-tackle-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-2']}-22-avg-raid-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-2']}-139-avg-tackle-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-2']}-132-do-or-die-raid-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-2']}-104-super-raids-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-2']}-28-super-tackles-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-2']}-100-super-10s-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-2']}-101-high-5s-statistics"
]   

x = 0
for url in urls:
    x+=1
    df, stat_name = fetch_and_process_data(url)
    if df is not None:
        # Create a file name based on the statistic
        file_name = f"{x}_df_season2_{stat_name.lower().replace(' ', '-')}.csv"
        
        # Export the DataFrame to CSV
        df.to_csv(file_name, index=False)
        print(f"Exported {file_name}")
        
        # Display basic information about the DataFrame
        print(f"\nStatistic: {stat_name}")
        print(df.info())
        
        # Display the first few rows
        print(df.head())
        
        # Basic statistics
        print(df.describe())
        
        # Top 10 players by the statistic
        top_10_players = df.sort_values('value', ascending=False).head(10)
        print(f"\nTop 10 players by {stat_name}:")
        print(top_10_players[['player_name', 'value', 'team_name']])
        
        # Team performance
        team_performance = df.groupby('team_name')['value'].sum().sort_values(ascending=False)
        print(f"\nTeam performance (total {stat_name}):")
        print(team_performance)
        
        # Position-wise analysis
        position_analysis = df.groupby('position_name')['value'].agg(['sum', 'mean', 'count'])
        print("\nPosition-wise analysis:")
        print(position_analysis)
        
        # Correlation between matches played and the statistic
        correlation = df['match_played'].corr(df['value'])
        print(f"\nCorrelation between matches played and {stat_name}: {correlation:.2f}")
        
        print("\n" + "="*50 + "\n")
    else:
        print(f"Failed to fetch or process data from {url}")

Stopped after 12 clicks
Exported 1_df_season2_player-total-points.csv

Statistic: Player Total Points
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128 entries, 0 to 127
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         128 non-null    int64
 1   player_name       128 non-null    object
 2   match_played      128 non-null    int64
 3   value             128 non-null    int64
 4   team_id           128 non-null    int64
 5   team              0 non-null      object
 6   team_name         128 non-null    object
 7   rank              128 non-null    object
 8   position_id       128 non-null    int64
 9   position_name     128 non-null    object
 10  team_full_name    128 non-null    object
 11  points_per_match  128 non-null    float64
dtypes: float64(1), int64(5), object(6)
memory usage: 12.1+ KB
None
   player_id         player_name  match_played  value  team_id  team  \
0         58     Kashiling Adake            14    117        2  None
1         69    Manjeet Chhillar            16    107        1  None
2         81     Rahul Chaudhari            14    107        8  None
3         41  Deepak Niwas Hooda            15     96        8  None
4         86       Rajesh Narwal            14     87        3  None

  team_name rank  position_id position_name        team_full_name  \
0       DEL    1            8        Raider     Dabang Delhi K.C.
1       BLR    2            0   All Rounder       Bengaluru Bulls
2       HYD    3            8        Raider         Telugu Titans
3       HYD    4            0   All Rounder         Telugu Titans
4       JAI    5            0   All Rounder  Jaipur Pink Panthers

   points_per_match
0          8.357143
1          6.687500
2          7.642857
3          6.400000
4          6.214286
        player_id  match_played       value     team_id  position_id  \
count  128.000000    128.000000  128.000000  128.000000   128.000000
mean   150.390625      8.273438   24.539062    4.671875     6.789062
std     77.119728      4.615474   26.430983    2.348091     3.470125
min     10.000000      1.000000    1.000000    1.000000     0.000000
25%     78.250000      4.000000    5.000000    3.000000     8.000000
50%    163.500000      8.000000   13.000000    5.000000     8.000000
75%    219.500000     13.000000   37.250000    7.000000     9.000000
max    268.000000     16.000000  117.000000    8.000000     9.000000

       points_per_match
count        128.000000
mean           2.432524
std            1.714911
min            0.142857
25%            1.075000
50%            2.000000
75%            3.157143
max            8.357143

Top 10 players by Player Total Points:
          player_name  value team_name
0     Kashiling Adake    117       DEL
2     Rahul Chaudhari    107       HYD
1    Manjeet Chhillar    107       BLR
3  Deepak Niwas Hooda     96       HYD
4       Rajesh Narwal     87       JAI
5      Sandeep Narwal     83       PAT
6          Anup Kumar     81       MUM
7         Ajay Thakur     80       BLR
8        Jasvir Singh     74       JAI
9     Sandeep Kandola     70       HYD

Team performance (total Player Total Points):
team_name
HYD    516
MUM    433
BLR    416
PAT    392
JAI    374
DEL    353
PUN    337
KOL    320
Name: value, dtype: int64

Position-wise analysis:
                sum       mean  count
position_name
All Rounder     714  27.461538     26
Defender        924  17.433962     53
Raider         1503  30.673469     49

Correlation between matches played and Player Total Points: 0.78

==================================================

Stopped after 8 clicks
Exported 2_df_season2_player-successful-raids.csv

Statistic: Player Successful Raids
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83 entries, 0 to 82
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         83 non-null     int64
 1   player_name       83 non-null     object
 2   match_played      83 non-null     int64
 3   value             83 non-null     int64
 4   team_id           83 non-null     int64
 5   team              0 non-null      object
 6   team_name         83 non-null     object
 7   rank              83 non-null     object
 8   position_id       83 non-null     int64
 9   position_name     83 non-null     object
 10  team_full_name    83 non-null     object
 11  points_per_match  83 non-null     float64
dtypes: float64(1), int64(5), object(6)
memory usage: 7.9+ KB
None
   player_id       player_name  match_played  value  team_id  team team_name  \
0         58   Kashiling Adake            14     87        2  None       DEL
1         81   Rahul Chaudhari            14     75        8  None       HYD
2         29        Anup Kumar            14     61        5  None       MUM
3         69  Manjeet Chhillar            16     60        1  None       BLR
4         26       Ajay Thakur            13     56        1  None       BLR

  rank  position_id position_name     team_full_name  points_per_match
0    1            8        Raider  Dabang Delhi K.C.          6.214286
1    2            8        Raider      Telugu Titans          5.357143
2    3            8        Raider            U Mumba          4.357143
3    4            0   All Rounder    Bengaluru Bulls          3.750000
4    5            8        Raider    Bengaluru Bulls          4.307692
        player_id  match_played      value    team_id  position_id  \
count   83.000000     83.000000  83.000000  83.000000    83.000000
mean   149.240964      9.228916  17.759036   4.662651     6.277108
std     79.609809      4.527222  20.079470   2.359605     3.579458
min     10.000000      1.000000   1.000000   1.000000     0.000000
25%     76.000000      5.500000   2.500000   3.000000     8.000000
50%    160.000000     10.000000   9.000000   5.000000     8.000000
75%    221.500000     14.000000  32.000000   7.000000     8.000000
max    268.000000     16.000000  87.000000   8.000000     9.000000

       points_per_match
count         83.000000
mean           1.731504
std            1.439502
min            0.071429
25%            0.500000
50%            1.285714
75%            2.784615
max            6.214286

Top 10 players by Player Successful Raids:
          player_name  value team_name
0     Kashiling Adake     87       DEL
1     Rahul Chaudhari     75       HYD
2          Anup Kumar     61       MUM
3    Manjeet Chhillar     60       BLR
4         Ajay Thakur     56       BLR
5  Deepak Niwas Hooda     54       HYD
6       Rajesh Narwal     54       JAI
7        Jasvir Singh     52       JAI
8         Wazir Singh     48       PUN
9       Deepak Narwal     45       PAT

Team performance (total Player Successful Raids):
team_name
HYD    265
BLR    194
MUM    187
JAI    183
PAT    182
PUN    170
DEL    159
KOL    134
Name: value, dtype: int64

Position-wise analysis:
                sum       mean  count
position_name
All Rounder     354  17.700000     20
Defender         61   3.588235     17
Raider         1059  23.021739     46

Correlation between matches played and Player Successful Raids: 0.59

==================================================

Stopped after 8 clicks
Exported 3_df_season2_player-raid-points.csv

Statistic: Player Raid Points
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88 entries, 0 to 87
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         88 non-null     int64
 1   player_name       88 non-null     object
 2   match_played      88 non-null     int64
 3   value             88 non-null     int64
 4   team_id           88 non-null     int64
 5   team              0 non-null      object
 6   team_name         88 non-null     object
 7   rank              88 non-null     object
 8   position_id       88 non-null     int64
 9   position_name     88 non-null     object
 10  team_full_name    88 non-null     object
 11  points_per_match  88 non-null     float64
dtypes: float64(1), int64(5), object(6)
memory usage: 8.4+ KB
None
   player_id      player_name  match_played  value  team_id  team team_name  \
0         58  Kashiling Adake            14    114        2  None       DEL
1         81  Rahul Chaudhari            14     98        8  None       HYD
2         26      Ajay Thakur            13     79        1  None       BLR
3         29       Anup Kumar            14     74        5  None       MUM
4         86    Rajesh Narwal            14     69        3  None       JAI

  rank  position_id position_name        team_full_name  points_per_match
0    1            8        Raider     Dabang Delhi K.C.          8.142857
1    2            8        Raider         Telugu Titans          7.000000
2    3            8        Raider       Bengaluru Bulls          6.076923
3    4            8        Raider               U Mumba          5.285714
4    5            0   All Rounder  Jaipur Pink Panthers          4.928571
        player_id  match_played       value    team_id  position_id  \
count   88.000000     88.000000   88.000000  88.000000    88.000000
mean   147.045455      9.056818   21.784091   4.659091     6.318182
std     80.378402      4.544437   25.529090   2.372672     3.580103
min     10.000000      1.000000    1.000000   1.000000     0.000000
25%     72.250000      5.000000    3.000000   3.000000     8.000000
50%    158.500000      9.000000   11.500000   5.000000     8.000000
75%    220.250000     13.250000   35.750000   7.000000     8.000000
max    268.000000     16.000000  114.000000   8.000000     9.000000

       points_per_match
count         88.000000
mean           2.125733
std            1.847526
min            0.071429
25%            0.500000
50%            1.633333
75%            3.407143
max            8.142857

Top 10 players by Player Raid Points:
            player_name  value team_name
0       Kashiling Adake    114       DEL
1       Rahul Chaudhari     98       HYD
2           Ajay Thakur     79       BLR
3            Anup Kumar     74       MUM
4         Rajesh Narwal     69       JAI
5      Manjeet Chhillar     67       BLR
6           Wazir Singh     65       PUN
7          Jasvir Singh     64       JAI
8          Sukesh Hegde     62       HYD
9  Rohit Kumar Choudary     61       DEL

Team performance (total Player Raid Points):
team_name
HYD    344
BLR    252
MUM    237
JAI    232
PAT    228
PUN    223
DEL    217
KOL    184
Name: value, dtype: int64

Position-wise analysis:
                sum       mean  count
position_name
All Rounder     436  20.761905     21
Defender         88   4.400000     20
Raider         1393  29.638298     47

Correlation between matches played and Player Raid Points: 0.59

==================================================

Stopped after 10 clicks
Exported 4_df_season2_player-successful-tackles.csv

Statistic: Player Successful Tackles
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107 entries, 0 to 106
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         107 non-null    int64
 1   player_name       107 non-null    object
 2   match_played      107 non-null    int64
 3   value             107 non-null    int64
 4   team_id           107 non-null    int64
 5   team              0 non-null      object
 6   team_name         107 non-null    object
 7   rank              107 non-null    object
 8   position_id       107 non-null    int64
 9   position_name     107 non-null    object
 10  team_full_name    107 non-null    object
 11  points_per_match  107 non-null    float64
dtypes: float64(1), int64(5), object(6)
memory usage: 10.2+ KB
None
   player_id            player_name  match_played  value  team_id  team  \
0        248        Sandeep Kandola            16     55        8  None
1        157         Ravinder Pahal            14     53        2  None
2         42  Dharmaraj Cheralathan            15     41        1  None
3         69       Manjeet Chhillar            16     39        1  None
4         71         Mohit Chhillar            14     39        5  None

  team_name rank  position_id position_name     team_full_name  \
0       HYD    1            9      Defender      Telugu Titans
1       DEL    2            9      Defender  Dabang Delhi K.C.
2       BLR    3            9      Defender    Bengaluru Bulls
3       BLR    4            0   All Rounder    Bengaluru Bulls
4       MUM    5            9      Defender            U Mumba

   points_per_match
0          3.437500
1          3.785714
2          2.733333
3          2.437500
4          2.785714
        player_id  match_played       value     team_id  position_id  \
count  107.000000    107.000000  107.000000  107.000000   107.000000
mean   144.261682      8.906542   10.411215    4.803738     6.841121
std     75.375580      4.583672   12.201108    2.320700     3.523906
min     12.000000      1.000000    1.000000    1.000000     0.000000
25%     74.500000      5.000000    2.000000    3.000000     8.000000
50%    158.000000      8.000000    5.000000    5.000000     8.000000
75%    209.500000     13.000000   13.000000    7.000000     9.000000
max    268.000000     16.000000   55.000000    8.000000     9.000000

       points_per_match
count        107.000000
mean           1.053152
std            0.818315
min            0.066667
25%            0.414286
50%            0.818182
75%            1.612500
max            3.785714

Top 10 players by Player Successful Tackles:
             player_name  value team_name
0        Sandeep Kandola     55       HYD
1         Ravinder Pahal     53       DEL
2  Dharmaraj Cheralathan     41       BLR
4         Mohit Chhillar     39       MUM
5          Surender Nada     39       MUM
3       Manjeet Chhillar     39       BLR
6         Sandeep Narwal     34       PAT
7             Ravi Kumar     33       PUN
8         Somvir Shekhar     32       BLR
9     Deepak Niwas Hooda     32       HYD

Team performance (total Player Successful Tackles):
team_name
MUM    180
BLR    158
HYD    158
PAT    152
JAI    124
DEL    122
KOL    116
PUN    104
Name: value, dtype: int64

Position-wise analysis:
               sum       mean  count
position_name
All Rounder    253  11.500000     22
Defender       760  14.615385     52
Raider         101   3.060606     33

Correlation between matches played and Player Successful Tackles: 0.59

==================================================

Stopped after 10 clicks
Exported 5_df_season2_player-tackle-points.csv

Statistic: Player Tackle Points
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107 entries, 0 to 106
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         107 non-null    int64
 1   player_name       107 non-null    object
 2   match_played      107 non-null    int64
 3   value             107 non-null    int64
 4   team_id           107 non-null    int64
 5   team              0 non-null      object
 6   team_name         107 non-null    object
 7   rank              107 non-null    object
 8   position_id       107 non-null    int64
 9   position_name     107 non-null    object
 10  team_full_name    107 non-null    object
 11  points_per_match  107 non-null    float64
dtypes: float64(1), int64(5), object(6)
memory usage: 10.2+ KB
None
   player_id            player_name  match_played  value  team_id  team  \
0        157         Ravinder Pahal            14     60        2  None
1        248        Sandeep Kandola            16     59        8  None
2         42  Dharmaraj Cheralathan            15     42        1  None
3         71         Mohit Chhillar            14     42        5  None
4        146          Surender Nada            14     41        5  None

  team_name rank  position_id position_name     team_full_name  \
0       DEL    1            9      Defender  Dabang Delhi K.C.
1       HYD    2            9      Defender      Telugu Titans
2       BLR    3            9      Defender    Bengaluru Bulls
3       MUM    4            9      Defender            U Mumba
4       MUM    5            9      Defender            U Mumba

   points_per_match
0          4.285714
1          3.687500
2          2.800000
3          3.000000
4          2.928571
        player_id  match_played       value     team_id  position_id  \
count  107.000000    107.000000  107.000000  107.000000   107.000000
mean   144.261682      8.906542   11.439252    4.803738     6.841121
std     75.375580      4.583672   13.319143    2.320700     3.523906
min     12.000000      1.000000    1.000000    1.000000     0.000000
25%     74.500000      5.000000    2.000000    3.000000     8.000000
50%    158.000000      8.000000    6.000000    5.000000     8.000000
75%    209.500000     13.000000   13.500000    7.000000     9.000000
max    268.000000     16.000000   60.000000    8.000000     9.000000

       points_per_match
count        107.000000
mean           1.161669
std            0.906588
min            0.066667
25%            0.500000
50%            1.000000
75%            1.857143
max            4.285714

Top 10 players by Player Tackle Points:
             player_name  value team_name
0         Ravinder Pahal     60       DEL
1        Sandeep Kandola     59       HYD
2  Dharmaraj Cheralathan     42       BLR
3         Mohit Chhillar     42       MUM
4          Surender Nada     41       MUM
5       Manjeet Chhillar     40       BLR
6            Jeeva Kumar     38       MUM
7         Sandeep Narwal     37       PAT
8             Ravi Kumar     37       PUN
9     Deepak Niwas Hooda     36       HYD

Team performance (total Player Tackle Points):
team_name
MUM    196
HYD    172
BLR    164
PAT    164
JAI    142
DEL    136
KOL    136
PUN    114
Name: value, dtype: int64

Position-wise analysis:
               sum       mean  count
position_name
All Rounder    278  12.636364     22
Defender       836  16.076923     52
Raider         110   3.333333     33

Correlation between matches played and Player Tackle Points: 0.59

==================================================

Stopped after 8 clicks
Exported 6_df_season2_player-raid-points.csv

Statistic: Player Raid Points
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88 entries, 0 to 87
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         88 non-null     int64
 1   player_name       88 non-null     object
 2   match_played      88 non-null     int64
 3   value             88 non-null     int64
 4   team_id           88 non-null     int64
 5   team              0 non-null      object
 6   team_name         88 non-null     object
 7   rank              88 non-null     object
 8   position_id       88 non-null     int64
 9   position_name     88 non-null     object
 10  team_full_name    88 non-null     object
 11  points_per_match  88 non-null     float64
dtypes: float64(1), int64(5), object(6)
memory usage: 8.4+ KB
None
   player_id      player_name  match_played  value  team_id  team team_name  \
0         58  Kashiling Adake            14    114        2  None       DEL
1         81  Rahul Chaudhari            14     98        8  None       HYD
2         26      Ajay Thakur            13     79        1  None       BLR
3         29       Anup Kumar            14     74        5  None       MUM
4         86    Rajesh Narwal            14     69        3  None       JAI

  rank  position_id position_name        team_full_name  points_per_match
0    1            8        Raider     Dabang Delhi K.C.          8.142857
1    2            8        Raider         Telugu Titans          7.000000
2    3            8        Raider       Bengaluru Bulls          6.076923
3    4            8        Raider               U Mumba          5.285714

### season 1

In [11]:
import pandas as pd
import json
import re
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.firefox.options import Options
from bs4 import BeautifulSoup
import time


import requests
import csv
from bs4 import BeautifulSoup
from selenium  import webdriver
import pandas as pd
import numpy as np
from selenium.webdriver.common.by import By
import os


d={"s-10": "44", 
   "s-9": "25", 
   "s-8": "20",
   "s-7": "11",
   "s-6": "10",
   "s-5": "8",
   "s-4": "4",
   "s-3": "3",
   "s-2": "2",
   "s-1": "1",
   "s-all":"0" ,
   
   }


def extract_json_from_script(script_content):
    start = script_content.find('window.statsWidgetData = ')
    if start == -1:
        return None
    start += len('window.statsWidgetData = ')
    
    bracket_count = 0
    end = start
    for i, char in enumerate(script_content[start:]):
        if char == '{':
            bracket_count += 1
        elif char == '}':
            bracket_count -= 1
            if bracket_count == 0:
                end = start + i + 1
                break
    
    if bracket_count != 0:
        return None
    
    json_str = script_content[start:end]
    
    try:
        return json.loads(json_str)
    except json.JSONDecodeError:
        return None

def fetch_and_process_data(url):
    options = webdriver.FirefoxOptions()
    options.add_argument("--headless")
    driver = webdriver.Firefox(options=options)
    
    try:
        driver.get(url)
        
        for i in range(21):
            try:
                element = WebDriverWait(driver, 10).until(
                    EC.presence_of_element_located((By.CLASS_NAME, 'loadmore'))
                )
                driver.execute_script("arguments[0].click();", element)
                time.sleep(1)
            except:
                print(f"Stopped after {i} clicks")
                break
        
        soup = BeautifulSoup(driver.page_source, 'html.parser')
        script_tag = soup.find('script', string=lambda text: text and 'window.statsWidgetData' in text)
        
        if script_tag:
            json_data = extract_json_from_script(script_tag.string)
            if json_data:
                player_data = json_data['stats']['data']
                df = pd.DataFrame(player_data)
                
                df['value'] = pd.to_numeric(df['value'])
                df['match_played'] = pd.to_numeric(df['match_played'])
                
                df['points_per_match'] = df['value'] / df['match_played']
                
                return df, json_data['stats']['stat']
    
    finally:
        driver.quit()
    
    return None, None

urls = [
    f"https://www.prokabaddi.com/stats/{d['s-1']}-102-total-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-1']}-21-successful-raids-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-1']}-22-raid-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-1']}-23-successful-tackles-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-1']}-103-tackle-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-1']}-22-avg-raid-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-1']}-139-avg-tackle-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-1']}-132-do-or-die-raid-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-1']}-104-super-raids-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-1']}-28-super-tackles-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-1']}-100-super-10s-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-1']}-101-high-5s-statistics"
]   

x = 0
for url in urls:
    x+=1
    df, stat_name = fetch_and_process_data(url)
    if df is not None:
        # Create a file name based on the statistic
        file_name = f"{x}_df_season1_{stat_name.lower().replace(' ', '-')}.csv"
        
        # Export the DataFrame to CSV
        df.to_csv(file_name, index=False)
        print(f"Exported {file_name}")
        
        # Display basic information about the DataFrame
        print(f"\nStatistic: {stat_name}")
        print(df.info())
        
        # Display the first few rows
        print(df.head())
        
        # Basic statistics
        print(df.describe())
        
        # Top 10 players by the statistic
        top_10_players = df.sort_values('value', ascending=False).head(10)
        print(f"\nTop 10 players by {stat_name}:")
        print(top_10_players[['player_name', 'value', 'team_name']])
        
        # Team performance
        team_performance = df.groupby('team_name')['value'].sum().sort_values(ascending=False)
        print(f"\nTeam performance (total {stat_name}):")
        print(team_performance)
        
        # Position-wise analysis
        position_analysis = df.groupby('position_name')['value'].agg(['sum', 'mean', 'count'])
        print("\nPosition-wise analysis:")
        print(position_analysis)
        
        # Correlation between matches played and the statistic
        correlation = df['match_played'].corr(df['value'])
        print(f"\nCorrelation between matches played and {stat_name}: {correlation:.2f}")
        
        print("\n" + "="*50 + "\n")
    else:
        print(f"Failed to fetch or process data from {url}")

Stopped after 9 clicks
Exported 1_df_season1_player-total-points.csv

Statistic: Player Total Points
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         96 non-null     int64
 1   player_name       96 non-null     object
 2   match_played      96 non-null     int64
 3   value             96 non-null     int64
 4   team_id           96 non-null     int64
 5   team              0 non-null      object
 6   team_name         96 non-null     object
 7   rank              96 non-null     object
 8   position_id       96 non-null     int64
 9   position_name     96 non-null     object
 10  team_full_name    96 non-null     object
 11  points_per_match  96 non-null     float64
dtypes: float64(1), int64(5), object(6)
memory usage: 9.1+ KB
None
   player_id      player_name  match_played  value  team_id  team team_name  \
0         29       Anup Kumar            16    169        5  None       MUM
1         81  Rahul Chaudhari            14    161        8  None       HYD
2        143   Maninder Singh            16    137        3  None       JAI
3         26      Ajay Thakur            15    127        1  None       BLR
4         58  Kashiling Adake            14    122        2  None       DEL

  rank  position_id position_name        team_full_name  points_per_match
0    1            8        Raider               U Mumba         10.562500
1    2            8        Raider         Telugu Titans         11.500000
2    3            8        Raider  Jaipur Pink Panthers          8.562500
3    4            8        Raider       Bengaluru Bulls          8.466667
4    5            8        Raider     Dabang Delhi K.C.          8.714286
        player_id  match_played       value    team_id  position_id  \
count   96.000000     96.000000   96.000000  96.000000    96.000000
mean    90.416667     10.083333   37.166667   4.583333     6.572917
std     53.285461      4.576063   41.059819   2.301792     3.629542
min      4.000000      1.000000    1.000000   1.000000     0.000000
25%     45.750000      6.750000    5.750000   3.000000     8.000000
50%     84.500000     10.000000   21.000000   5.000000     8.000000
75%    146.250000     14.000000   50.000000   7.000000     9.000000
max    174.000000     16.000000  169.000000   8.000000     9.000000

       points_per_match
count         96.000000
mean           3.094299
std            2.679748
min            0.250000
25%            1.191964
50%            2.113095
75%            3.901282
max           11.500000

Top 10 players by Player Total Points:
        player_name  value team_name
0        Anup Kumar    169       MUM
1   Rahul Chaudhari    161       HYD
2    Maninder Singh    137       JAI
3       Ajay Thakur    127       BLR
4   Kashiling Adake    122       DEL
5  Manjeet Chhillar    122       BLR
6    Surjeet Narwal    120       DEL
7    Sandeep Narwal    119       PAT
8      Jasvir Singh    113       JAI
9       Wazir Singh    111       PUN

Team performance (total Player Total Points):
team_name
JAI    513
MUM    504
PAT    458
BLR    454
HYD    440
DEL    419
KOL    404
PUN    376
Name: value, dtype: int64

Position-wise analysis:
                sum       mean  count
position_name
                 24  12.000000      2
All Rounder     830  41.500000     20
Defender        771  19.769231     39
Raider         1943  55.514286     35

Correlation between matches played and Player Total Points: 0.66

==================================================

Stopped after 8 clicks
Exported 2_df_season1_player-successful-raids.csv

Statistic: Player Successful Raids
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70 entries, 0 to 69
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         70 non-null     int64
 1   player_name       70 non-null     object
 2   match_played      70 non-null     int64
 3   value             70 non-null     int64
 4   team_id           70 non-null     int64
 5   team              0 non-null      object
 6   team_name         70 non-null     object
 7   rank              70 non-null     object
 8   position_id       70 non-null     int64
 9   position_name     70 non-null     object
 10  team_full_name    70 non-null     object
 11  points_per_match  70 non-null     float64
dtypes: float64(1), int64(5), object(6)
memory usage: 6.7+ KB
None
   player_id      player_name  match_played  value  team_id  team team_name  \
0         29       Anup Kumar            16    123        5  None       MUM
1         81  Rahul Chaudhari            14    122        8  None       HYD
2        143   Maninder Singh            16    103        3  None       JAI
3        118   Surjeet Narwal            14     98        2  None       DEL
4         26      Ajay Thakur            15     96        1  None       BLR

  rank  position_id position_name        team_full_name  points_per_match
0    1            8        Raider               U Mumba          7.687500
1    2            8        Raider         Telugu Titans          8.714286
2    3            8        Raider  Jaipur Pink Panthers          6.437500
3    4            8        Raider     Dabang Delhi K.C.          7.000000
4    5            8        Raider       Bengaluru Bulls          6.400000
        player_id  match_played      value    team_id  position_id  \
count   70.000000     70.000000   70.00000  70.000000    70.000000
mean    86.414286     10.685714   27.60000   4.357143     6.185714
std     51.562399      4.576382   34.64955   2.377648     3.688183
min      4.000000      1.000000    1.00000   1.000000     0.000000
25%     44.250000      7.000000    3.00000   2.000000     2.000000
50%     80.500000     12.000000    8.00000   4.000000     8.000000
75%    141.750000     14.000000   43.75000   6.000000     8.000000
max    174.000000     16.000000  123.00000   8.000000     9.000000

       points_per_match
count         70.000000
mean           2.232609
std            2.342189
min            0.062500
25%            0.425000
50%            1.125000
75%            3.284375
max            8.714286

Top 10 players by Player Successful Raids:
       player_name  value team_name
0       Anup Kumar    123       MUM
1  Rahul Chaudhari    122       HYD
2   Maninder Singh    103       JAI
3   Surjeet Narwal     98       DEL
4      Ajay Thakur     96       BLR
5  Kashiling Adake     92       DEL
6       Ravi Dalal     87       PAT
7      Wazir Singh     85       PUN
8     Jasvir Singh     83       JAI
9     Nitin Madane     78       KOL

Team performance (total Player Successful Raids):
team_name
HYD    270
JAI    268
MUM    268
PAT    248
DEL    243
BLR    222
KOL    213
PUN    200
Name: value, dtype: int64

Position-wise analysis:
                sum       mean  count
position_name
                  1   1.000000      1
All Rounder     450  26.470588     17
Defender         72   4.235294     17
Raider         1409  40.257143     35

Correlation between matches played and Player Successful Raids: 0.51

==================================================

Stopped after 7 clicks
Exported 3_df_season1_player-raid-points.csv

Statistic: Player Raid Points
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         71 non-null     int64
 1   player_name       71 non-null     object
 2   match_played      71 non-null     int64
 3   value             71 non-null     int64
 4   team_id           71 non-null     int64
 5   team              0 non-null      object
 6   team_name         71 non-null     object
 7   rank              71 non-null     object
 8   position_id       71 non-null     int64
 9   position_name     71 non-null     object
 10  team_full_name    71 non-null     object
 11  points_per_match  71 non-null     float64
dtypes: float64(1), int64(5), object(6)
memory usage: 6.8+ KB
None
   player_id      player_name  match_played  value  team_id  team team_name  \
0         29       Anup Kumar            16    155        5  None       MUM
1         81  Rahul Chaudhari            14    151        8  None       HYD
2        143   Maninder Singh            16    130        3  None       JAI
3         26      Ajay Thakur            15    122        1  None       BLR
4         58  Kashiling Adake            14    113        2  None       DEL

  rank  position_id position_name        team_full_name  points_per_match
0    1            8        Raider               U Mumba          9.687500
1    2            8        Raider         Telugu Titans         10.785714
2    3            8        Raider  Jaipur Pink Panthers          8.125000
3    4            8        Raider       Bengaluru Bulls          8.133333
4    5            8        Raider     Dabang Delhi K.C.          8.071429
       player_id  match_played       value    team_id  position_id  \
count   71.00000     71.000000   71.000000  71.000000    71.000000
mean    87.43662     10.704225   34.788732   4.338028     6.098592
std     51.91249      4.546252   43.028534   2.366092     3.734606
min      4.00000      1.000000    1.000000   1.000000     0.000000
25%     44.50000      7.000000    4.000000   2.000000     0.000000
50%     81.00000     12.000000   12.000000   4.000000     8.000000
75%    142.50000     14.000000   59.500000   6.000000     8.000000
max    174.00000     16.000000  155.000000   8.000000     9.000000

       points_per_match
count         71.000000
mean           2.841896
std            2.916466
min            0.062500
25%            0.500000
50%            1.500000
75%            4.468750
max           10.785714

Top 10 players by Player Raid Points:
       player_name  value team_name
0       Anup Kumar    155       MUM
1  Rahul Chaudhari    151       HYD
2   Maninder Singh    130       JAI
3      Ajay Thakur    122       BLR
4  Kashiling Adake    113       DEL
5   Surjeet Narwal    113       DEL
6       Ravi Dalal    111       PAT
7     Jasvir Singh    106       JAI
8      Wazir Singh    104       PUN
9     Nitin Madane    101       KOL

Team performance (total Player Raid Points):
team_name
MUM    347
JAI    343
HYD    336
PAT    316
BLR    291
DEL    285
KOL    283
PUN    269
Name: value, dtype: int64

Position-wise analysis:
                sum       mean  count
position_name
                  1   1.000000      1
All Rounder     568  31.555556     18
Defender         99   5.823529     17
Raider         1802  51.485714     35

Correlation between matches played and Player Raid Points: 0.51

==================================================

Stopped after 8 clicks
Exported 4_df_season1_player-successful-tackles.csv

Statistic: Player Successful Tackles
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85 entries, 0 to 84
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   player_id         85 non-null     int64
 1   player_name       85 non-null     object
 2   match_played      85 non-null     int64
 3   value             85 non-null     int64
 4   team_id           85 non-null     int64
 5   team              0 non-null      object
 6   team_name         85 non-null     object
 7   rank              85 non-null     object
 8   position_id       85 non-null     int64
 9   position_name     85 non-null     object
 10  team_full_name    85 non-null     object
 11  points_per_match  85 non-null     float64
dtypes: float64(1), int64(5), object(6)
memory usage: 8.1+ KB
None
   player_id            player_name  match_played  value  team_id  team  \
0         69       Manjeet Chhillar            16     51        1  None
1        146          Surender Nada            15     47        5  None
2         96             Rohit Rana            15     37        3  None
3         51     Jasmer Singh Gulia            14     36        2  None
4         42  Dharmaraj Cheralathan            16     34        1  None

  team_name rank  position_id position_name        team_full_name  \
0       BLR    1            0   All Rounder       Bengaluru Bulls
1       MUM    2            9      Defender               U Mumba
2       JAI    3            9      Defender  Jaipur Pink Panthers
3       DEL    4            0   All Rounder     Dabang Delhi K.C.
4       BLR    5            9      Defender       Bengaluru Bulls

   points_per_match
0          3.187500
1          3.133333
2          2.466667
3          2.571429
4          2.125000
        player_id  match_played      value    team_id  position_id  \
count   85.000000     85.000000  85.000000  85.000000    85.000000
mean    91.364706     10.564706  11.741176   4.470588     6.576471
std     52.002025      4.454658  11.238913   2.332933     3.694837
min      4.000000      1.000000   1.000000   1.000000     0.000000
25%     52.000000      8.000000   3.000000   2.000000     8.000000
50%     85.000000     12.000000   8.000000   4.000000     8.000000
75%    146.000000     14.000000  19.000000   7.000000     9.000000
max    174.000000     16.000000  51.000000   8.000000     9.000000

       points_per_match
count         85.000000
mean           1.020677
std            0.763229
min            0.100000
25%            0.400000
50%            0.812500
75%            1.428571
max            3.222222

Top 10 players by Player Successful Tackles:
              player_name  value team_name
0        Manjeet Chhillar     51       BLR
1           Surender Nada     47       MUM
2              Rohit Rana     37       JAI
3      Jasmer Singh Gulia     36       DEL
4   Dharmaraj Cheralathan     34       BLR
5          Mohit Chhillar     30       MUM
6          Ravinder Pahal     29       DEL
7         Prashant Chavan     28       JAI
8     Amit Singh Chhillar     26       DEL
10          Rajesh Narwal     25       JAI

Team performance (total Player Successful Tackles):
team_name
JAI    158
BLR    153
MUM    145
DEL    124
PAT    124
KOL    105
HYD     96
PUN     93
Name: value, dtype: int64

Position-wise analysis:
               sum       mean  count
position_name
                22  11.000000      2
All Rounder    242  13.444444     18
Defender       611  15.666667     39
Raider         123   4.730769     26

Correlation between matches played and Player Successful Tackles: 0.60

==================================================

### all

In [ ]:
import pandas as pd
import json
import re
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.firefox.options import Options
from bs4 import BeautifulSoup
import time


import requests
import csv
from bs4 import BeautifulSoup
from selenium  import webdriver
import pandas as pd
import numpy as np
from selenium.webdriver.common.by import By
import os


d={"s-10": "44", 
   "s-9": "25", 
   "s-8": "20",
   "s-7": "11",
   "s-6": "10",
   "s-5": "8",
   "s-4": "4",
   "s-3": "3",
   "s-2": "2",
   "s-1": "1",
   "s-all":"0" ,
   
   }


def extract_json_from_script(script_content):
    start = script_content.find('window.statsWidgetData = ')
    if start == -1:
        return None
    start += len('window.statsWidgetData = ')
    
    bracket_count = 0
    end = start
    for i, char in enumerate(script_content[start:]):
        if char == '{':
            bracket_count += 1
        elif char == '}':
            bracket_count -= 1
            if bracket_count == 0:
                end = start + i + 1
                break
    
    if bracket_count != 0:
        return None
    
    json_str = script_content[start:end]
    
    try:
        return json.loads(json_str)
    except json.JSONDecodeError:
        return None

def fetch_and_process_data(url):
    options = webdriver.FirefoxOptions()
    options.add_argument("--headless")
    driver = webdriver.Firefox(options=options)
    
    try:
        driver.get(url)
        
        for i in range(21):
            try:
                element = WebDriverWait(driver, 10).until(
                    EC.presence_of_element_located((By.CLASS_NAME, 'loadmore'))
                )
                driver.execute_script("arguments[0].click();", element)
                time.sleep(1)
            except:
                print(f"Stopped after {i} clicks")
                break
        
        soup = BeautifulSoup(driver.page_source, 'html.parser')
        script_tag = soup.find('script', string=lambda text: text and 'window.statsWidgetData' in text)
        
        if script_tag:
            json_data = extract_json_from_script(script_tag.string)
            if json_data:
                player_data = json_data['stats']['data']
                df = pd.DataFrame(player_data)
                
                df['value'] = pd.to_numeric(df['value'])
                df['match_played'] = pd.to_numeric(df['match_played'])
                
                df['points_per_match'] = df['value'] / df['match_played']
                
                return df, json_data['stats']['stat']
    
    finally:
        driver.quit()
    
    return None, None

urls = [
    f"https://www.prokabaddi.com/stats/{d['s-all']}-102-total-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-all']}-21-successful-raids-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-all']}-22-raid-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-all']}-23-successful-tackles-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-all']}-103-tackle-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-all']}-22-avg-raid-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-all']}-139-avg-tackle-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-all']}-132-do-or-die-raid-points-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-all']}-104-super-raids-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-all']}-28-super-tackles-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-all']}-100-super-10s-statistics",
    f"https://www.prokabaddi.com/stats/{d['s-all']}-101-high-5s-statistics"
]   

x = 0
for url in urls:
    x+=1
    df, stat_name = fetch_and_process_data(url)
    if df is not None:
        # Create a file name based on the statistic
        file_name = f"{x}_df_season_combinedall_{stat_name.lower().replace(' ', '-')}.csv"
        
        # Export the DataFrame to CSV
        df.to_csv(file_name, index=False)
        print(f"Exported {file_name}")
        
        # Display basic information about the DataFrame
        print(f"\nStatistic: {stat_name}")
        print(df.info())
        
        # Display the first few rows
        print(df.head())
        
        # Basic statistics
        print(df.describe())
        
        # Top 10 players by the statistic
        top_10_players = df.sort_values('value', ascending=False).head(10)
        print(f"\nTop 10 players by {stat_name}:")
        print(top_10_players[['player_name', 'value', 'team_name']])
        
        # Team performance
        team_performance = df.groupby('team_name')['value'].sum().sort_values(ascending=False)
        print(f"\nTeam performance (total {stat_name}):")
        print(team_performance)
        
        # Position-wise analysis
        position_analysis = df.groupby('position_name')['value'].agg(['sum', 'mean', 'count'])
        print("\nPosition-wise analysis:")
        print(position_analysis)
        
        # Correlation between matches played and the statistic
        correlation = df['match_played'].corr(df['value'])
        print(f"\nCorrelation between matches played and {stat_name}: {correlation:.2f}")
        
        print("\n" + "="*50 + "\n")
    else:
        print(f"Failed to fetch or process data from {url}")